// DEFINE_PATCH_FUNCTION check_for_sig_mismatch 
// RET
//     mismatched
// BEGIN

//     SET mismatched = 0
//     READ_ASCII 0x0 sig (4)

//     PATCH_IF "%sig%" STR_EQ "ITM " BEGIN

//         PATCH_IF NOT "%SOURCE_EXT%" STR_EQ "itm" BEGIN
//             mismatched = 1
//         END

//     END ELSE PATCH_IF "%sig%" STR_EQ "SPL " BEGIN

//         PATCH_IF NOT "%SOURCE_EXT%" STR_EQ "spl" BEGIN
//             mismatched = 1
//         END

//     END PATCH_IF "%sig%" STR_EQ "CRE " BEGIN

//         PATCH_IF NOT "%SOURCE_EXT%" STR_EQ "cre" BEGIN
//             mismatched = 1
//         END

//     END PATCH_IF "%sig%" STR_EQ "EFF " BEGIN

//         PATCH_IF NOT "%SOURCE_EXT%" STR_EQ "eff" BEGIN
//             mismatched = 1
//         END

//     END PATCH_IF "%sig%" STR_EQ "PRO " BEGIN

//         PATCH_IF NOT "%SOURCE_EXT%" STR_EQ "pro" BEGIN
//             mismatched = 1
//         END

//     END 

//     PATCH_IF 1 BEGIN
//         LPF LOG_TEXT STR_VAR message="Found a file with mismatched signature and file extension: %SOURCE_FILE%" END
//     END

// END

DEFINE_PATCH_FUNCTION CHECK_EXTENSION
INT_VAR
    fail_on_mismatch = 1
    suppress = 0
STR_VAR
    extension = ""
RET
    result
   // mismatched
BEGIN
    PATCH_IF STRING_LENGTH "%extension%" = 0 BEGIN
        PATCH_FAIL "[FAIL]: Extension is empty"
    END

    result = 1
  //  mismatched = 0
  //  LPF check_for_sig_mismatch RET mismatched END
    PATCH_IF NOT "%SOURCE_EXT%" STR_EQ "%extension%" BEGIN

        result = 0
        PATCH_IF NOT suppress BEGIN

            PATCH_IF fail_on_mismatch BEGIN
                PATCH_FAIL "[WARN]: This function only works for .%extension% files"
            END ELSE BEGIN
                PATCH_WARN "[WARN]: This function only works for .%extension% files"
            END

        END

    END

END

DEFINE_DIMORPHIC_FUNCTION ~IS_BIT_SET~
INT_VAR
    bit       = "-1"
    bit_field = "-1"
    bit_limit = 32
RET
    result // 1 if flag is set, 0 if it's unset. -1 if invalid flag is asked for
BEGIN
    ACTION_IF bit_field = "-1" BEGIN
        FAIL "[FAIL]: Bit field not set"
    END

    ACTION_IF bit >= 0 AND bit < bit_limit BEGIN
        OUTER_SET bitmask = (1 << bit)
        OUTER_SET result = (bit_field & bitmask) != 0
    END ELSE BEGIN
        OUTER_SET result = "-1"
    END
END

DEFINE_PATCH_FUNCTION IS_FLAG_SET
INT_VAR
    flag = "-1"
RET
    result // 1 if flag is set, 0 if it's unset. -1 if invalid flag is asked for
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "ITM" END
    END

    READ_LONG 0x18 itm_flags
    LPF IS_BIT_SET INT_VAR bit = flag bit_field = itm_flags RET set = result END
    result = set
END

DEFINE_PATCH_FUNCTION IS_USABILITY_FLAG_SET
INT_VAR
    flag = "-1"
RET
    result // 1 if flag is set, 0 if it's unset. -1 if invalid flag is asked for
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "ITM" END
    END

    READ_LONG 0x1e itm_flags
    LPF IS_BIT_SET INT_VAR bit = flag bit_field = itm_flags RET set = result END
    result = set
END

DEFINE_PATCH_FUNCTION CRE_IS_FLAG_SET
INT_VAR
    flag = "-1"
RET
    result
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "CRE" END
    END

    READ_LONG 0x10 cre_flags
    LPF IS_BIT_SET INT_VAR bit = flag bit_field = cre_flags RET set = result END
    result = set
END

DEFINE_DIMORPHIC_FUNCTION ~RGB~
INT_VAR
    red = 0
    green = 0
    blue = 0
RET
    result
BEGIN
    OUTER_SET result = (red << 8) + (green << 16) + (blue << 24) // this works, idk why
END
