DEFINE_PATCH_FUNCTION WPN_DMG
INT_VAR
    type = 1
RET
    result
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "ITM" END
    END

    LPF ITM_LAST_HEADER_TYPE INT_VAR type = type RET header = result END
    PATCH_IF header != "-1" BEGIN
        SET offset = 0x72 + (header * 0x38)
        READ_SHORT (offset + 0x1a) result
    END ELSE BEGIN
        SET result = "-1"
    END
END

DEFINE_PATCH_FUNCTION WPN_DICENUM
INT_VAR
    type = 1
RET
    result
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "ITM" END
    END

    LPF ITM_LAST_HEADER_TYPE INT_VAR type = type RET header = result END
    PATCH_IF header != "-1" BEGIN
    SET offset = 0x72 + (header * 0x38)
        READ_BYTE (offset + 0x19) result
    END ELSE BEGIN
        SET result = "-1"
    END
END

DEFINE_PATCH_FUNCTION WPN_SPEED
INT_VAR
    type = 1
RET
    result
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "ITM" END
    END

    LPF ITM_LAST_HEADER_TYPE INT_VAR type = type RET header = result END
    PATCH_IF header != "-1" BEGIN
        SET offset = 0x72 + (header * 0x38)
        READ_BYTE (offset + 0x12) result
    END ELSE BEGIN
        SET result = "-1"
    END
END

DEFINE_PATCH_FUNCTION WPN_DICESIZE
INT_VAR
    type = 1
RET
    result
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "ITM" END
    END

    LPF ITM_LAST_HEADER_TYPE INT_VAR type = type RET header = result END
    PATCH_IF header != "-1" BEGIN
        SET offset = 0x72 + (header * 0x38)
        READ_BYTE (offset + 0x16) result
    END ELSE BEGIN
        SET result = "-1"
    END
END

DEFINE_PATCH_FUNCTION WPN_THAC0
INT_VAR
    type = 1
RET
    result
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "ITM" END
    END

    LPF ITM_LAST_HEADER_TYPE INT_VAR type = type RET header = result END
    PATCH_IF header != "-1" BEGIN
        SET offset = 0x72 + (header * 0x38)
        READ_BYTE (offset + 0x14) result
    END ELSE BEGIN
        SET result = "-999"
    END
END

DEFINE_PATCH_FUNCTION GET_SHIELD_LEVEL
RET
   result
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "ITM" END
    END

    SET original_ac = "-1"
    SET result = "-1"
    GET_OFFSET_ARRAY eff_arr 0x6a 4 0x70 2 0 0 0x30
    PHP_EACH eff_arr AS int => ab_off BEGIN
        PATCH_IF SHORT_AT(ab_off) = 0 AND LONG_AT(ab_off + 0x8) = 0 BEGIN
            result = (LONG_AT(ab_off + 0x4)) - 1
            PATCH_IF result = "-1" BEGIN
                PATCH_WARN "[WARN]: Something went wrong, the shield %SOURCE_RES% had no base AC value: %result%"
            END
        END
    END
END

