// This function tries to find the last valid header of a spell or item ability in a given file. A "valid" header is defined
// as either the last header in a sequence of headers or a header that represents a "gap" in the sequence.

DEFINE_PATCH_FUNCTION LAST_VALID_HEADER
INT_VAR
    type = "-1"
    level_to_avoid = 100
RET
    result
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "SPL" END
    END

    READ_LONG 0x64 ability_offset
    READ_SHORT 0x68 num_abilities

    PATCH_IF num_abilities > 1 BEGIN // #1 if there's at least more than one header to look at...
        READ_SHORT (ability_offset + 0x10) first_casting_level // first header casting level
        READ_SHORT (ability_offset + 0x28 + 0x10) next_casting_level // first scaling header (i.e. second one)
        PATCH_IF next_casting_level < level_to_avoid BEGIN // #2 if the diff between both is one, let's continue...
           // PATCH_IF num_abilities > 2 BEGIN // #3 if we have more headers to examine, let's continue...
                SET found = 0
                FOR ( h = 2; h < num_abilities; ++h ) BEGIN
                    SET new_offset = ability_offset + (0x28 * h) + 0x10
                    READ_SHORT new_offset curr_casting_level
                    SET diff = curr_casting_level - next_casting_level
                    PATCH_IF diff > 1 BEGIN // #4 if the diff is more than one, we found it
                        result = h - 1
                        h = num_abilities + 1 // i.e. break
                        found = 1
                    END
                    next_casting_level = curr_casting_level
                END
                PATCH_IF found = 0 BEGIN
                    result = num_abilities - 1
                END
        END ELSE BEGIN // #2 otherwise, the last valid header in question is the previous one: the first header
            result = 0
        END
    END ELSE BEGIN // #1 otherwise, the last valid header will be the first one, or none if none are present
        result = num_abilities - 1
    END
END

DEFINE_PATCH_FUNCTION ITM_LAST_HEADER_TYPE
INT_VAR
    type = 1
RET
    result
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "ITM" END
    END

    READ_LONG 0x64 ability_offset
    READ_SHORT 0x68 num_abilities

    PATCH_IF num_abilities > 1 BEGIN
        SET bytes = 0x38
        SET header = 0
        FOR ( h = 1; h < num_abilities; ++h ) BEGIN
            ability_offset += bytes
            SET t = BYTE_AT (ability_offset)
            PATCH_IF t = type BEGIN
                header = h
            END
        END
        result = header
    END ELSE BEGIN
        SET t = BYTE_AT (ability_offset)
        PATCH_IF t = type BEGIN
            result = 0
        END ELSE BEGIN
            result = "-1"
        END
    END
END

// This function tries to see if an opcode (effect) is present in a given creature file.
DEFINE_PATCH_MACRO CRE_OP_PRESENT
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "CRE" END
    END

    READ_LONG 0x2c4 eff_offset
    READ_LONG 0x2c8 eff_length
    READ_BYTE 0x33 eff_type

    PATCH_IF eff_type = 0 BEGIN
        SET effect_size = 0x30
    END ELSE BEGIN
        SET effect_size = 0x108
    END

    SET present = 0
    SET found = 0
    FOR ( index = 0; index < eff_length; ++index ) BEGIN
        PATCH_IF eff_type = 0 BEGIN
            READ_SHORT eff_offset op
        END ELSE BEGIN
            READ_LONG (eff_offset + 0x08) op
        END

        PATCH_IF op = opcode1 OR op = opcode2 BEGIN
            found = 1
            index = eff_length // break
        END

        eff_offset += effect_size
    END
    present = found

END

DEFINE_PATCH_MACRO SPELL_OPCODE_PRESENT
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "SPL" END
        PATCH_IF opcode <= 0 BEGIN
            PATCH_FAIL ~[DEBUG][FAIL]: Invalid opcode specified for SPELL_OPCODE_PRESENT.~
        END
    END

    SET present = 0
    READ_LONG 0x64 ability_offset
    READ_SHORT 0x68 num_abilities

    PATCH_IF num_abilities > 0 BEGIN
        SET effect_offset = LONG_AT 0x6a
        SET globals_number = SHORT_AT 0x70
        SET effects_number = SHORT_AT (ability_offset + 0x1e)

        PATCH_IF effects_number > 0 BEGIN

            SET p2_set = VARIABLE_IS_SET "parameter2"
            SET res_set = VARIABLE_IS_SET "resource"
            SET matches_needed = 1 + p2_set + res_set

            FOR ( index = 0; index < effects_number; ++index ) BEGIN

                SET base_eff_offset = effect_offset + (globals_number * 0x30) + (index * 0x30)
                READ_SHORT base_eff_offset op
                READ_LONG (base_eff_offset + 0x08) p2
                READ_ASCII (base_eff_offset + 0x14) assigned_resource
                SET matches = 0
                PATCH_IF opcode = op BEGIN

                    ++matches

                    PATCH_IF p2_set OR res_set BEGIN
                        PATCH_IF p2_set AND parameter2 = p2 BEGIN
                            ++matches
                        END

                        PATCH_IF res_set AND "%resource%" STR_EQ "%assigned_resource%" BEGIN
                            ++matches
                        END
                    END
                END

                PATCH_IF matches = matches_needed BEGIN
                    present = 1
                    index = effects_number
                END
            END

        END
    END

END

// checks globals only
DEFINE_PATCH_MACRO ITM_OPCODE_PRESENT
BEGIN
    PATCH_IF zs_debug BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "ITM" END
        PATCH_IF opcode <= 0 BEGIN
            PATCH_FAIL ~[DEBUG][FAIL]: Invalid opcode specified for ITM_OPCODE_PRESENT.~
        END
    END

    SET present = 0
    READ_LONG 0x6a ability_offset
    READ_SHORT 0x70 effects_number

    PATCH_IF effects_number > 0 BEGIN

        SET p2_set = VARIABLE_IS_SET "parameter2"
        SET res_set = VARIABLE_IS_SET "resource"
        SET matches_needed = 1 + p2_set + res_set

        FOR ( index = 0; index < effects_number; ++index ) BEGIN

            SET base_eff_offset = ability_offset + (index * 0x30)
            READ_SHORT base_eff_offset op
            READ_LONG (base_eff_offset + 0x08) p2
            READ_ASCII (base_eff_offset + 0x14) assigned_resource
            SET matches = 0

            PATCH_IF opcode = op BEGIN

                ++matches
                PATCH_IF p2_set OR res_set BEGIN
                    PATCH_IF p2_set AND parameter2 = p2 BEGIN
                        ++matches
                    END

                    PATCH_IF res_set AND "%resource%" STR_EQ "%assigned_resource%" BEGIN
                        ++matches
                    END
                END
            END

            PATCH_IF matches = matches_needed BEGIN
                present = 1
                index = effects_number
            END

        END

    END

END

DEFINE_PATCH_FUNCTION IS_WEAPON_EQUIPPED
INT_VAR
    at_slot = 0
    anywhere = 0
STR_VAR
    weapon = ~*~
RET
    found
BEGIN
    // precondition checks
    PATCH_IF zs_debug AND NOT FILE_EXISTS_IN_GAME ~%weapon%.itm~ BEGIN
        PATCH_FAIL ~[DEBUG][FAIL]: Weapon %weapon% does not exist in game~
    END

    PATCH_IF at_slot < 0 OR at_slot > 4 BEGIN
        PATCH_FAIL ~[FAIL]: at_slot must be set between 1 and 4 (inclusive)~
    END

    PATCH_IF anywhere != 0 AND anywhere != 1 BEGIN
        PATCH_FAIL ~[FAIL]: anywhere must be set to 0 (false) or 1 (true)~
    END

    PATCH_IF at_slot > 0 AND anywhere = 1 BEGIN
        PATCH_FAIL ~[FAIL]: at_slot must not be set when anywhere is on (1)~
    END

    PATCH_IF at_slot > 0 AND anywhere = 1 BEGIN
        PATCH_FAIL ~[FAIL]: Cannot mix indiscriminate searching with searching at particular slot~
    END

    SET found = 0
    READ_LONG 0x2bc item_offset
    READ_LONG 0x2b8 item_slots_offset

    PATCH_IF anywhere BEGIN
        READ_SHORT (item_slots_offset + (9 * 2)) weapon1
        READ_SHORT (item_slots_offset + (10 * 2)) weapon2
        READ_SHORT (item_slots_offset + (11 * 2)) weapon3
        READ_SHORT (item_slots_offset + (12 * 2)) weapon4

        PATCH_FOR_EACH value IN "%weapon1%" "%weapon2%" "%weapon3%" "%weapon4%" BEGIN
            
            PATCH_IF value != "-1" BEGIN
                READ_ASCII (item_offset + (0x14 * value)) equipped_weapon
                PATCH_IF "%equipped_weapon%" STR_EQ ~%weapon%~ BEGIN
                    found = 1
                END
            END
        END

    END ELSE BEGIN
        PATCH_IF at_slot = 1 BEGIN
            READ_SHORT (item_slots_offset + (9 * 2)) weapon1
            READ_ASCII (item_offset + (0x14 * weapon1)) equipped_weapon
            PATCH_IF "%equipped_weapon%" STR_EQ ~%weapon%~ BEGIN
                found = 1
            END
        END ELSE PATCH_IF at_slot = 2 BEGIN
            READ_SHORT (item_slots_offset + (10 * 2)) weapon2
            READ_ASCII (item_offset + (0x14 * weapon2)) equipped_weapon
            PATCH_IF "%equipped_weapon%" STR_EQ ~%weapon%~ BEGIN
                found = 1
            END
        END ELSE PATCH_IF at_slot = 3 BEGIN
            READ_SHORT (item_slots_offset + (11 * 2)) weapon3
            READ_ASCII (item_offset + (0x14 * weapon3)) equipped_weapon
            PATCH_IF "%equipped_weapon%" STR_EQ ~%weapon%~ BEGIN
                found = 1
            END
        END ELSE PATCH_IF at_slot = 4 BEGIN
            READ_SHORT (item_slots_offset + (12 * 2)) weapon4
            READ_ASCII (item_offset + (0x14 * weapon4)) equipped_weapon
            PATCH_IF "%equipped_weapon%" STR_EQ ~%weapon%~ BEGIN
                found = 1
            END
        END
    END

    // postcondition check
    PATCH_IF zs_debug AND found != 0 AND found != 1 BEGIN
        PATCH_FAIL ~[DEBUG][FAIL]: Found value is not 0 or 1~
    END
END

DEFINE_PATCH_FUNCTION IS_HELMET_EQUIPPED
STR_VAR
    match_resource = ""
RET
    found
    which
BEGIN
    SET res_len = STRING_LENGTH "%match_resource%"
    PATCH_IF zs_debug = TRUE BEGIN
        LPF CHECK_EXTENSION STR_VAR extension = "CRE" END

        PATCH_IF res_len > 8 BEGIN
            PATCH_FAIL "[DEBUG][FAIL]: IS_HELMET_EQUIPPED function launched with an illegal resource filename length of %res_len%"
        END
    END

    SPRINT which ""
    SET find_any = res_len == 0
    SET found = FALSE
    READ_LONG 0x2b0 items_count
    PATCH_IF items_count > 0 BEGIN

        READ_LONG 0x2b8 item_slots_offset
        READ_SHORT item_slots_offset helmet_slot

        PATCH_IF helmet_slot > "-1" AND (helmet_slot + 1) <= items_count BEGIN

            PATCH_IF NOT find_any BEGIN

                READ_LONG 0x2bc items_offset
                SET item_size = 0x14
                READ_ASCII (items_offset + (helmet_slot * item_size)) resource
                SET found = "%resource%" STR_EQ "%match_resource%"
                SPRINT which "%resource%"

            END ELSE BEGIN
                found = TRUE
            END

        END
    END
END

DEFINE_ACTION_FUNCTION PROTECT_FOR_RESOURCE
INT_VAR
    target_206 = 1
    target_318 = 1
    target_321 = 1
    target_324 = 1
STR_VAR
    target_resource = ""
    resource_to_clone = ""
BEGIN
    ACTION_IF zs_debug BEGIN

        ACTION_IF target_206 != 1 AND target_318 != 1 AND target_321 != 1 AND target_324 != 1 BEGIN
            LAF LOG_TEXT
                STR_VAR
                    filename = "crash"
                    log_level = "fail"
                    message = "NO OPCODES SELECTED FOR FUNCTION PROTECT_FOR_RESOURCE"
            END
        END

        ACTION_IF STRING_LENGTH target_resource = 0 OR STRING_LENGTH resource_to_clone = 0 BEGIN
            LAF LOG_TEXT
                STR_VAR
                    filename = "crash"
                    log_level = "fail"
                    message = "EMPTY RESOURCES SELECTED FOR FUNCTION PROTECT_FOR_RESOURCE"
            END
        END

    END

    COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
                         ~^.+\.itm$~ ~override~
                         ~^.+\.spl$~ ~override~

        PATCH_IF INDEX_BUFFER(%target_resource%) >= 0 BEGIN
            
            PATCH_IF target_206 BEGIN
                LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode=206 STR_VAR match_resource = "%target_resource%" resource="%resource_to_clone%" END
            END

            PATCH_IF target_318 BEGIN
                LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode=318 STR_VAR match_resource = "%target_resource%" resource="%resource_to_clone%" END
            END

            PATCH_IF target_321 BEGIN
                LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode=321 STR_VAR match_resource = "%target_resource%" resource="%resource_to_clone%" END
            END

            PATCH_IF target_324 BEGIN
                LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode=324 STR_VAR match_resource = "%target_resource%" resource="%resource_to_clone%" END
            END

        END

    BUT_ONLY
END

