COPY_EXISTING ~WA2DAK.ITM~ ~override~
    LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6331) id_ref_name=RESOLVE_STR_REF(@6330) ench=3 END
    LPF ALTER_HEADER INT_VAR match_damage=2 match_to_hit=2 match_speed=2 to_hit=3 speed=1 damage=3 END
    PATCH_IF MOD_IS_INSTALLED "ZSTweaks.tp2" "1450" BEGIN // update bonus due to +3 enchantment
        LPF ALTER_EFFECT INT_VAR check_globals = 0 match_opcode = 326 STR_VAR match_resource = ~ZSTWK2~ resource = ~ZSTWK3~ END
    END
BUT_ONLY
