ACTION_IF GAME_IS "bg2ee eet" BEGIN
    COPY ~%MOD_FOLDER%/items/cleric_staff~ ~override~
    COPY_EXISTING ~STAF19.ITM~ ~override~
        LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@7060) END
        LPF ADD_ITEM_HEADER INT_VAR target=5 charges=2 depletion=3 flags =2**9 + 2**11 STR_VAR icon=~SPPR514B~ END
        LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=146,tgt=1,t=3,p1=1,tmg=1,res=SPPR514~ END
        LPF ADD_EQUIPPED_EFF INT_VAR p1 = 204 p2 = 5
        STR_VAR effects = ~op=0,p1=1,p2=0;op=177,res=ZSTWSF01;op=177,res=ZSTWSF02;op=177,res=ZSTWSF03~ END
END
