ACTION_IF GAME_IS "bg2ee eet" BEGIN
COPY ~ZSTweaks/eff/ZSTWTRL0.EFF~ ~override~
    COPY_EXISTING ~SW2H12.ITM~ ~override~
        PATCH_IF MOD_IS_INSTALLED "ZSTweaks.tp2" "1318" OR group_component = 1 BEGIN
            LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6172) END
        END ELSE BEGIN
            LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6171) END
        END
        LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=177,tmg=1,p1=129,p2=4,res=ZSTWTRL0~ END
    BUT_ONLY
END
