ACTION_IF GAME_IS "bg2ee eet" BEGIN
    COPY ~%MOD_FOLDER%/items/wave~ ~override~
    COPY_EXISTING "HALB09.ITM" ~override~
        LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6420) END
        LPF ALTER_EFFECT INT_VAR match_opcode = 12 match_probability1=15 probability1 = 14 END
        LPF ALTER_EFFECT INT_VAR match_opcode = 12 special = 1024 END
        LPF GET_DMG_TYPE STR_VAR type = ~cold~ RET cold = result END
        LPF ADD_ON_HIT_EFF INT_VAR tmg=1 STR_VAR effects = ~op=12,p1=3,p2=%cold%,spec=1024;op=177,p1=142,p2=4,res=ZSTWWAVE~ END
END
