OUTER_SET group_component = 1

INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1200.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1201.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1202.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1280.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1290.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1300.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1318.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1322.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1390.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1410.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1420.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1460.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1540.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1587.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1590.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1591.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1592.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1593.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1594.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1595.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1597.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1599.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1602.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1603.tph~
INCLUDE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks/zs_comp_1604.tph~
