ACTION_IF GAME_IS "bg2ee eet" BEGIN
    COPY_EXISTING "SW2H08.ITM" ~override~
        PATCH_IF !(MOD_IS_INSTALLED "ZSTweaks.tp2" "1592") BEGIN
            LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6830) END
        END ELSE BEGIN
            LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6850) END
        END
        LPF ALTER_EFFECT INT_VAR match_opcode = 54 match_duration = 120 duration = 30 savingthrow = 1 savebonus = "-4" END
    BUT_ONLY
END
