IF
    Global("zs_antipsycho_guard_variable","GLOBAL",0)
THEN
    RESPONSE #100
        SetGlobal("zs_antipsycho_guard_variable","MYAREA",1)
        ApplySpellRES("ZSTWPSYC", Player1)
        ApplySpellRES("ZSTWPSYC", Player2)
        ApplySpellRES("ZSTWPSYC", Player3)
        ApplySpellRES("ZSTWPSYC", Player4)
        ApplySpellRES("ZSTWPSYC", Player5)
        ApplySpellRES("ZSTWPSYC", Player6)

        ChangeStat(Player1, MORALERECOVERYTIME, replaceme, SET)
        ChangeStat(Player2, MORALERECOVERYTIME, replaceme, SET)
        ChangeStat(Player3, MORALERECOVERYTIME, replaceme, SET)
        ChangeStat(Player4, MORALERECOVERYTIME, replaceme, SET)
        ChangeStat(Player5, MORALERECOVERYTIME, replaceme, SET)
        ChangeStat(Player6, MORALERECOVERYTIME, replaceme, SET)
        Continue()
END