ACTION_IF GAME_IS "bg2ee eet" BEGIN
    COPY_EXISTING ~SW1H66.ITM~ ~override~
        LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6110) END
        LPF ALTER_EFFECT INT_VAR check_headers = 0 match_opcode = 0 parameter1 = 2 END
        LPF ADD_EQUIPPED_EFF INT_VAR p1 = 5 STR_VAR effects=~op=0,p1=1,p2=2;op=0,p1=1,p2=4;op=0,p1=1,p2=8;op=27;op=28;op=29;op=30;op=31;op=86;op=87;op=88;op=89;op=166;op=173~ END
    BUT_ONLY
END
