ACTION_IF GAME_IS "bg2ee eet" BEGIN
    COPY ~ZSTweaks/eff/ZSTWTHM1.EFF~ ~override~
        ~ZSTweaks/eff/ZSTWTHM2.EFF~ ~override~
        ~ZSTweaks/eff/ZSTWTHM3.EFF~ ~override~

    COPY_EXISTING ~WA2RING.ITM~ ~override~
        LPF ALTER_ITEM INT_VAR unusable0=1611987392 id_ref_desc=RESOLVE_STR_REF(@6340) END
        LPF ADD_EQUIPPED_EFF INT_VAR p1=4 p2=5 STR_VAR effects=~op=177,res=ZSTWTHM1;op=177,res=ZSTWTHM2;op=177,res=ZSTWTHM3~ END
    BUT_ONLY
END
