ACTION_IF GAME_IS "bg2ee eet" BEGIN
    COPY_EXISTING ~RING44.ITM~ ~override~
        LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6790) END
        LPF DELETE_EFFECT INT_VAR check_headers=0 match_opcode=62 match_parameter1=1 multi_match=1 END
        LPF ALTER_EFFECT INT_VAR check_headers = 0 match_opcode = 62 parameter1=1 parameter2=127 END
        LPF ADD_EQUIPPED_EFF STR_VAR effects=~op=98,p1=6,p2=3;op=142,p2=87~ END

END
