INCLUDE ~ZSTweaks/libs/zs_patch_spells.tpa~

DEFINE_PATCH_FUNCTION ADD_EQUIPPED_EFF
    INT_VAR
        p1 = 0
        p2 = 0
    STR_VAR
        effects = ~~
BEGIN
    LPF a7_auto_apply_spl_effect
        INT_VAR
            def_target = 1
            def_timing = 2
            def_parameter1 = p1
            def_parameter2 = p2
        STR_VAR
            function_name = ~ADD_ITEM_EQEFFECT~
            effect_codes = ~%effects%~
    END
END
