ACTION_IF !VARIABLE_IS_SET comp_moved BEGIN
    MOVE "%MOD_FOLDER%/libs/components/01_general_tweaks" ~%MOD_FOLDER%/libs/components~
    //DELETE ~%MOD_FOLDER%/libs/components/01_general_tweaks~

    MOVE "%MOD_FOLDER%/libs/components/02_gear_tweaks" ~%MOD_FOLDER%/libs/components~
    //DELETE ~%MOD_FOLDER%/libs/components/02_gear_tweaks~

    MOVE "%MOD_FOLDER%/libs/components/03_dagger_tweaks" ~%MOD_FOLDER%/libs/components~
    //DELETE ~%MOD_FOLDER%/libs/components/03_dagger_tweaks~

    MOVE "%MOD_FOLDER%/libs/components/04_two_handed_tweaks" ~%MOD_FOLDER%/libs/components~
   // DELETE ~%MOD_FOLDER%/libs/components/04_two_handed_tweaks~

    MOVE "%MOD_FOLDER%/libs/components/05_one_handed_swords_tweaks" ~%MOD_FOLDER%/libs/components~
    //DELETE ~%MOD_FOLDER%/libs/components/05_one_handed_swords_tweaks~

    MOVE "%MOD_FOLDER%/libs/components/06_axes_blunt_tweaks" ~%MOD_FOLDER%/libs/components~
    //DELETE ~%MOD_FOLDER%/libs/components/06_axes_blunt_tweaks~

    MOVE "%MOD_FOLDER%/libs/components/07_ranged_tweaks" ~%MOD_FOLDER%/libs/components~
    //DELETE ~%MOD_FOLDER%/libs/components/07_ranged_tweaks~

    MOVE "%MOD_FOLDER%/libs/components/08_npc_tweaks" ~%MOD_FOLDER%/libs/components~
    //DELETE ~%MOD_FOLDER%/libs/components/08_npc_tweaks~

    MOVE "%MOD_FOLDER%/libs/components/09_wizard_spells_tweaks" ~%MOD_FOLDER%/libs/components~
    //DELETE ~%MOD_FOLDER%/libs/components/09_wizard_spells_tweaks~

    MOVE "%MOD_FOLDER%/libs/components/10_cleric_spells_tweaks" ~%MOD_FOLDER%/libs/components~
    //DELETE ~%MOD_FOLDER%/libs/components/10_cleric_spells_tweaks~

    MOVE "%MOD_FOLDER%/libs/components/11_class_tweaks" ~%MOD_FOLDER%/libs/components~
    //DELETE ~%MOD_FOLDER%/libs/components/11_class_tweaks~

    MOVE "%MOD_FOLDER%/libs/components/12_creature_tweaks" ~%MOD_FOLDER%/libs/components~
    //DELETE ~%MOD_FOLDER%/libs/components/12_creature_tweaks~

    OUTER_SET comp_moved = 1
END

ACTION_IF !VARIABLE_IS_SET zst_config_file_copied BEGIN
    COPY ~%MOD_FOLDER%/zstweaks_prefs.txt~ ~override~
    OUTER_SET zst_config_file_copied = 1
END

OUTER_SET group_component = 0
INCLUDE ~%MOD_FOLDER%/libs/components/zs_comp_%COMPONENT_NUMBER%.tph~
