DEFINE_PATCH_FUNCTION change_stat_requirements
    INT_VAR
        str = "-1"
    BEGIN
        PATCH_IF str < "-1" BEGIN
            WRITE_SHORT 0x26 0 // STR
        END ELSE BEGIN
            WRITE_SHORT 0x26 str // STR
        END
        WRITE_BYTE 0x2c 0 // DEX
        WRITE_BYTE 0x2e 0 // WIS
        WRITE_BYTE 0x2a 0 // INT
        WRITE_BYTE 0x30 0 // CON
        WRITE_BYTE 0x32 0 // CHA
END
