ACTION_IF !(GAME_IS "iwdee") BEGIN
    COPY_EXISTING "DART05.itm" ~override~
        LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6390) END
        LPF ALTER_EFFECT INT_VAR check_globals=0 header_type=2 match_savingthrow=4 savebonus="-4" END
        LPF GET_DMG_TYPE STR_VAR type = ~poison~ RET poison = result END
        LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=12,dsize=2,dnum=1,p2=%poison%,t=2~ END
    BUT_ONLY
END
