DEFINE_ACTION_FUNCTION LOG_WARNING_FAIL
INT_VAR
STR_VAR
    message = ""
    log_level = "warn"
BEGIN
    ACTION_IF STRING_LENGTH message > 0 BEGIN
        
        OUTER_SET is_warn = "%log_level%" STR_EQ "warn"
        OUTER_SET is_fail =  "%log_level%" STR_EQ "fail"

        ACTION_IF is_warn OR is_fail BEGIN

            ACTION_IF FILE_EXISTS ~%MOD_FOLDER%/logs/no_errors_found.txt~ BEGIN

                COPY ~%MOD_FOLDER%/logs/no_errors_found.txt~ ~%MOD_FOLDER%/logs/errors_found.txt~
                APPEND_OUTER ~%MOD_FOLDER%/logs/errors_found.txt~ "----Start of Logs----"
                DELETE ~%MOD_FOLDER%/logs/no_errors_found.txt~
                
            END

            ACTION_IF FILE_EXISTS ~%MOD_FOLDER%/logs/errors_found.txt~ BEGIN
                COPY ~%MOD_FOLDER%/logs/errors_found.txt~ ~%MOD_FOLDER%/logs/errors_found.txt~
                APPEND_OUTER ~%MOD_FOLDER%/logs/errors_found.txt~ "%message%"                
            END
 
            ACTION_IF is_warn BEGIN         
                PRINT "%message%"
            END ELSE BEGIN
                FAIL "%message%"
            END

        END ELSE BEGIN
            FAIL "Logging function called with an invalid logging level: %log_level%. Valid levels are 'warn' and 'fail'"
        END

    END ELSE BEGIN
        FAIL "Logging function has an empty message as input"
    END
END

INCLUDE ~%MOD_FOLDER%/libs/preambles/fragments/zs_preinstall_check.tph~
INCLUDE ~%MOD_FOLDER%/libs/preambles/fragments/zs_vars.tph~
INCLUDE ~%MOD_FOLDER%/libs/preambles/fragments/zs_vars_eval.tph~
INCLUDE ~%MOD_FOLDER%/libs/preambles/fragments/zs_npc_array.tph~
INCLUDE ~%MOD_FOLDER%/libs/preambles/fragments/zs_ids_setup.tph~
INCLUDE ~%MOD_FOLDER%/libs/preambles/fragments/zs_constants.tph~
INCLUDE ~%MOD_FOLDER%/libs/functions/zs_tw_functions.tph~
INCLUDE ~%MOD_FOLDER%/libs/preambles/fragments/zs_prefixes.tph~
INCLUDE ~%MOD_FOLDER%/libs/preambles/fragments/zs_standardize_shields.tph~
INCLUDE ~%MOD_FOLDER%/libs/preambles/fragments/zs_splprot_include.tph~

ACTION_IF NOT ZS_MARKER_FILE_EXISTS BEGIN
    PRINT "[INFO]: Generating marker file zssetup.rp"
    SILENT
    COPY_EXISTING ~sw1h01.itm~ ~override/zssetup.rp~
    OUTER_SET ZS_MARKER_FILE_EXISTS = 1
    VERBOSE
END

INCLUDE ~%MOD_FOLDER%/libs/preambles/fragments/zs_component_include.tph~
