OUTER_SET group_component = 1

INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_120.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1120.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1121.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1150.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1160.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1350.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1352.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1360.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1370.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1400.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1430.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1440.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1450.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1530.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1532.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1533.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1534.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1535.tph"
INCLUDE "ZSTweaks/libs/components/01_general_tweaks/zs_comp_1537.tph"
INCLUDE ~ZSTweaks/libs/components/01_general_tweaks/zs_comp_1601.tph~
INCLUDE ~ZSTweaks/libs/components/01_general_tweaks/zs_comp_1650.tph~
