ACTION_IF GAME_IS "bg2ee eet" BEGIN
    COPY_EXISTING ~WAMACE.ITM~ ~override~
        LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6351) id_ref_name=RESOLVE_STR_REF(@6350) ench=3 END
        LPF ALTER_HEADER INT_VAR match_damage = 3 match_to_hit = 2 match_speed = 5 to_hit = 3 speed = 4 damage = 4 END
    BUT_ONLY

    COPY_EXISTING ~DAMACEA.EFF~ ~override~
        LPF ALTER_EFF_FILE INT_VAR special = 1024 END
END
