ACTION_IF NOT is_iwdee BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~bdhelm09.itm~ BEGIN

    COPY_EXISTING "bdhelm09.itm" ~override~
      LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6970) END
      LPF ALTER_EFFECT INT_VAR check_headers = 0 match_parameter1 = 3 match_parameter2 = 0 parameter1 = 5 END

  END ELSE BEGIN
    LAF LOG_TEXT INT_VAR predicate_stdout = (NOT group_component) STR_VAR log_level="abort" message = "Helm of the Dumathoin (bdhelm09) not found. -- Harmless unless you are playing BGEE with SoD or in BG2EE" END
  END

END
