ACTION_IF NOT is_iwdee BEGIN

  COPY_EXISTING ~sppr304.spl~ ~override~
    LPF ALTER_SPELL INT_VAR desc=RESOLVE_STR_REF(@5000) END
    LPF ALTER_EFFECT INT_VAR match_savingthrow=2**0+2**24 special=2**8 END

    PATCH_IF NOT has_eefixpack BEGIN

      LPF ~CD_LEVEL_SELECT-O-MATIC~ INT_VAR min_abil=1 step_dur=0 dur_special=1 level_cap=20 damage_rolls=1 min_lev_alt=5 damage_special=1 END

    END

  BUT_ONLY

END
