ACTION_IF (VARIABLE_IS_SET ~zs_comp_1675~) BEGIN
  FAIL ~Script already included: zs_comp_1675~
END ELSE BEGIN
  OUTER_SET ~zs_comp_1675~ = 1
END

ACTION_IF NOT is_iwdee BEGIN

  COPY_EXISTING ~clck03.itm~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@7450) END
    LPF DELETE_EFFECT INT_VAR match_opcode = 65 END
    LPF ADD_EQUIPPED_EFF INT_VAR p1=5 STR_VAR effects=~op=86;op=87;op=88;op=89;op=27;op=28;op=29;op=30;op=173~ END

END
