ACTION_IF is_bg2ee_or_eet BEGIN

  COPY ~%MOD_FOLDER%/items/girdle_fortitude~ ~override~
  COPY_EXISTING ~belt09.itm~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@8070) END
    LPF DELETE_EFFECT INT_VAR check_globals = 0 header_type = 3 END
    LPF ALTER_HEADER INT_VAR target=1 match_type=3 launcher=0 alt_dicenumber=0 overhand=0 backhand=0 thrust=0 STR_VAR icon="ibelt09" END
    LPF ADD_ON_HIT_EFF STR_VAR effects = ~t=3,op=146,res=zstwgfrt~ END
    LPF ADD_EQUIPPED_EFF STR_VAR effects = ~op=10,p1=18,p2=1;op=206,res=zstwgfrt~ END

END
