ACTION_IF is_bg2ee_or_eet BEGIN

  COPY_EXISTING ~ohdhswd.itm~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6190) END
    LPF ALTER_EFFECT INT_VAR check_globals=0 header_type=1 match_opcode=177 parameter1=alignmen_mask_evil END
    LPF ADD_EQUIPPED_EFF STR_VAR effects = ~op=344,p1=3,p2=8,spec=5~ END

  COPY_EXISTING "sw2h19a.eff" ~override~
    LPF ALTER_EFF_FILE INT_VAR special=1024 END

END
 