ACTION_IF is_bg2ee_or_eet BEGIN

  COPY ~%MOD_FOLDER%/items/aeger_hide~ ~override~
  COPY_EXISTING ~leat20.itm~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@8450) END
    LPF ADD_EQUIPPED_EFF INT_VAR p1=kit_barbarian p2=9 STR_VAR effects = ~op=177,res=zstwaega;op=177,res=zstwaegb;op=177,res=zstwaegc;op=177,res=zstwaegd;op=177,res=zstwaege;op=177,res=zstwaegf;op=177,res=zstwaegg;op=177,res=zstwaegh;op=177,res=zstwaegj;op=177,res=zstwaegk;op=177,res=zstwaegl~ END

END
