ACTION_IF (VARIABLE_IS_SET ~zs_comp_1701~) BEGIN
  FAIL ~Script already included: zs_comp_1701~
END ELSE BEGIN
  OUTER_SET ~zs_comp_1701~ = 1
END

ACTION_IF is_bg2ee_or_eet BEGIN

  COPY ~%MOD_FOLDER%/items/ilbratha~ ~override~
  COPY_EXISTING ~sw1h26.itm~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@55000) END
    LPF ADD_EQUIPPED_EFF STR_VAR effects = ~op=232,p2=7,res=zstwilb0~ END

END
