COPY_EXISTING ~clck03.itm~ ~override~
  LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@7450) END
  LPF DELETE_EFFECT INT_VAR match_opcode = 65 END
  LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 3 END

  PATCH_FOR_EACH type IN 1 4 8 BEGIN
    LPF CLONE_EFFECT INT_VAR match_opcode = 0 match_parameter2 = 2 parameter1 = 1 parameter2 = type END
  END
  
  LPF ADD_EQUIPPED_EFF INT_VAR p1=zst_1675_cloak_displacement_dr STR_VAR effects=~op=84;op=85;op=86;op=87;op=88;op=89;op=27;op=28;op=29;op=30;op=31;op=173~ END
