COPY_EXISTING ~SPWI518.SPL~ ~override~
    SET dur = 126
    LPF LAST_VALID_HEADER RET new_header = result END
    FOR ( level = 19; level <= 20; ++level ) BEGIN
        LPF ADD_SPELL_HEADER INT_VAR copy_header=new_header - 1 zs_min_level_for_copy = level insert_point=new_header+1 END
        LPF ALTER_EFFECT INT_VAR header_type=1 header=new_header+1 duration= dur + 6 END
        ++new_header
        dur += 6
    END
BUT_ONLY
