ACTION_IF is_bg2ee_or_eet BEGIN

    OUTER_SET general_tweaks_installed = MOD_IS_INSTALLED "ZSTweaks.tp2" "103"
    OUTER_SET finesse_component_installed = (MOD_IS_INSTALLED "ZSTweaks.tp2" "1450" OR (general_tweaks_installed AND zst_group_1450_finesse))
    OUTER_SET weapon_dice_installed = (MOD_IS_INSTALLED "ZSTweaks.tp2" "1150" OR (general_tweaks_installed AND zst_group_1150_weapon_dice))

    COPY ~%MOD_FOLDER%/items/rod_might~ ~override~
    COPY_EXISTING ~rods02.itm~ ~override~
                  ~rods02a.itm~ ~override~
        LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6040) id_name = RESOLVE_STR_REF(@6048) unusable0=0 END

    COPY_EXISTING ~rodmace.itm~ ~override~
        SET name = RESOLVE_STR_REF(@6041)
        SET desc = RESOLVE_STR_REF(@6044)
        LPF ALTER_ITEM INT_VAR id_desc=desc general_desc=desc general_name=name id_name=name ench=3 STR_VAR icon=~zstwrrm0~ desc_img=~zstwrrm1~ END
        LPF ALTER_HEADER INT_VAR match_type = 1 speed = 4 damage = 4 STR_VAR icon = ~zstwrrm1~ END
        LPF ALTER_EFFECT INT_VAR header_type=1 check_globals=0 match_opcode=24 opcode=40 savebonus=2 duration=12 END
        LPF ALTER_EFFECT INT_VAR match_opcode = 7 parameter1=44 END

        PATCH_IF has_eefixpack BEGIN

            LPF ALTER_EFFECT INT_VAR match_opcode=324 match_parameter2=110 match_parameter1=splstate_fp_panic_immunity parameter1=splstate_fp_slow_immunity END

        END

    DEFINE_PATCH_MACRO patch_file BEGIN
        SPRINT fp_compat_sleep ""
        PATCH_IF has_eefixpack BEGIN
            SPRINT fp_compat_sleep "op=318,p2=110,p1=%splstate_fp_sleep_immunity%,res=%DEST_RES%"
        END

        LPF ADD_SPL_TGTEFF INT_VAR rd=3 pwr=0 STR_VAR effects = ~%fp_compat_sleep%op=39,dur=6,p2=1~ END
    END
    LAF CREATE_TG_SPL STR_VAR filename = "zstrdsw0" END // sleep

    DEFINE_PATCH_MACRO patch_file BEGIN
        SPRINT fp_compat_stun ""
        PATCH_IF has_eefixpack BEGIN
            SPRINT fp_compat_stun "op=318,p2=110,p1=%splstate_fp_stun_immunity%,res=%DEST_RES%"
        END

        LPF ADD_SPL_TGTEFF INT_VAR rd=3 pwr=0 STR_VAR effects = ~%fp_compat_stun%op=45,dur=6;op=139,p1=1280~ END
    END
    LAF CREATE_TG_SPL STR_VAR filename = "zstrdsw1" END // stun

    COPY_EXISTING ~rodsword.itm~ ~override~
        SET name = RESOLVE_STR_REF(@6042)
        SET desc = RESOLVE_STR_REF(@6045)
        LPF ALTER_ITEM INT_VAR id_desc=desc general_desc=desc general_name=name id_name=name ench=3 STR_VAR appearance="fs" icon=~zstwrrm2~ desc_img=~zstwrrm3~ END
        LPF ALTER_HEADER INT_VAR match_type = 1 speed = 2 damage = 3 STR_VAR icon = ~zstwrrm2~ END
        LPF DELETE_EFFECT_EX STR_VAR match_opcode_ex = "(o_opcode=139 OR o_opcode=45 OR o_opcode=39 OR o_opcode=109)" END
        LPF ALTER_EFFECT INT_VAR check_headers=0 match_opcode = 7 parameter1=44 END
        LPF ADD_ON_HIT_EFF STR_VAR effects =~op=146,p2=1,res=zstrdsw0,stype=2,sbonus=2,pro1=49;op=146,p2=1,res=zstrdsw1,stype=2,sbonus=2,pro2=50,pro1=100;op=12,dsize=4,dnum=1,p2=%op12_fire%,spec=1024~ END

        PATCH_IF zst_1450_allow_lswords AND finesse_component_installed BEGIN
            SET ench = 3
            LPM PROBABILITY_BONUS
            LPF ALTER_EFFECT INT_VAR match_opcode=326 probability1=(bonus+base_ls_staff) STR_VAR match_resource="zstwl1" resource="zstwl3" END
        END

    COPY_EXISTING ~rodspear.itm~ ~override~
        SET name = RESOLVE_STR_REF(@6043)
        SET desc = RESOLVE_STR_REF(@6046)
        LPF ALTER_ITEM INT_VAR general_name=name id_name=name general_desc=desc id_desc=desc STR_VAR icon=~zstwrrm4~ desc_img=~zstwrrm5~ END
        LPF ALTER_HEADER INT_VAR match_type = 1 overhand = 25 thrust = 75 STR_VAR icon = ~zstwrrm4~ END
        LPF ALTER_EFFECT INT_VAR check_globals=0 match_opcode=12 savebonus=0 savingthrow=0 parameter1=2 special=1024 probability1=9 END
        LPF ALTER_EFFECT INT_VAR match_opcode = 7 parameter1=44 END
        LPF ADD_ON_HIT_EFF INT_VAR p2=104 STR_VAR effects = ~op=318,p2=55;op=318,p2=9;op=318,p1=%race_shambling_mound%;op=318,p1=%race_slime%~ END
        LPF ADD_ON_HIT_EFF INT_VAR p1=2 p2=op12_piercing tmg=3 stype=4 spec=1024 STR_VAR effects = ~op=12,tmg=0,p1=1,stype=0;op=12,p1=1,dur=1;op=12,dur=2;op=12,dur=3;op=12,dur=4;op=12,dur=5;op=12,p1=1,dur=6~ END

        PATCH_IF zst_1150_dice_spears AND weapon_dice_installed BEGIN
            SPRINT desc @6046
            SPRINT str @99999
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~\([%LNL%%MNL%%WNL%]+[ %TAB%]*%str%[ %TAB%]*:?[ %TAB%]*\)1[Dd]6~ ~\11d8~
            END
            SAY_EVALUATED 0x54 ~%desc%~
            SAY_EVALUATED 0x50 ~%desc%~
        END ELSE BEGIN
            LPF ALTER_ITEM INT_VAR id_desc=desc END
        END

END
