ACTION_IF (VARIABLE_IS_SET ~zs_comp_1651~) BEGIN
  FAIL ~Script already included: zs_comp_1651~
END ELSE BEGIN
  OUTER_SET ~zs_comp_1651~ = 1
END

ACTION_IF is_bg2ee_or_eet BEGIN

  COPY_EXISTING "LEAT23.ITM" ~override~
    LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6890) END

  COPY_EXISTING "LEAT23A.SPL" ~override~
    LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter2 = op12_piercing END

END
