ACTION_IF NOT is_iwdee BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~bdring10.itm~ BEGIN
    COPY ~%MOD_FOLDER%/items/ring_purity~ ~override~
    COPY_EXISTING ~bdring10.itm~ ~override~
      LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@7820) END
      LPF CLONE_EFFECT INT_VAR match_opcode=219 opcode = 178 special = 1 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 178 opcode = 179 END
      LPF ADD_EQUIPPED_EFF INT_VAR p1=alignmen_mask_good p2=8 STR_VAR effects = ~op=177,res=zstwpur0;op=177,res=zstwpur1~ END

  END ELSE BEGIN
    LAF LOG_WARNING_FAIL INT_VAR force_warn=1 predicate_stdout = (NOT group_component) STR_VAR message = "[WARN]: No Ring of Purity found in the game -- Harmless if not EET or not SoD" END
  END

END
