

ACTION_IF is_bg2ee_or_eet BEGIN

  COPY ~%MOD_FOLDER%/items/thayan_circlet~ ~override~
  COPY_EXISTING "ohnhelm1.itm" ~override~
    LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6460) END
    LPF ALTER_EFFECT INT_VAR check_headers = 0 match_opcode = 281 parameter1 = 25 END
    SET description_note = RESOLVE_STR_REF(@6461)
    LPF ADD_EQUIPPED_EFF STR_VAR effects=~op=272,p1=6,p2=3,res=ZSTWTHY0;op=319,pwr=1,p1=%kit_wild_mage%,p2=9,spec=%description_note%~ END

END
