DEFINE_PATCH_MACRO patch_file BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode=318 parameter1=0 target=1 parameter2=115 parameter1=class_fighter_all  STR_VAR resource="%DEST_RES%" END
    LPF ADD_SPELL_EFFECT INT_VAR opcode=318 parameter1=0 target=1 parameter2=115 parameter1=class_ranger_all  STR_VAR resource="%DEST_RES%" END
    LPF ADD_SPELL_EFFECT INT_VAR opcode=321 parameter1=0 target=1 STR_VAR resource="%DEST_RES%" END
    LPF ADD_SPELL_EFFECT INT_VAR opcode=1 parameter1=1 target=1 resist_dispel=1 duration=18 END
    LPF ~CD_EXTEND-O-MATIC~ INT_VAR dur_special=1 step_dur=6 level_cap=20 END
END
LAF CREATE_SELF_SPL STR_VAR filename="zstlath0" END // APR for non-fighter clerics bonus

COPY_EXISTING ~spcl741.spl~ ~override~
    LPF ALTER_SPELL INT_VAR desc = RESOLVE_STR_REF(@9020) END
    LPF ALTER_EFFECT_EX STR_VAR match_duration_ex="(o_duration >= 6)" duration_ex="(THIS + 12)" END
    LPF ALTER_EFFECT INT_VAR match_opcode=1 parameter1=6 END
    LPF CLONE_EFFECT INT_VAR match_opcode=1 opcode=146 duration=0 timing=0 parameter2=1 parameter1=0 STR_VAR resource="zstlath0" END