ACTION_IF (VARIABLE_IS_SET ~zs_comp_10012~) BEGIN
  FAIL ~Script already included: zs_comp_10012~
END ELSE BEGIN
  OUTER_SET ~zs_comp_10012~ = 1
END

OUTER_SET group_component = 1

OUTER_SPRINT config_path ~%MOD_FOLDER%/configurations/zstweaks_endofinstallorder_group_install.txt~
INCLUDE ~%config_path%~
COPY ~%config_path%~ ~override~

ACTION_IF zst_group_1531_selective_spells_mr BEGIN
  WITH_SCOPE BEGIN INCLUDE ~%MOD_FOLDER%/libs/components/zs_comp_1531.tph~ END
END
