COPY ~%MOD_FOLDER%/items/whispers_silence~ ~override~
COPY_EXISTING ~clck06.itm~ ~override~
              ~thclck01.itm~ ~override~
  LPF ADD_EQUIPPED_EFF STR_VAR effects=~op=59,p1=15;op=206,res=spwi322;op=206,res=spwi515;op=272,p1=1,p2=3,res=zstwsil0~ END
IF_EXISTS

COPY_EXISTING ~clck06.itm~ ~override~  
  LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@7440) END

COPY_EXISTING ~thclck01.itm~ ~override~  
  LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@7442) END
  LPF CLONE_EFFECT INT_VAR match_opcode = 20 opcode = 318 parameter2 = 110 parameter1 = splstate_cannot_turn_invisible STR_VAR resource = "%SOURCE_RES%" insert = "first" END
IF_EXISTS
