ACTION_IF (VARIABLE_IS_SET ~zs_comp_497~) BEGIN
  FAIL ~Script already included: zs_comp_497~
END ELSE BEGIN
  OUTER_SET ~zs_comp_497~ = 1
END

ACTION_IF spell_produce_fire > 0 BEGIN

  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = "CLERIC_PRODUCE_FIRE" RET spell_res END
  COPY_EXISTING ~%spell_res%.SPL~ ~override~
    LPF ALTER_SPELL INT_VAR desc = RESOLVE_STR_REF(@8606) END
    LPF ALTER_EFFECT INT_VAR match_opcode = 206 duration=2 STR_VAR match_resource = "%SOURCE_RES%" END

END
