OUTER_SET new_description =RESOLVE_STR_REF(@7360)
COPY_EXISTING ~spwi913.spl~ ~override~
  LPF DELETE_EFFECT INT_VAR check_headers = 0 match_opcode = 101 match_parameter2 = 55 END
  LPF ALTER_SPELL INT_VAR desc=new_description END
  LPF ADD_SPL_TGTEFF INT_VAR pwr=9 rd=3 STR_VAR effects=~op=12,p1=3,tmg=1,dnum=3,dsize=6,p2=0;op=80,dur=12;op=142,p2=112,dur=12~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter2 = op12_magic END
  LPF ALTER_EFFECT INT_VAR check_globals = 0 resist_dispel = 3 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 55 savingthrow = 0 dicenumber = 8 END
  
COPY_EXISTING ~scrl9v.itm~ ~override~
  LPF ALTER_ITEM INT_VAR id_desc=new_description END
IF_EXISTS

ACTION_IF zst_170_wail_wish_bonus BEGIN
  PRINT "[INFO]: Making sure the Limited Wish version of Wail of the Banshee is extra nasty..."
  COPY_EXISTING ~spwi913.spl~ "override/zstwswl.spl"
    LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = zst_170_wail_save_bonus END
    WRITE_BYTE 0x25 0
  COMPILE ~%MOD_FOLDER%/dlg/zs_wish_wail_banshee.d~

  ACTION_TIME "Horrendous WoB patching" BEGIN
    COPY_EXISTING_REGEXP ".+\.\(spl\|itm\|cre\)" ~override~
      LPF CLONE_EFFECT INT_VAR silent=1 match_opcode = 204 match_parameter2 = 7 opcode = 206 STR_VAR resource=~zstwswl~ END
      LPF CLONE_EFFECT INT_VAR silent=1 match_opcode = 206 STR_VAR resource = ~zstwswl~ END
  END

END



