OUTER_SET new_description        = RESOLVE_STR_REF(@5250)
OUTER_SET new_description_priest = RESOLVE_STR_REF(@5251)

OUTER_SET golem = 27
OUTER_SET notallies = 50
OUTER_SET fade_speed = (25 << 16)

ACTION_IF is_iwdee BEGIN
    OUTER_SET two_levels_drained = 35497
    OUTER_SET four_levels_drained = 35472
END ELSE ACTION_IF is_bgee BEGIN
    OUTER_SET two_levels_drained = 25803
    OUTER_SET four_levels_drained = 25805
END ELSE ACTION_IF is_bg2ee_or_eet BEGIN
    OUTER_SET two_levels_drained = 40968
    OUTER_SET four_levels_drained = 40979
END

OUTER_SPRINT the_effects ~op=324,p1=%race_salamander%;op=324,p1=%race_darkplanetar%;op=324,p1=%race_planetar%;op=324,p1=%race_antisolar%;op=324,p1=%race_solar%;op=324,p1=%race_rakshasa%;op=324,p1=%race_genie%;op=324,p1=%race_elemental%;op=324,p1=%race_mephit%;op=324,p1=%race_demonic%;op=324,p2=%golem%;op=326,p2=1,res=zstegdr0;op=318,p2=1;op=216,p1=4,p2=0,tmg=1;op=139,p1=%four_levels_drained%,p2=0;op=216,p1=2,p2=0,tmg=1;op=139,p2=0,p1=%two_levels_drained%;op=174,p2=0,tmg=1,res=eff_m07;op=141,tmg=1,p2=2;op=61,tmg=1,p1=2019179520,p2=%fade_speed%;op=146,p2=1,res=zstegdr5;op=326,p2=%notallies%,res=zstegdr1;op=326,p2=%notallies%,res=zstegdr7~


COPY ~%MOD_FOLDER%/spells/arcane/energy_drain~ ~override~

COPY_EXISTING ~zstegdrs.cre~ ~override~ // devil shade
    SAY 0x08 @5651
    SAY 0x0c @5651

COPY_EXISTING ~zstegdr0.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR match_opcode=139 parameter1=RESOLVE_STR_REF(@5652) END

ACTION_IF is_iwdee BEGIN

    COPY_EXISTING ~zswraith.itm~ ~override/wraith1.itm~
    COPY_EXISTING ~sppr739.spl~ ~override~
        LPF ALTER_SPELL INT_VAR desc=new_description_priest END
        LPF DELETE_EFFECT INT_VAR check_globals = 0 END
        LPF ADD_SPL_TGTEFF INT_VAR tmg=0 rd=0 pwr=9 p2=104 STR_VAR res="%SOURCE_RES%" effects = ~%the_effects%~ END

END ELSE ACTION_IF has_iwd_spells_divine BEGIN

   ACTION_IF spell_cleric_energy_drain > 0 BEGIN
        LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = "CLERIC_ENERGY_DRAIN" RET spell_res END
        COPY_EXISTING ~%spell_res%.spl~ ~override~
            LPF ALTER_SPELL INT_VAR desc = new_description_priest END
            LPF DELETE_EFFECT INT_VAR check_globals = 0 END
            LPF ADD_SPL_TGTEFF INT_VAR tmg=0 rd=0 pwr=9 p2=104 STR_VAR res="%SOURCE_RES%" effects = ~%the_effects%~ END
    END

END

COPY_EXISTING ~spwi914.spl~  ~override~
              ~spwish19.spl~ ~override~
    LPF ALTER_SPELL INT_VAR desc=new_description END
    LPF DELETE_EFFECT INT_VAR check_globals = 0 END
    LPF ADD_SPL_TGTEFF INT_VAR tmg=0 rd=0 pwr=9 p2=104 STR_VAR res="%SOURCE_RES%" effects = ~%the_effects%~ END

IF_EXISTS

COPY_EXISTING ~scrl9w.itm~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc=new_description END
IF_EXISTS
