ACTION_IF is_bg2ee_or_eet BEGIN

  DEFINE_PATCH_MACRO patch_file BEGIN LPF ALTER_EFF_FILE INT_VAR opcode = 89 parameter1 = 10 END END
  LAF CREATE_EQ_EFF STR_VAR filename = "zstworc0" END // missile resist

  DEFINE_PATCH_MACRO patch_file BEGIN LPF ALTER_EFF_FILE INT_VAR opcode = 18 parameter1 = 10 parameter2 = 3 END END
  LAF CREATE_EQ_EFF STR_VAR filename = "zstworc1" END // max hp

  DEFINE_PATCH_MACRO patch_file BEGIN LPF ALTER_EFF_FILE INT_VAR opcode = 285 parameter1 = 1 END END
  LAF CREATE_EQ_EFF STR_VAR filename = "zstworc2" END // melee weapon damage

  COPY_EXISTING ~leat16.itm~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@8420) END
    LPF DELETE_EFFECT INT_VAR match_opcode = 6 END
    LPF ADD_EQUIPPED_EFF INT_VAR p1=race_halforc p2=4 STR_VAR effects = ~op=6,p1=-2;op=177,res=zstworc0;op=177,res=zstworc1;op=177,res=zstworc2~ END

END
