ACTION_IF is_bg2ee_or_eet BEGIN

    COPY ~%MOD_FOLDER%/items/vorpal_weapons~ ~override~
    COPY_EXISTING ~zstwvrpa.spl~ ~override~
        LPF ALTER_EFFECT INT_VAR match_opcode = 318 parameter2 = ~%zs_has_stoneskins%~ END

        PATCH_IF zst_1541_vorpal_no_chunking BEGIN
            LPF ALTER_EFFECT INT_VAR match_opcode = 13 parameter2 = (2**2) END
        END

        PATCH_IF zst_1541_vorpal_no_golems BEGIN
            LPF CLONE_EFFECT INT_VAR match_opcode = 318 match_parameter2 = ~%zs_has_stoneskins%~ parameter2=27 STR_VAR insert="first" END
        END

        PATCH_IF zst_1541_vorpal_no_slimes BEGIN
            LPF CLONE_EFFECT INT_VAR match_opcode = 318 match_parameter2 = ~%zs_has_stoneskins%~ parameter2=104 parameter1=race_slime STR_VAR insert="first" END
        END

        PATCH_IF zst_1541_vorpal_no_elementals BEGIN
            LPF CLONE_EFFECT INT_VAR match_opcode = 318 match_parameter2 = ~%zs_has_stoneskins%~ parameter2=9 STR_VAR insert="first" END
        END

        PATCH_IF zst_1541_vorpal_no_spectral_races BEGIN

            LPF CLONE_EFFECT INT_VAR match_opcode = 318 match_parameter2 = ~%zs_has_stoneskins%~ parameter2=104 parameter1=race_specter STR_VAR insert="first" END
            LPF CLONE_EFFECT INT_VAR match_opcode = 318 match_parameter2 = ~%zs_has_stoneskins%~ parameter2=104 parameter1=race_spectral_undead STR_VAR insert="first" END
            LPF CLONE_EFFECT INT_VAR match_opcode = 318 match_parameter2 = ~%zs_has_stoneskins%~ parameter2=104 parameter1=race_wraith STR_VAR insert="first" END
            LPF CLONE_EFFECT INT_VAR match_opcode = 318 match_parameter2 = ~%zs_has_stoneskins%~ parameter2=104 parameter1=race_shadow STR_VAR insert="first" END
            LPF CLONE_EFFECT INT_VAR match_opcode = 318 match_parameter2 = ~%zs_has_stoneskins%~ parameter2=104 parameter1=race_mist STR_VAR insert="first" END
            LPF CLONE_EFFECT INT_VAR match_opcode = 318 match_parameter2 = ~%zs_has_stoneskins%~ parameter2=105 parameter1=class_spectral_troll STR_VAR insert="first" END

        END

        PATCH_IF has_eefixpack BEGIN
            LPF CLONE_EFFECT INT_VAR match_opcode = 318 match_parameter2 = ~%zs_has_stoneskins%~ parameter2=110 parameter1=splstate_fp_death_immunity STR_VAR insert="first" END
        END

    OUTER_SET two_handed_comp_installed = MOD_IS_INSTALLED ~ZSTweaks.tp2~ ~1199~
    OUTER_SET creature_comp_installed = MOD_IS_INSTALLED ~ZSTweaks.tp2~ ~3000~

    DEFINE_PATCH_MACRO patch_pnp_outsiders BEGIN
        LPF ADD_ON_HIT_EFF INT_VAR ip=0 p2=104 dur=1 pro1=out_pro1 pro2=out_pro2 STR_VAR res = "zstwvrpa" effects = ~op=318,p2=27;op=318,p1=%race_slime%;op=318,p2=9;op=318,p1=%race_mist%;op=318,p1=%race_wraith%;op=318,p1=%race_shadow%;op=318,p1=%race_spectral_undead%;op=318,p1=%race_specter%;op=318,p1=%class_spectral_troll%,p2=105;op=318,p1=%race_skeleton%~ END

        LPF ALTER_EFFECT INT_VAR silent=1 match_opcode = 146 probability1 = out_pro1 probability2 = out_pro2 STR_VAR resource=~zstwvrpa~ match_resource="ca#vorpl" END
        LPF ALTER_EFFECT INT_VAR silent=1 match_opcode = 146 probability1 = out_pro1 probability2 = out_pro2 STR_VAR resource=~zstwvrpa~ match_resource="rr#vorpl" END
        LPF ALTER_EFFECT INT_VAR check_globals = 0 match_probability1 = out_pro1 match_probability2 = out_pro2 savingthrow = 4 savebonus = "-4" END
    END

    COPY_EXISTING ~ca#planw.itm~ ~override~
        SET out_pro1 = 100
        SET out_pro2 = 90
        LPM patch_pnp_outsiders
    IF_EXISTS

    COPY_EXISTING ~rr#dbalr.itm~ ~override~
        SET out_pro1 = 14
        SET out_pro2 = 0
        LPM patch_pnp_outsiders
    IF_EXISTS

    COPY_EXISTING ~balor.itm~ ~override~
        LPF DELETE_EFFECT INT_VAR check_globals = 0 END
        SPRINT effect_str ~op=326,pro1=14,res=zstwvrpa~

        PATCH_IF MOD_IS_INSTALLED ~ZSTweaks.tp2~ ~3050~ OR (zst_group_3050_balors_tweak AND creature_comp_installed) BEGIN
            SPRINT effect_str "%effect_str%,stype=4,sbonus=%zst_3050_balor_vorpal_penalty%"
        END

        LPF ADD_ON_HIT_EFF STR_VAR effects = ~%effect_str%~ END

    ACTION_IF zst_3030_planetars AND
              NOT (MOD_IS_INSTALLED ~ZSTweaks.tp2~ ~3030~ OR
              (creature_comp_installed AND zst_group_3030_celestials_tweak))
    BEGIN

        COPY_EXISTING ~planetar.itm~ ~override~
            LPF DELETE_EFFECT INT_VAR match_opcode = 13 END
            LPF DELETE_EFFECT INT_VAR match_opcode = 141 match_parameter2 = 39 END
            LPF DELETE_EFFECT INT_VAR match_opcode = 61 END
            LPF DELETE_EFFECT INT_VAR match_opcode = 139 END
            LPF ALTER_EFFECT_EX INT_VAR probability1 = 24 STR_VAR match_probability1_ex = ~(o_probability1 < 100)~ END
            LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=326,pro1=24,res=zstwvrpa,stype=4,sbonus=-2~ END

    END

    COPY_EXISTING ~gith.itm~ ~override~
        LPF DELETE_EFFECT INT_VAR check_globals = 0 END
        LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=326,pro1=24,res=zstwvrpa,stype=4~ END

    COPY_EXISTING ~sw2h15.itm~ ~override~
        PATCH_IF NOT MOD_IS_INSTALLED ~ZSTweaks.tp2~ ~1300~ AND
                 NOT (two_handed_comp_installed AND zst_group_1300_silver_sword)
        BEGIN
            LPF DELETE_EFFECT INT_VAR check_globals = 0 END
        END ELSE BEGIN
            LPF DELETE_EFFECT INT_VAR check_globals = 0 match_probability1 = 24 END
        END
        LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=326,pro1=24,res=zstwvrpa,stype=4,sbonus=-2~ END

    COPY_EXISTING ~ax1h15.itm~ ~override~
        LPF DELETE_EFFECT INT_VAR check_globals = 0 END
        LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=326,pro1=9,res=zstwvrpa,stype=4,sbonus=-4~ END

    COPY_EXISTING ~halb11.itm~ ~override~
        PATCH_IF MOD_IS_INSTALLED ~ZSTweaks.tp2~ ~1606~ OR
                (two_handed_comp_installed AND zst_group_1606_ravager)
        BEGIN

            LPF DELETE_EFFECT INT_VAR match_probability1 = 9 END
            LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=326,pro1=9,res=zstwvrpa,stype=4,sbonus=-4,ip=0~ END

        END ELSE BEGIN

            LPF DELETE_EFFECT INT_VAR match_opcode = 13 END
            LPF DELETE_EFFECT INT_VAR match_opcode = 141 match_parameter2 = 39 END
            LPF DELETE_EFFECT INT_VAR match_opcode = 139 END
            LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=326,pro1=9,res=zstwvrpa,ip=0~ END

        END

        COPY_EXISTING ~finsol02.itm~ ~override~
            LPF DELETE_EFFECT INT_VAR check_globals = 0 END
            LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=326,pro1=24,res=zstwvrpa,stype=4,sbonus=-2~ END

        PRINT "[INFO]: Patching items and spells with immunity to the Vorpal effect..."

        OUTER_SET opcode = 101
        OUTER_SET parameter2 = 13
        COPY_EXISTING_REGEXP ~^.+\.\(itm\|spl\)$~ ~override~
            SET present = 0
            READ_ASCII 0x0 sig (4)
            PATCH_MATCH "%sig%" WITH
            "SPL "
            BEGIN 
                PATCH_IF "%SOURCE_EXT%" STR_EQ "SPL" BEGIN
                    LPM SPELL_OPCODE_PRESENT 
                END
            END

            "ITM "
            BEGIN 
                PATCH_IF "%SOURCE_EXT%" STR_EQ "ITM" BEGIN
                    LPM ITM_OPCODE_PRESENT 
                END
            END

            DEFAULT
                PATCH_IF zs_debug BEGIN
                    PATCH_WARN "[DEBUG][WARN]: Found invalid file: %SOURCE_RES%"
                END
            END

            PATCH_IF present BEGIN
                LPF CLONE_EFFECT INT_VAR match_opcode=101 match_parameter2=13 opcode=206 parameter2=0 STR_VAR resource="zstwvrpa" END
            END

        BUT_ONLY

END
