<<<<<<<<.../zstweaks/summoned_demons_givexp.baf
IF
  Killed([ANYONE])
THEN
    RESPONSE #100
    AddXPWorth(LastKilled)
    Continue()
END
>>>>>>>>
APPEND ~object.ids~ ~94 LastKilled~ UNLESS ~^94[ %TAB%]+LastKilled$~

EXTEND_TOP "demnabsu.bcs" ".../zstweaks/summoned_demons_givexp.baf"
EXTEND_TOP "demglasu.bcs" ".../zstweaks/summoned_demons_givexp.baf"
EXTEND_TOP "dempitsu.bcs" ".../zstweaks/summoned_demons_givexp.baf"
