ACTION_IF NOT is_iwdee BEGIN

  COPY_EXISTING ~shartd.cre~  ~override~
                ~sharte.cre~  ~override~
                ~sharte4.cre~ ~override~
                ~sharte6.cre~ ~override~
                ~7xcre1.cre~  ~override~
                ~l#shte3.cre~ ~override~
                ~l#shte2.cre~ ~override~
                ~l#shte1.cre~ ~override~
                ~l#sht25.cre~ ~override~
                ~l#sht.cre~   ~override~
    LPF ADD_CRE_EFFECT INT_VAR opcode = 179 timing = 9 parameter2 = 7 parameter1 = 1 special = 1 END
    LPF ADD_CRE_EFFECT INT_VAR opcode = 178 timing = 9 parameter2 = 7 parameter1 = 1 special = 1 END
    LPF ADD_CRE_EFFECT INT_VAR opcode = 219 timing = 9 parameter2 = 7 parameter1 = 1 END
  IF_EXISTS

END
