ACTION_IF is_bg2ee_or_eet BEGIN

  COPY ~%MOD_FOLDER%/templates/eff/equipped.eff~ ~override/zstwthm1.eff~ // +1 thac0
    LPF ALTER_EFF_FILE INT_VAR opcode = 278 parameter1 = 1 END

  COPY ~%MOD_FOLDER%/templates/eff/equipped.eff~ ~override/zstwthm2.eff~ // +1 damage
    LPF ALTER_EFF_FILE INT_VAR opcode = 73 parameter1 = 1 END

  COPY ~%MOD_FOLDER%/templates/eff/equipped.eff~ ~override/zstwthm3.eff~ // +1 crit
    LPF ALTER_EFF_FILE INT_VAR opcode = 301 parameter1 = 1 END

  COPY_EXISTING ~wa2ring.itm~ ~override~
    LPF ALTER_ITEM INT_VAR unusable0=1075116480 id_desc=RESOLVE_STR_REF(@6340) END
    LPF ADD_EQUIPPED_EFF INT_VAR p1=class_thief p2=5 STR_VAR effects=~op=177,res=zstwthm1;op=177,res=zstwthm2;op=177,res=zstwthm3;op=177,p2=9,p1=%kit_stalker%,res=zstwthm3~ END

END
