DEFINE_PATCH_FUNCTION add_immunity_to 
INT_VAR
    p1 = "-1"
    p2 = "-1"
    race = "-1"
    min_level = 0
    op = 318
    dur = 0
STR_VAR
    i = "above"
    res = "%SOURCE_RES%"
BEGIN
    LPF CLONE_EFFECT 
        INT_VAR 
            match_opcode = 12
            multi_match = 1
            opcode = 318
            duration=dur
            parameter2 = (p2 > "-1" ? p2 : 104)
            parameter1 = (p1 > "-1" ? p1 : race)
            dicesize = min_level
        STR_VAR 
            insert=i 
            resource=res
    END
END

COPY ~%MOD_FOLDER%/templates/spl/1h_lactor.spl~ ~override/zstrpim0.spl~
    LPF ADD_SPELL_EFFECT
        INT_VAR
            opcode = 206
            target = 2
            duration = 1
        STR_VAR
            resource = "spcl411"
    END

COPY ~%MOD_FOLDER%/templates/spl/1h_lactor.spl~ ~override/zstrpim1.spl~
    SET bypass_mirr = 2 ** 24
    LPF ADD_SPL_TGTEFF STR_VAR effects = ~op=318,res=zstrpim1,p2=55;op=318,res=zstrpim1,p2=77;op=55,p2=2,stype=4,sbonus=4;op=12,p2=%op12_poison%,p1=20,stype=%bypass_mirr%~ END

COPY_EXISTING ~spcl411.spl~ ~override~
    PATCH_IF zst_3180_immunity_by_type BEGIN
        LPF add_immunity_to INT_VAR race = race_lich END
        LPF add_immunity_to INT_VAR race = race_demilich END
        LPF add_immunity_to INT_VAR race = race_dragon END
    END

    PATCH_IF zst_3180_immunity_by_power BEGIN
        LPF add_immunity_to INT_VAR p2=0 p1=0 min_level = 25 END
    END

    PATCH_IF zst_3180_only_once_per_sec BEGIN
        LPF DELETE_EFFECT INT_VAR match_opcode= 318 STR_VAR match_resource = "%SOURCE_RES%" END
        LPF DELETE_EFFECT INT_VAR match_opcode= 55 END
        LPF DELETE_EFFECT INT_VAR match_opcode = 12 match_parameter2 = op12_poison END
        LPF ADD_SPL_TGTEFF STR_VAR effects = ~op=146,res=zstrpim1,p2=1;op=146,res=zstrpim0,p2=1~ END
    END