ACTION_IF (VARIABLE_IS_SET ~zs_comp_1585~) BEGIN
  FAIL ~Script already included: zs_comp_1585~
END ELSE BEGIN
  OUTER_SET ~zs_comp_1585~ = 1
END

ACTION_IF is_bg2ee_or_eet BEGIN

    COPY_EXISTING "SW1H27.itm" ~override~
        LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@7540) END
        LPF ALTER_HEADER INT_VAR match_type = 1 speed = 0 END
        LPF ALTER_EFFECT INT_VAR header_type = 3 match_duration = 12 duration = 60 END
        
END
