ACTION_IF is_bg2ee_or_eet BEGIN

    COPY_EXISTING ~plat16.itm~ ~override~
        LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@60200) END
        LPF ADD_EQUIPPED_EFF STR_VAR p2=8 p1=alignmen_mask_evil effects = ~op=178;op=179;op=6,p1=2,p2=0;op=296,res=cdhorror;op=240,p2=36;op=169,p2=36;op=267,p1=17427;op=267,p1=14007;op=106,p2=1,p1=1;op=161;op=23;op=101,p2=24;op=142,p2=37;op=101,p2=23;op=101,p2=106;op=232,p2=1,res=zsthart0~ END

END