ACTION_IF is_bg2ee_or_eet BEGIN

    DEFINE_PATCH_MACRO patch_file BEGIN
        LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 tmg=1
        STR_VAR effects = ~op=318,p2=55,res=%DEST_RES%,tmg=0;op=78,p1=3,p2=4;op=78,p1=3,p2=5;op=78,p1=3,p2=6;op=142,p2=7;op=215,p2=1,tmg=0,dur=2,res=magres4;op=206,res=%DEST_RES%~ END
    END
    LAF CREATE_TG_SPL STR_VAR filename = "zstpitf1" END // disease component

    OUTER_SET opcode = 79 
    COPY_EXISTING_REGEXP ~^.+\.\(itm\|spl\)$~ ~override~
        READ_ASCII 0x0 sig (4)
        PATCH_MATCH "%sig%" WITH
        "SPL "
        BEGIN 
          PATCH_IF "%SOURCE_EXT%" STR_EQ "SPL" BEGIN
            LPM SPELL_OPCODE_PRESENT 
          END
        END

        "ITM "
        BEGIN 
            PATCH_IF "%SOURCE_EXT%" STR_EQ "ITM" BEGIN
              LPM ITM_OPCODE_PRESENT 
            END 
        END DEFAULT END

        PATCH_IF present BEGIN
            LPF CLONE_EFFECT INT_VAR match_opcode = 79 opcode = 321 STR_VAR resource = ~zstpitf1~ END
        END

    BUT_ONLY

    OUTER_SET poison_one = RESOLVE_STR_REF(@80600)
    OUTER_SET poison_two = RESOLVE_STR_REF(@80601)
    OUTER_SET poison_three = RESOLVE_STR_REF(@80602)
    
    DEFINE_PATCH_MACRO patch_file BEGIN
        LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 STR_VAR effects = ~op=318,p2=55,res=%DEST_RES%;op=318,p2=77,res=%DEST_RES%;op=12,dsize=6,dnum=2,p2=%op12_poison%;op=146,p2=1,pro1=8,res=zstpitf5;op=146,p2=1,pro2=9,pro1=16,res=zstpitf6;op=146,p2=1,pro2=17,pro1=24,res=zstpitf7~ END
    END
    LAF CREATE_TG_SPL STR_VAR filename = "zstpitf2" END // poison component

    DEFINE_PATCH_MACRO patch_file BEGIN
       LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 STR_VAR effects = ~op=139,p1=%poison_one%;op=142,dur=6,p2=51;op=142,dur=6,p2=6~ END
       LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 tmg=3 dur=6 STR_VAR effects = ~op=12,p2=%op12_poison%,dsize=6,dnum=1;op=146,p2=1,res=zstpitf3~ END
    END
    LAF CREATE_TG_SPL STR_VAR filename = "zstpitf5" END // poison 1 round

    DEFINE_PATCH_MACRO patch_file BEGIN
       LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 STR_VAR effects = ~op=139,p1=%poison_two%;op=142,dur=12,p2=51;op=142,dur=12,p2=6~ END
       LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 tmg=3 dur=6 STR_VAR effects = ~op=12,p2=%op12_poison%,dsize=6,dnum=1~ END
       LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 tmg=3 dur=12 STR_VAR effects=~op=12,p2=%op12_poison%,dsize=6,dnum=1;op=146,p2=1,res=zstpitf3~ END
    END
    LAF CREATE_TG_SPL STR_VAR filename = "zstpitf6" END // poison 2 rounds

    DEFINE_PATCH_MACRO patch_file BEGIN
       LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 STR_VAR effects = ~op=139,p1=%poison_three%;op=142,dur=18,p2=51;op=142,dur=18,p2=6~ END
       LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 tmg=3 dur=6 STR_VAR effects = ~op=12,p2=%op12_poison%,dsize=6,dnum=1~ END
       LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 tmg=3 dur=12 STR_VAR effects=~op=12,p2=%op12_poison%,dsize=6,dnum=1~ END
       LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 tmg=3 dur=18 STR_VAR effects = ~op=12,p2=%op12_poison%,dsize=6,dnum=1;op=146,p2=1,res=zstpitf3~ END
    END
    LAF CREATE_TG_SPL STR_VAR filename = "zstpitf7" END // poison 3 rounds

    OUTER_SET opcode = 11 
    COPY_EXISTING_REGEXP ~^.+\.\(itm\|spl\)$~ ~override~
        READ_ASCII 0x0 sig (4)
        PATCH_MATCH "%sig%" WITH
        "SPL "
        BEGIN 
          PATCH_IF "%SOURCE_EXT%" STR_EQ "SPL" BEGIN
            LPM SPELL_OPCODE_PRESENT 
          END
        END

        "ITM "
        BEGIN 
            PATCH_IF "%SOURCE_EXT%" STR_EQ "ITM" BEGIN
              LPM ITM_OPCODE_PRESENT 
            END 
        END DEFAULT END

        PATCH_IF present BEGIN
            LPF CLONE_EFFECT INT_VAR match_opcode = 11 opcode = 321 STR_VAR resource = ~zstpitf2~ END
        END

    BUT_ONLY

    DEFINE_PATCH_MACRO patch_file BEGIN
        SPRINT fp_death_immune ""
        PATCH_IF has_eefixpack BEGIN
            SPRINT fp_death_immune ~op=318,p2=110,p1=%splstate_fp_death_immunity%,res=%DEST_RES%;~
        END
        LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 stype=4 STR_VAR effects = ~%fp_death_immune%op=55,p2=2~ END
    END
    LAF CREATE_TG_SPL STR_VAR filename = "zstpitf3" END // slay component

    DEFINE_PATCH_MACRO patch_file BEGIN
        LPF ADD_SPL_TGTEFF INT_VAR pwr=0 rd=0 p2=1 STR_VAR effects=~op=146,res=zstpitf1;op=146,res=zstpitf2;op=206,dur=3,res=%DEST_RES%~ END
    END
    LAF CREATE_TG_SPL STR_VAR filename = "zstpitf4" END // bite effects

    COPY_EXISTING ~p3-12m4.itm~ ~override/zstpitf0.itm~
        LPF ALTER_HEADER INT_VAR damage=4 damage_type=6 range=2 END
        LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=146,p2=1,res=zstpitf4,pro1=24~ END
        LPF ADD_EQUIPPED_EFF STR_VAR effects = ~op=176,p1=7;op=206,p1=-1,res=spin701~ END

    COPY_EXISTING ~dempit.cre~   ~override~
                  ~dempit01.cre~ ~override~
                  ~dempitsu.cre~ ~override~
                  ~telpit2.cre~  ~override~
                  ~telpit1.cre~  ~override~
        // HP
        WRITE_SHORT 0x24 110 // +30, 10 less than balor
        WRITE_SHORT 0x26 110

        // AC
        WRITE_SHORT 0x46 "-7" // +2, 1 worse than balor
        WRITE_SHORT 0x48 "-7"
        
        // THAC0
        WRITE_BYTE 0x52 5 // +2, 1 worse than balor

        // resistances
        WRITE_BYTE 0x5e 100 // 100 magic fire resist just because completeness
        WRITE_BYTE 0x5a 50 // half of balor cold resistance
        WRITE_BYTE 0x5f 50 // half of balor magic cold resistance
        WRITE_BYTE 0x5c 50 // acid resistance

        WRITE_BYTE 0x5d 65 // magic resistance from 50 (20 less than balor)

        PATCH_FOR_EACH offset IN 0x60 0x61 0x62 0x63 0x64 BEGIN // physical resistance
            WRITE_BYTE offset 20 // 0 -> 20, 5 less than balor
        END

        PATCH_FOR_EACH offset IN 0x6e 0x6f 0x70 0x71 0x72 0x73 0x74 0x75 BEGIN // legacy proficiency, making sure all are at 5
            WRITE_BYTE offset 5 
        END

        WRITE_BYTE 0x234 15 // making sure they're level 14 like balors (from 13)

        WRITE_BYTE 0x23a 22 // intelligence, from 9. Sorry mind flayers. Balors have 20
        WRITE_BYTE 0x23b 18 // wisdom, from 16, same as balors.
        WRITE_BYTE 0x23d 17 // constitution, from 9. No effect in most circumstances due to being non playable class

        WRITE_BYTE 0x273 class_imp

        ADD_CRE_ITEM ~helmnoan~ #0 #0 #0 ~unstealable&undroppable~ ~helmet~ // immunity to crits, just like balors
        ADD_CRE_ITEM ~zstpitf0~ #0 #0 #0 ~unstealable&undroppable~ ~weapon1~ EQUIP // new weapon

END