COPY_EXISTING "SW1H39.itm" ~override~
    LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@7560) END
    LPF ALTER_EFFECT INT_VAR check_globals=0 match_opcode=12 dicesize=3 dicenumber=1 END
    LPF GET_DMG_TYPE STR_VAR type="fire" RET fire = result END
    SET burning = RESOLVE_STR_REF(@7561)
    LPF ADD_ON_HIT_EFF INT_VAR p2=fire tmg=4 dnum=1 dsize=3 stype=1 STR_VAR effects=~op=12,tmg=0;op=12,dur=6;op=12,dur=12;op=139,tmg=0,dnum=0,dsize=0,p2=0,p1=%burning%~ END
BUT_ONLY
