ACTION_IF (VARIABLE_IS_SET ~zs_comp_1651~) BEGIN
  FAIL ~Script already included: zs_comp_1651~
END ELSE BEGIN
  OUTER_SET ~zs_comp_1651~ = 1
END

ACTION_IF GAME_IS "bg2ee eet" BEGIN
    COPY_EXISTING "LEAT23.ITM" ~override~
        LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6890) END

    COPY_EXISTING "LEAT23A.SPL" ~override~
        LPF GET_DMG_TYPE STR_VAR type = ~piercing~ RET piercing = result END
        LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter2 = piercing END
END
