COPY_EXISTING ~plat06.itm~ ~override~
              ~plat06_.itm~ ~override~
  LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@8470) END
  LPF ADD_EQUIPPED_EFF STR_VAR effects = ~op=27,p1=20~ END
IF_EXISTS

COPY_EXISTING ~bzplm06a.itm~ ~override~
  LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@8471) END
  LPF ADD_EQUIPPED_EFF STR_VAR effects = ~op=27,p1=20~ END
IF_EXISTS

ACTION_IF is_iwdee AND NOT FILE_EXISTS_IN_GAME "plat06.itm" AND NOT group_component BEGIN
  LAF LOG_TEXT INT_VAR predicate_stdout = (NOT group_component) STR_VAR log_level="abort" message = "Ankheg's Plate Armor not found in IWDEE. -- Harmless unless it's supposed to be there." END
END
