ACTION_IF (VARIABLE_IS_SET ~zs_comp_1510~) BEGIN
  FAIL ~Script already included: zs_comp_1510~
END ELSE BEGIN
  OUTER_SET ~zs_comp_1510~ = 1
END

ACTION_IF GAME_IS "bg2ee eet" BEGIN
    COPY_EXISTING "NPSHLD.ITM" ~override~
        LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6250) ench=2 END
        LPF ALTER_EFFECT INT_VAR check_headers = 0 match_opcode = 0 parameter1 = 3 END
        LPF RM_STAT_REQS INT_VAR str=SHORT_AT(0x26) END
END
