ACTION_IF NOT is_iwdee BEGIN

    ACTION_IF FILE_EXISTS_IN_GAME ~bdshld04.itm~ BEGIN

        COPY_EXISTING ~bdshld04.itm~ ~override~
            LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@7850) END
            LPF ALTER_EFFECT INT_VAR match_opcode=89 parameter1=12 END

            LPF CLONE_EFFECT INT_VAR match_opcode=89 opcode=86 parameter1=8 END
            LPF CLONE_EFFECT INT_VAR match_opcode=89 opcode=88 parameter1=5 END

            LPF ALTER_EFFECT INT_VAR match_opcode = 0 match_parameter2=2 parameter1=2 END
            LPF CLONE_EFFECT INT_VAR match_opcode = 0 match_parameter2=0 parameter2=8 parameter1=1 END

    END ELSE BEGIN
        LAF LOG_WARNING_FAIL INT_VAR force_warn=1 predicate_stdout = (NOT group_component) STR_VAR message = "[WARN]: No Rhino Beetle Shield found in the game -- Harmless if not EET or not SoD" END
    END

    ACTION_IF FILE_EXISTS_IN_GAME ~bdplat04.itm~ BEGIN

        COPY_EXISTING ~bdplat04.itm~ ~override~
            LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@7840) END
            LPF ALTER_EFFECT INT_VAR match_opcode=89 parameter1=18 END
            LPF CLONE_EFFECT INT_VAR match_opcode=89 opcode=86 parameter1=12 END
            LPF CLONE_EFFECT INT_VAR match_opcode=89 opcode=88 parameter1=8 END
            LPF ALTER_EFFECT INT_VAR match_opcode = 0 match_parameter2 = 2 parameter1 = 3 END
            LPF ALTER_EFFECT INT_VAR match_opcode = 0 match_parameter2 = 8 parameter1 = 2 END
            LPF ALTER_EFFECT INT_VAR match_opcode = 0 match_parameter2 = 4 parameter1 = 1 END

    END ELSE BEGIN
        LAF LOG_WARNING_FAIL INT_VAR force_warn=1 predicate_stdout = (NOT group_component) STR_VAR message = "[WARN]: No Rhino Beetle Plate found in the game -- Harmless if not EET or not SoD" END
    END

END
