COPY ~%MOD_FOLDER%/spells/arcane/disintegrate/common~ ~override~
COPY_EXISTING ~spwi616.spl~ ~override~
  LPF ALTER_SPELL INT_VAR desc = RESOLVE_STR_REF(@8630) END
  LPF ADD_SPL_TGTEFF STR_VAR effects = "pwr=0,rd=0,op=326,p2=105,p1=%class_golem_clay%,ip=0,res=zstdstgr" END


ACTION_IF NOT is_iwdee AND zst_522_use_iwdee_version BEGIN

  COPY ~%MOD_FOLDER%/spells/arcane/disintegrate/iwdee~ ~override~
  COPY_EXISTING ~spwi616.spl~ ~override~
    LPF ALTER_SPELL INT_VAR desc = RESOLVE_STR_REF(@8631) END
    LPF DELETE_EFFECT_EX INT_VAR check_globals=0 STR_VAR match_resource_ex="(NOT(~%o_resource%~ STR_EQ ~zstdstgr~))" END
    SET fade_speed = (30 << 16)
    LPF ADD_SPL_TGTEFF INT_VAR pwr=6 tmg=1 stype=1 STR_VAR effects = "op=215,res=disinth;op=174,res=#eff_m43;op=161,p1=1188522240,p2=%fade_speed%;op=326,res=#disint" END


    COPY_EXISTING ~#disint.spl~ ~override~
      LPF ALTER_EFFECT INT_VAR match_opcode=324 opcode=318 parameter1 = %splstate_fp_death_immunity% STR_VAR match_resource = "%SOURCE_RES%" END


END
