ACTION_IF zst_1532_add_1hp_to_shields BEGIN

  COPY_EXISTING ~shld03.itm~ ~override~
    READ_LONG 0x8 medium_shield_strref

  COPY_EXISTING ~shld01.itm~ ~override~
    READ_LONG 0x8 small_shield_strref

  COPY_EXISTING ~shld05.itm~ ~override~
    READ_LONG 0x8 large_shield_strref

  COPY_EXISTING ~shld08.itm~ ~override~
    READ_LONG 0x8 buckler_shield_strref

END

DEFINE_PATCH_MACRO patch BEGIN LPF ADD_EQUIPPED_EFF STR_VAR effects=~op=177,p2=2,p1=%ea_pc%,res=zstw1hp0~ END END

COPY ~%MOD_FOLDER%/general/1hp_bonus~ ~override~
COPY_EXISTING_REGEXP "^.+\.itm$" ~override~

  READ_SHORT 0x1c category

  PATCH_IF
      ( category =  6 AND zst_1532_add_1hp_to_belts     ) OR
      ( category =  4 AND zst_1532_add_1hp_to_boots     ) OR
      ( category =  3 AND zst_1532_add_1hp_to_bracers   ) OR
      ( category =  2 AND zst_1532_add_1hp_to_body_armor) OR
      ( category =  7 AND zst_1532_add_1hp_to_helmets   )
  BEGIN
    LPM patch
  END

  ELSE PATCH_IF category = 12 AND zst_1532_add_1hp_to_shields BEGIN

      READ_LONG 0x8 strref // strref
      PATCH_IF strref = medium_shield_strref OR strref = small_shield_strref OR
               strref = large_shield_strref  OR strref = buckler_shield_strref 
      BEGIN
          LPM patch
      END

  END

BUT_ONLY
