ACTION_IF is_bg2ee_or_eet BEGIN

    COPY ~%MOD_FOLDER%/items/armor_hart~ ~override~
    COPY_EXISTING ~plat16.itm~ ~override~
        LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@60200) END

        SPRINT extra_fixpack ""
        PATCH_IF has_eefixpack BEGIN
            SPRINT extra_fixpack "op=328,spec=1,p2=%splstate_fp_panic_immunity%;"
        END

        LPF ADD_EQUIPPED_EFF INT_VAR p2=8 p1=alignmen_mask_evil STR_VAR effects = ~%extra_fixpack%op=178,spec=1;op=178,p2=4,p1=%race_orc%,spec=1;op=179,spec=1;op=179,p2=4,p1=%race_orc%,spec=1;op=6,p1=2,p2=0;op=296,res=cdhorror;op=240,p2=36;op=169,p2=36;op=267,p1=17427;op=267,p1=14007;op=106,p2=1,p1=1;op=161;op=23;op=101,p2=24;op=142,p2=37;op=101,p2=23;op=101,p2=106;op=232,p2=1,res=zsthart0~ END

END