ACTION_IF (VARIABLE_IS_SET ~zs_comp_1650~) BEGIN
  FAIL ~Script already included: zs_comp_1650~
END ELSE BEGIN
  OUTER_SET ~zs_comp_1650~ = 1
END

COPY_EXISTING_REGEXP "^.+\.itm$" ~override~

  PATCH_IF SHORT_AT(0x1c) = 2 BEGIN
    LPF ITM_APPEARANCE RET armor_appearance = result END
    PATCH_IF "%armor_appearance%" STR_EQ "2w" BEGIN // apperance of simple robes
      LPF ALTER_ITEM STR_VAR appearance="3W" END
    END
  END

BUT_ONLY
