

ACTION_IF NOT is_iwdee BEGIN

  OUTER_SET opcode1 = 126
  OUTER_SET opcode2 = 176
  
  COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
    READ_LONG 0x28 animation
    PATCH_IF animation = 0x7f0b OR animation = 0x7f0a BEGIN
      SET present = 0
      LPM CRE_OP_PRESENT
      PATCH_IF NOT present BEGIN
        LPF ADD_CRE_EFFECT INT_VAR opcode = 176 timing=9 parameter1 = 6 END
      END

    END

  BUT_ONLY

END
