ACTION_IF (VARIABLE_IS_SET ~zs_comp_522~) BEGIN
  FAIL ~Script already included: zs_comp_522~
END ELSE BEGIN
  OUTER_SET ~zs_comp_522~ = 1
END

COPY ~%MOD_FOLDER%/spells/arcane/disintegrate~ ~override~
COPY_EXISTING ~SPWI616.SPL~ ~override~
  LPF ALTER_SPELL INT_VAR desc = RESOLVE_STR_REF(@8630) END
  LPF ADD_SPL_TGTEFF STR_VAR effects = "pwr=0,rd=0,op=326,p2=105,p1=%class_golem_clay%,ip=0,res=ZSTDSTGR" END
