ACTION_IF (VARIABLE_IS_SET ~zs_comp_1610~) BEGIN
  FAIL ~Script already included: zs_comp_1610~
END ELSE BEGIN
  OUTER_SET ~zs_comp_1610~ = 1
END

ACTION_IF is_bg2ee_or_eet BEGIN

  COPY_EXISTING "ohnrobe2.ITM" ~override~
    LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6530) END
    LPF ADD_EQUIPPED_EFF INT_VAR p1=5 STR_VAR effects=~op=332,p2=1;op=332,p2=2;op=332,p2=3;op=332,p2=4;op=346,p1=2,spec=6~ END

END
