ACTION_IF NOT is_iwdee BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~bdring03.itm~ BEGIN

    COPY_EXISTING ~bdring03.itm~ ~override~
      LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@7830) END
      LPF CLONE_EFFECT INT_VAR match_opcode=219 opcode = 178 special=2 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 178 opcode = 179 END

  END ELSE BEGIN
    LAF LOG_WARNING_FAIL INT_VAR force_warn=1 predicate_stdout = (NOT group_component) STR_VAR message = "[WARN]: No Ring of the Crusade found in the game -- Harmless if not EET or not SoD" END
  END

END
