ACTION_IF (VARIABLE_IS_SET ~zs_comp_2150~) BEGIN
  FAIL ~Script already included: zs_comp_2150~
END ELSE BEGIN
  OUTER_SET ~zs_comp_2150~ = 1
END

ACTION_IF GAME_IS "bg2ee eet" BEGIN
    COPY_EXISTING_REGEXP "SPCL90[47]\.SPL" ~override~
        LPF ALTER_SPELL INT_VAR secondary_type=0 END
    BUT_ONLY
    COPY_EXISTING_REGEXP "SPCL91[3467]\.SPL" ~override~
        LPF ALTER_SPELL INT_VAR secondary_type=0 END
    BUT_ONLY
END
