ACTION_IF NOT is_iwdee BEGIN

  COPY ~%MOD_FOLDER%/templates/eff/equipped.eff~ ~override/zstwausf.eff~ // apr
    LPF ALTER_EFF_FILE INT_VAR opcode = 1 parameter1 = 1 END
  
  DEFINE_PATCH_MACRO patch BEGIN
      LPF ADD_EQUIPPED_EFF INT_VAR p2=5 STR_VAR res=~zstwausf~ effects = "op=177,p1=%class_mage%;op=177,p1=%class_mage_thief%;op=177,p1=%class_cleric_mage%;op=177,p1=%class_sorcerer%" END
  END

  ACTION_IF NOT is_eet BEGIN
    
    COPY_EXISTING ~staf08.itm~ ~override~
      LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@8041) id_name = RESOLVE_STR_REF(@8040) END
      LPM patch

  END ELSE BEGIN

    COPY_EXISTING ~staf08_.itm~ ~override~
      LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@8041) id_name = RESOLVE_STR_REF(@8040) END
      LPM patch

    COPY_EXISTING ~staf08.itm~ ~override~
      LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@8042) id_name = RESOLVE_STR_REF(@8040) END
      LPM patch

  END

END
