COPY ~%MOD_FOLDER%/creatures/yuanti~ ~override~
OUTER_SPRINT melee_effect "zsipyua2"
OUTER_SET movement_boost = 4

COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
    READ_BYTE 0x272 race

    PATCH_IF race = race_yuanti AND NOT "%SOURCE_RES%" STR_EQ "zsipyua1" // formless serpent from my item pack
    BEGIN
        WRITE_SHORT 0x4c (THIS - 1)
        WRITE_SHORT 0x4e (THIS - 1)
        WRITE_SHORT 0x50 (THIS - 2)

        PATCH_IF BYTE_AT(0x60) < 18 BEGIN
            WRITE_BYTE 0x60 18
        END

        PATCH_IF BYTE_AT(0x62) < 9 BEGIN
            WRITE_BYTE 0x60 9
        END


        PATCH_IF BYTE_AT(0x63) < 9 BEGIN
            WRITE_BYTE 0x60 9
        END

        LPF ADD_CRE_PASSIVE INT_VAR op=173 p1=75 END
        LPM ADD_CRE_MELEE_EFFECT
        LPM ADD_CRE_MOVEMENT_BOOST
    END

BUT_ONLY
