DEFINE_PATCH_FUNCTION add_immunity_to
INT_VAR
    p1 = "-1"
    p2 = "-1"
    race = "-1"
    min_level = 0
    op = 324
    dur = 0
STR_VAR
    i = "first"
    res = "%SOURCE_RES%"
BEGIN
    LPF CLONE_EFFECT
        INT_VAR
            match_opcode = 12
            multi_match = 1
            opcode = 324
            duration=dur
            parameter2 = (p2 > "-1" ? p2 : 104)
            parameter1 = (p1 > "-1" ? p1 : race)
            dicesize = min_level
        STR_VAR
            insert=i
            resource="%res%"
    END
END

DEFINE_PATCH_MACRO patch_file BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=2 duration=1 STR_VAR resource="spcl411" END
END
LAF CREATE_TG_SPL STR_VAR filename = "zstrpim0" END 

COPY_EXISTING ~spcl411.spl~ ~override/zstrpim1.spl~ // base damage
    LPF ALTER_HEADER INT_VAR projectile = 0 END
    LPF DELETE_EFFECT_EX STR_VAR match_opcode_ex = "(o_opcode != 12)" END
    LPF DELETE_EFFECT_EX STR_VAR match_parameter2_ex = "(o_parameter2 = %op12_poison%)" END

COPY_EXISTING ~spcl411.spl~ ~override/zstrpim2.spl~ // protected damage (slay/poison)
    LPF ALTER_HEADER INT_VAR projectile = 0 END
    LPF DELETE_EFFECT_EX STR_VAR match_opcode_ex = "(o_opcode != 318 AND o_opcode != 12 AND o_opcode != 55)" END
    LPF DELETE_EFFECT_EX INT_VAR match_opcode = 12 STR_VAR match_parameter2_ex = "(o_parameter2 != %op12_poison%)" END
    LPF ALTER_EFFECT STR_VAR match_resource = ~spcl411~ resource="%DEST_RES%" END

COPY_EXISTING ~spcl411.spl~ ~override~
    PATCH_IF zst_3180_immunity_by_type BEGIN
        LPF add_immunity_to INT_VAR race = race_lich END
        LPF add_immunity_to INT_VAR race = race_demilich END
        LPF add_immunity_to INT_VAR race = race_dragon END
    END

    PATCH_IF zst_3180_immunity_by_power BEGIN
        LPF add_immunity_to INT_VAR p2=2 p1=0 min_level = 25 END
    END

    PATCH_IF zst_3180_only_once_per_sec BEGIN
        LPF DELETE_EFFECT_EX INT_VAR check_globals=0 STR_VAR match_opcode_ex= "(o_opcode != 324 AND o_opcode != 254)" END
        LPF ADD_SPL_TGTEFF INT_VAR rd=0 pwr=0 STR_VAR effects = ~op=146,res=zstrpim1,p2=1;op=146,res=zstrpim2,p2=1;op=146,res=zstrpim0,p2=1~ END
    END

    LPF ALTER_EFFECT INT_VAR match_opcode = 324 opcode = 318 END

ACTION_IF zst_3180_modify_trap_limit > 0 BEGIN

    COPY_EXISTING ~traplimt.2da~ ~override~
        LPF SWAP_2DA_TABLE_VALUE INT_VAR column = 1 STR_VAR replacement = "%zst_3180_modify_trap_limit%" END
        PRETTY_PRINT_2DA

END