ACTION_IF (VARIABLE_IS_SET ~zs_comp_1603~) BEGIN
  FAIL ~Script already included: zs_comp_1603~
END ELSE BEGIN
  OUTER_SET ~zs_comp_1603~ = 1
END

ACTION_IF is_bg2ee_or_eet BEGIN

  COPY_EXISTING ~HALB05.ITM~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@7710) END
    LPF ALTER_HEADER INT_VAR match_type=1 damage=4 END
    LPF ALTER_EFFECT INT_VAR match_opcode=12 special=1024 END

END
