

COPY_EXISTING ~sppr201.spl~ ~override~
    LPF ALTER_SPELL INT_VAR desc = RESOLVE_STR_REF(@5260) END
    LPF ALTER_HEADER INT_VAR range=10 projectile = 160 END

    PATCH_IF zst_507_disable_aidglow BEGIN
        LPF DELETE_EFFECT INT_VAR opcode=8 END
    END
    
    LPF CLONE_EFFECT_EX INT_VAR match_opcode=129 opcode=18 
    STR_VAR parameter1_ex = "(((o_duration / 6) - 1) < 5 ? 1 : (((o_duration / 6) - 1) - 3))" END
