ACTION_IF NOT is_iwdee BEGIN

    COPY ~%MOD_FOLDER%/items/voidweapons~ ~override~
    ACTION_IF zst_1150_dice_warhammers AND
            (MOD_IS_INSTALLED "ZSTweaks.tp2" "1150" OR
            (group_component AND zst_group_1150_weapon_dice))
    BEGIN

        COPY_EXISTING ~zstwvd01.spl~ ~override~
            LPF ALTER_EFFECT INT_VAR match_opcode = 12 dicesize = 5 END

    END

    COPY_EXISTING ~bdsw1h06.itm~ ~override~
        LPF ADD_EQUIPPED_EFF STR_VAR effects = ~op=341,p2=1,res=zstwvd00;op=177,p2=3,p1=%general_undead%,res=zstwvd04~ END

    COPY_EXISTING ~bdhamm02.itm~ ~override~
        LPF ADD_EQUIPPED_EFF STR_VAR effects = ~op=341,p2=1,res=zstwvd01;op=177,p2=3,p1=%general_undead%,res=zstwvd04~ END

    ACTION_IF FILE_EXISTS_IN_GAME "bdarow02.itm" BEGIN

        ACTION_IF NOT FILE_EXISTS_IN_GAME ~zstarrow.pro~ BEGIN
            COPY_EXISTING ~arrow.pro~ ~%MOD_FOLDER%/pro/zstarrow.pro~
                WRITE_SHORT 0xa (THIS + 5)
                WRITE_ASCII 0x104 "" #8
            ADD_PROJECTILE ~%MOD_FOLDER%/pro/zstarrow.pro~
        END

        COPY_EXISTING ~zstwvd03.spl~ ~override~
            LPF ALTER_HEADER INT_VAR projectile = %zstarrow% END

        COPY_EXISTING ~bdarow02.itm~ ~override~
            LPF ADD_EQUIPPED_EFF STR_VAR effects = ~op=341,p2=1,res=zstwvd03~ END

    END

    ACTION_IF FILE_EXISTS_IN_GAME "bdbull02.itm" BEGIN

        ACTION_IF NOT FILE_EXISTS_IN_GAME ~zstbulet.pro~ BEGIN
            COPY_EXISTING ~bullet.pro~ ~%MOD_FOLDER%/pro/zstbulet.pro~
                WRITE_SHORT 0xa (THIS + 5)
                WRITE_ASCII 0x104 "" #8
            ADD_PROJECTILE ~%MOD_FOLDER%/pro/zstbulet.pro~
        END

        COPY_EXISTING ~zstwvd05.spl~ ~override~
            LPF ALTER_HEADER INT_VAR projectile = %zstbulet% END

        COPY_EXISTING ~bdbull02.itm~ ~override~
            LPF ADD_EQUIPPED_EFF STR_VAR effects = ~op=341,p2=1,res=zstwvd05~ END

    END

END

