

ACTION_IF NOT is_iwdee BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~bdhelm09.itm~ BEGIN

    COPY_EXISTING "bdhelm09.itm" ~override~
      LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6970) END
      LPF ALTER_EFFECT INT_VAR check_headers = 0 match_parameter1 = 3 match_parameter2 = 0 parameter1 = 5 END

  END ELSE BEGIN
    ACTION_IF NOT group_component BEGIN WARN "bdhelm09.itm not found" END
  END

END
