 // converting to LG
COPY_EXISTING ~c6kalden.cre~ ~override~ // paladins that help with bodhi, currently LN, should be LG
              ~c6levin.cre~  ~override~ // paladins that help with bodhi, currently LN, should be LG
              ~c6squire.cre~ ~override~ // paladins that help with bodhi, currently LN, should be LG
              ~derrick.cre~  ~override~ // ranger helping valygar, shouldn't be LN
              ~elotte.cre~   ~override~ // squire elotte, paladin stronghold duties, currently LN, likely better as LG
              ~solar.cre~    ~override~
  LPF ALTER_CRE INT_VAR alignment=alignmen_lawful_good END
IF_EXISTS

// converting to NG
COPY_EXISTING ~arval.cre~    ~override~ // Arval Mornmaster, currently LE, should be NG
              ~bharval.cre~  ~override~ // Arval Mornmaster, currently LE, should be NG
              ~c6cler1.cre~  ~override~ // cleric of lathander, neutral, should probably be NG
  LPF ALTER_CRE INT_VAR alignment=alignmen_neutral_good END
IF_EXISTS

// converting to CG
COPY_EXISTING ~jarev1.cre~   ~override~ // nameless bard harper, currently CN, makes more sense as CG
              ~nevaziah.cre~ ~override~ // the confused undead spellcaster that wants to protect his pupils (CE)
              ~udvith.cre~   ~override~ // vithal, currently LE, there are no obvious signs he's evil
              ~aataqah.cre~  ~override~ // he's a djinni and djinni are always chaotic good (lawful neutral)
              ~ohhdjinn.cre~ ~override~ // he's a noble djinni
              ~ppdjinn.cre~  ~override~ // djinni
  LPF ALTER_CRE INT_VAR alignment=alignmen_chaotic_good END
IF_EXISTS

// converting to LN
COPY_EXISTING ~bdact07.cre~ ~override~ // non-interctable NPC hired for the bard stronghold, LE for some reason
              ~taxcoll.cre~ ~override~ // tax collector, the man is doing his job, he ain't neutral evil

  LPF ALTER_CRE INT_VAR alignment=alignmen_lawful_neutral END
IF_EXISTS

//converting to TN
COPY_EXISTING ~bdock1.cre~   ~override~ // overworked dockhand ogres
              ~bdock2.cre~   ~override~
              ~becky.cre~    ~override~ // no alignment assigned
              ~diane.cre~    ~override~ // no alignment assigned
              ~druid10a.cre~ ~override~ // druid set as evil
              ~druid10b.cre~ ~override~ // druid set as evil
              ~druid12a.cre~ ~override~ // druid set as evil
              ~druid12b.cre~ ~override~ // druid set as evil
              ~druid6a.cre~  ~override~ // druid set as evil
              ~druid8a.cre~  ~override~ // druid set as evil
              ~druid8b.cre~  ~override~ // druid set as evil
              ~ecolt.cre~    ~override~ // no alignment assigned
              ~kpmerc01.cre~ ~override~ // person complaining of bandit attacks in fighter stronghold (why evil?)
              ~bazliz03.cre~ ~override~ // lizardmen, often neutral, even in this game, evil here for some reason
              ~bazliz04.cre~ ~override~ // lizardmen, often neutral, even in this game, evil here for some reason
              ~ohbliz01.cre~ ~override~ // lizardman
              ~clgol01.cre~  ~override~ // clay golem in planar sphere is chaotic good somehow?
              ~bpclay.cre~   ~override~
              ~battho.cre~   ~override~ // battle horror, evil, but is a construct like golems, should be neutral
              ~senstalk.cre~ ~override~ // invisible stalker, they're neutral elemental creatures
              ~gorstalk.cre~ ~override~ // invisible stalker, they're neutral elemental creatures
              ~stalke.cre~   ~override~ // invisible stalker, they're neutral elemental creatures
              ~spidswsu.cre~ ~override~ // sword spider is neutral
              ~spidsw01.cre~ ~override~ // sword spider is neutral
              ~spspid07.cre~ ~override~ // sword spider is neutral
              ~plyspid.cre~  ~override~  // sword spider is neutral
              ~spidphas.cre~ ~override~ // phase spiders are neutral
              ~bdspidgi.cre~ ~override~
              ~ms5gspi.cre~  ~override~
              ~cyspidsw.cre~ ~override~
              ~bpspid01.cre~ ~override~ //bp spiders
              ~bpspid02.cre~ ~override~
              ~bpspid03.cre~ ~override~
              ~bdspid7l.cre~ ~override~
              ~rsspidgi.cre~ ~override~ // spider
              ~bdspidga.cre~ ~override~
              ~bdwistak.cre~ ~override~
              ~bdhelp01.cre~ ~override~ // spider
              ~bdhelp03.cre~ ~override~ // spider
              ~udspid01.cre~ ~override~ // spider
              ~spidgi.cre~   ~override~ // spider
              ~spidsw.cre~   ~override~ // spider
              ~bdspider.cre~ ~override~
              ~udspid02.cre~ ~override~ // spider
              ~udspid03.cre~ ~override~ // spider
              ~udspid04.cre~ ~override~ // spider
              ~udspid05.cre~ ~override~ // spider
              ~udspid06.cre~ ~override~ // spider
              ~udspid07.cre~ ~override~ // spider
              ~udspid08.cre~ ~override~ // spider
              ~ohbspi01.cre~ ~override~ // spider
              ~ohdanim4.cre~ ~override~ // spider
              ~spidgi01.cre~ ~override~ // spider
              ~spidgisu.cre~ ~override~ // spider
              ~spidsm01.cre~ ~override~ // spider
              ~spidsm02.cre~ ~override~ // spider
              ~spspid05.cre~ ~override~ // spider
              ~sensmsp.cre~  ~override~ //spider
              ~ohhspid1.cre~ ~override~  // hexxat quest spider is neutral
              ~ohhspid2.cre~ ~override~  // hexxat quest spider is neutral
              ~ohhspi01.cre~ ~override~  // hexxat quest spider is neutral
              ~ohhspi02.cre~ ~override~  // hexxat quest spider is neutral
              ~ohhspi03.cre~ ~override~  // hexxat quest spider is neutral
              ~plyspid2.cre~ ~override~
              ~wyvern01.cre~ ~override~ // wyverns should be true neutral in my estimation, currently locked as neutral
              ~wyvernsu.cre~ ~override~
              ~corwyvrn.cre~ ~override~
              ~wyverba.cre~  ~override~
              ~wyvern.cre~   ~override~
              ~wyvernbi.cre~ ~override~
              ~wyvmat.cre~   ~override~
              ~bdwyvr03.cre~ ~override~
              ~bdwyvr02.cre~ ~override~
              ~bdwyvr01.cre~ ~override~
              ~dlbonec.cre~  ~override~
              ~airaspec.cre~ ~override~ // "air aspect" at Durlag's. Seems to be a wyvern in every way
              ~wyvbab01.cre~ ~override~
              ~wyvgre01.cre~ ~override~
              ~ohbmena8.cre~ ~override~
              ~nwyvbab.cre~  ~override~
              ~plywyvrn.cre~ ~override~
              ~pwyvv01.cre~  ~override~
              ~ohbmena5.cre~ ~override~ // boalisk, snakes should be neutral
              ~snakeb01.cre~ ~override~
              ~obsmod01.cre~ ~override~ // unaligned golem, probably unused but still
              ~tethto3.cre~  ~override~ // doppeldanger tehtoril, should be neutral, not reflect alignment of original
              ~phlydi3.cre~  ~override~ // dopple phlydia
              ~doomsa.cre~   ~override~ // doomsayer is a construct
              ~duplica1.cre~ ~override~ // mirror fiend, flesh golem
              ~es12watr.cre~ ~override~
              ~es16watr.cre~ ~override~
              ~es20watr.cre~ ~override~
              ~es24watr.cre~ ~override~
              ~rabbit.cre~   ~override~ // no alignment rabbit
              ~nechick1.cre~ ~override~ // no alignment squirrel
  LPF ALTER_CRE INT_VAR alignment=alignmen_neutral END
IF_EXISTS

// converting to Chaotic Neutral
COPY_EXISTING ~shth011.cre~  ~override~ // Hanz thief, this version is evil for some reason
              ~shth05.cre~   ~override~ // Joster getting a quota for Renal, original is LE
              ~shoal.cre~    ~override~ // Shoal the nereid, TN, should be chaotic neutral based on attitude (they're chaos-bound)
              ~sil.cre~      ~override~ // sil, a sirine, they're always chaotic neutral
              ~sirine.cre~   ~override~ // other sirines
              ~sirine02.cre~ ~override~
              ~sirine_a.cre~ ~override~
              ~sirine_b.cre~ ~override~
              ~meiala.cre~   ~override~
              ~larria.cre~   ~override~
              ~islsir.cre~   ~override~
  LPF ALTER_CRE INT_VAR alignment=alignmen_chaotic_neutral END
IF_EXISTS

// converting to LE
COPY_EXISTING ~aemerhob.cre~ ~override~ // hobgoblin, no alignment for some reason, LE now
              ~gguard01.cre~ ~override~ // guard harassing evilly a beggar
              ~golbra01.cre~ ~override~ // brain golem, they're always LE like mindflayers, CG in EE (??)
              ~udgolem.cre~  ~override~ // brain golem, they're always LE like mindflayers, Neutral in EE
              ~hgwra01.cre~  ~override~ // Gorion Wraith, shouldn't be Lawful Good
              ~maeguy02.cre~ ~override~ // maevar henchman, probably shouldnt be CN, instead LE
              ~noblem1.cre~  ~override~ // evil nobleman asshole
              ~noblem2.cre~  ~override~ // evil nobleman asshole
              ~tolger.cre~   ~override~ // tolgerias, he's obviously evil lol, not chaotic good
              ~tolger2.cre~  ~override~ // tolgerias, he's obviously evil lol, not chaotic good
              ~dpmon01.cre~  ~override~ // cutscene mindflayer
              ~dpmon03.cre~  ~override~ // cutscene vampire
              ~bpelan.cre~   ~override~ // unaligned raksasha, they're LE
              ~bphbar1.cre~  ~override~ // unaligned hobgoblin in BP1
              ~bphbwr1.cre~  ~override~ // unaligned hobgoblin in BP1
              ~bphbwz1.cre~  ~override~ // unaligned hobgoblin in BP1
  LPF ALTER_CRE INT_VAR alignment=alignmen_lawful_evil END
IF_EXISTS

// converting to NE
COPY_EXISTING ~hellil01.cre~ ~override~ // hellhound, should be evil, not neutral
              ~mgteos01.cre~ ~override~ // Teos, the asshole wizard in the planar sphere for the stronghold
              ~tobban01.cre~ ~override~ // gromnir henchmen, should be evil, not neutral
              ~tobban02.cre~ ~override~
              ~tobban03.cre~ ~override~
              ~tobban04.cre~ ~override~
              ~tobpar01.cre~ ~override~
              ~tobpar02.cre~ ~override~
              ~tobpar03.cre~ ~override~
              ~tobpar05.cre~ ~override~
              ~tobpar06.cre~ ~override~
              ~ad3sklm.cre~  ~override~ // stray skeleton (iwdification / iwdee?)
              ~rskel01.cre~  ~override~ // stray skeleton
              ~rskel03.cre~  ~override~ // stray skeleton
              ~uddoor07.cre~ ~override~ // stray skeleton
              ~ttskel.cre~   ~override~ // stray skeleton
              ~iskelet.cre~  ~override~
              ~skelsu01.cre~ ~override~
              ~skelsu07.cre~ ~override~
              ~skelsu11.cre~ ~override~
              ~skelsu15.cre~ ~override~
              ~ms7bgrd.cre~  ~override~
              ~ktsk1.cre~    ~override~
              ~ktsk1h.cre~   ~override~
              ~ktska1.cre~   ~override~
              ~ktska2.cre~   ~override~
              ~ktska3.cre~   ~override~
              ~ktskh2.cre~   ~override~
              ~ktskh3.cre~   ~override~
              ~ktskt1.cre~   ~override~
              ~ktskt2.cre~   ~override~
              ~kttas1.cre~   ~override~
              ~kttas2.cre~   ~override~
              ~kttas2h.cre~  ~override~
              ~kttga1.cre~   ~override~
              ~kttga2.cre~   ~override~
              ~kttga3.cre~   ~override~
              ~kttgm1.cre~   ~override~
              ~kttgm3.cre~   ~override~
              ~kttgm1.cre~   ~override~
              ~kttgm3.cre~   ~override~
              ~dlcldaxe.cre~ ~override~
              ~dlcldhnd.cre~ ~override~
              ~dlcldmce.cre~ ~override~
              ~dlcldswd.cre~ ~override~
              ~dlfznbne.cre~ ~override~
              ~dliceaxe.cre~ ~override~
              ~dlicehnd.cre~ ~override~
              ~dliceswd.cre~ ~override~
              ~bpskel.cre~   ~override~
              ~ad1sklm.cre~  ~override~
              ~ad2sklm.cre~  ~override~
              ~bon8005.cre~  ~override~ // boneguard
              ~dlbnegrd.cre~ ~override~
              ~bon8013.cre~  ~override~
              ~bonegard.cre~ ~override~
              ~ad2sklr.cre~  ~override~
              ~ad3sklr.cre~  ~override~
              ~ad4sklr.cre~  ~override~
              ~cdmhskel.cre~ ~override~
              ~kryskel.cre~  ~override~
              ~bdskgr00.cre~ ~override~
              ~bdskgr04.cre~ ~override~
              ~bdskgr01.cre~ ~override~
              ~bdskgr02.cre~ ~override~
              ~bdskgr03.cre~ ~override~
              ~bdskgr05.cre~ ~override~
              ~bdskgr06.cre~ ~override~
              ~skelar01.cre~ ~override~
              ~skelar02.cre~ ~override~
              ~skele2.cre~   ~override~
              ~skelded.cre~  ~override~
              ~skelet01.cre~ ~override~
              ~skelhp1.cre~  ~override~
              ~skelaci.cre~  ~override~
              ~skeldis.cre~  ~override~
              ~skelet.cre~   ~override~
              ~lskarmms.cre~ ~override~
              ~skelarh1.cre~ ~override~
              ~skelarh2.cre~ ~override~
              ~skaldar.cre~  ~override~
              ~skelarm.cre~  ~override~
              ~skelblad.cre~ ~override~
              ~skelblah.cre~ ~override~
              ~skelblaz.cre~ ~override~
              ~skelblst.cre~ ~override~
              ~skelbow.cre~  ~override~
              ~skelserr.cre~ ~override~
              ~lskarmsw.cre~ ~override~
              ~skelet02.cre~ ~override~
              ~skelet03.cre~ ~override~
              ~skeletb.cre~  ~override~
              ~skelets.cre~  ~override~
              ~skelet_a.cre~ ~override~
              ~skelet_b.cre~ ~override~
              ~skelet_c.cre~ ~override~
              ~skarmax.cre~  ~override~
              ~skarmms.cre~  ~override~
              ~skarmsw.cre~  ~override~
              ~skelfire.cre~ ~override~
              ~skelice.cre~  ~override~
              ~skelmel.cre~  ~override~
              ~skelpetr.cre~ ~override~
              ~bhghoul3.cre~ ~override~ // non evil zombie
              ~bdshzom1.cre~ ~override~
              ~zombiep.cre~  ~override~
              ~ad3zomb.cre~  ~override~
              ~ad4zomb.cre~  ~override~
              ~ad5zomb.cre~  ~override~
              ~zombie01.cre~ ~override~ // non evil zombie
              ~zombie.cre~   ~override~ // non evil zombie
              ~zombieb.cre~  ~override~ // non evil zombie
              ~zombiew.cre~  ~override~ // non evil zombie
              ~zombie_a.cre~ ~override~ // non evil zombie
              ~zombie_b.cre~ ~override~ // non evil zombie
              ~zombie_c.cre~ ~override~ // non evil zombie
              ~zombie_d.cre~ ~override~ // non evil zombie
              ~zombie_e.cre~ ~override~ // non evil zombie
              ~zombju01.cre~ ~override~ // non evil zombie
              ~bhghoul5.cre~ ~override~ // non evil zombie
              ~zomblo01.cre~ ~override~ // non evil zombie
              ~zombse01.cre~ ~override~ // non evil zombie
              ~sahzomb.cre~  ~override~ // non evil zombie
              ~sahzom01.cre~ ~override~ // non evil zombie
              ~rzomb01.cre~  ~override~ // non evil zombie
              ~lzombie.cre~  ~override~
              ~ktzom1.cre~   ~override~
              ~ad2zomb.cre~  ~override~
              ~nevm5.cre~    ~override~
              ~gtcit3.cre~   ~override~ // non evil zombie
              ~gtcit4.cre~   ~override~ // non evil zombie
              ~gtcit5.cre~   ~override~ // non evil zombie
              ~sewerf2.cre~  ~override~ // sewerfolk -- zombie
              ~dpmon02.cre~  ~override~ // cutscene lich
              ~fsskel.cre~   ~override~ // WK skeleton?
              ~zorl.cre~     ~override~ // greater doppledanger
              ~d2dop.cre~    ~override~ // another
              ~l#wolst.cre~  ~override~ // winter wolf from lava
              ~gdopp7.cre~   ~override~ // greater doppelgangers
              ~gdopp71.cre~  ~override~
              ~gdopp72.cre~  ~override~
              ~gdopp73.cre~  ~override~
              ~dopdur1.cre~  ~override~
              ~dopdur2.cre~  ~override~
              ~dopdur3.cre~  ~override~
              ~doppgr.cre~  ~override~
              ~gdopp74.cre~  ~override~
              ~gdopp75.cre~  ~override~
              ~gorion3.cre~  ~override~
              ~dopdop.cre~   ~override~
              ~elmins.cre~   ~override~
              ~elmins4.cre~  ~override~
              ~islann.cre~   ~override~ // probably the dopple that killed her and ate her brain
              ~shape.cre~    ~override~ // frennedan, obviously evil (also G. Dopple, which are always evil -- was Chaotic Neutral)
  LPF ALTER_CRE INT_VAR alignment=alignmen_neutral_evil END
IF_EXISTS

// converting to CE
COPY_EXISTING ~shadeld.cre~  ~override~ // a version of Shade Lord that is Neutral Good
              ~trskind1.cre~ ~override~ // skeletal version of skinner that is for some reason Neutral Good
              ~chang02.cre~  ~override~ // angelo (tob) version that is neutral good
              ~gnollhp1.cre~ ~override~ // gnoll version that is chaotic neutral
              ~alufie02.cre~ ~override~ // alu-fiend, probably unused, should probably not be lawful neutral
              ~c6lanf.cre~   ~override~ // lanfear is a wolfwere which are chaotic evil
              ~ogregrsu.cre~ ~override~ // ogre
              ~ogresu.cre~   ~override~
              ~plyogre.cre~  ~override~
              ~test.cre~     ~override~
              ~korax.cre~    ~override~ // korax the ghoul should probably be chaotic evil
              ~gorwom02.cre~ ~override~ // WK The Huntress
              ~l#chich1.cre~ ~override~ // chimeras from lava
              ~l#chich2.cre~ ~override~
              ~bpogre01.cre~ ~override~ // unaligned BP1 ogre
  LPF ALTER_CRE INT_VAR alignment=alignmen_chaotic_evil END
IF_EXISTS

ACTION_IF zs_debug BEGIN
  PRINT "[DEBUG][INFO]: Checking for possible suspects with wrong alignment (Oversight++ component 3010)... Check the debug.txt file for details after the installation and if you find anything interesting, let Kaelyn know, will ya?"
  LAF LOG_TEXT INT_VAR predicate_stdout=FALSE STR_VAR flog_preamble="" filename="debug" message="-- START OF OVERSIGHT++ ALIGNMENT CHECKING --" END

  OUTER_SET matches = 0
  COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~

    // exceptions that can't be caught easily
    PATCH_IF NOT "%SOURCE_RES%" STR_EQ ~ohbdrag1~ AND // bp2 dragons
             NOT "%SOURCE_RES%" STR_EQ ~ohbdrag2~ AND
             NOT "%SOURCE_RES%" STR_EQ ~ohbdrag3~ AND
             NOT "%SOURCE_RES%" STR_EQ ~ohbewwei~ AND // water weird
             NOT "%SOURCE_RES%" STR_EQ ~gorcamb~  AND // aesgareth
             NOT "%SOURCE_RES%" STR_EQ ~elemchan~ AND // elemental princes
             NOT "%SOURCE_RES%" STR_EQ ~elemcryo~ AND
             NOT "%SOURCE_RES%" STR_EQ ~elemhydr~ AND
             NOT "%SOURCE_RES%" STR_EQ ~elemimix~ AND
             NOT "%SOURCE_RES%" STR_EQ ~elemogre~ AND
             NOT "%SOURCE_RES%" STR_EQ ~elemsunn~ AND
             NOT "%SOURCE_RES%" STR_EQ ~elemyanc~ AND
             NOT "%SOURCE_RES%" STR_EQ ~elemzaam~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdock1~   AND //ogre dock workers
             NOT "%SOURCE_RES%" STR_EQ ~bdock2~   AND
             NOT "%SOURCE_RES%" STR_EQ ~golbra01~ AND // brain golem
             NOT "%SOURCE_RES%" STR_EQ ~golbur01~ AND // burning man
             NOT "%SOURCE_RES%" STR_EQ ~ohdcdawg~ AND // celestial hound
             NOT "%SOURCE_RES%" STR_EQ ~sahbeh01~ AND // spectator
             NOT "%SOURCE_RES%" STR_EQ ~cultbh4~ AND // spectator
             NOT "%SOURCE_RES%" STR_EQ ~senbeh01~ AND // spectator
             NOT "%SOURCE_RES%" STR_EQ ~behspe01~ AND // spectator
             NOT "%SOURCE_RES%" STR_EQ ~uhogre01~ AND // madulf people
             NOT "%SOURCE_RES%" STR_EQ ~uhogre02~ AND // madulf people
             NOT "%SOURCE_RES%" STR_EQ ~uhogre03~ AND // madulf people
             NOT "%SOURCE_RES%" STR_EQ ~uhogre04~ AND // madulf people
             NOT "%SOURCE_RES%" STR_EQ ~uhogre05~ AND // madulf people
             NOT "%SOURCE_RES%" STR_EQ ~moondog~  AND //  moondog
             NOT "%SOURCE_RES%" STR_EQ ~obsfir05~ AND // hellhound
             NOT "%SOURCE_RES%" STR_EQ ~hellho01~ AND // hellhound
             NOT "%SOURCE_RES%" STR_EQ ~hellil01~ AND // hellhound
             NOT "%SOURCE_RES%" STR_EQ ~ohdtmfil~ AND // faerie dragon dorn quest
             NOT "%SOURCE_RES%" STR_EQ ~udgolem~  AND // brain golem
             NOT "%SOURCE_RES%" STR_EQ ~ohdfaer~  AND // faerie dragon
             NOT "%SOURCE_RES%" STR_EQ ~finsol01~ AND // amelyssan stuff, it's fine
             NOT "%SOURCE_RES%" STR_EQ ~finsol02~ AND
             NOT "%SOURCE_RES%" STR_EQ ~finsol03~ AND
             NOT "%SOURCE_RES%" STR_EQ ~hspectr1~ AND //spectral harpist, not a typical undead
             NOT "%SOURCE_RES%" STR_EQ ~hspectr2~ AND
             NOT "%SOURCE_RES%" STR_EQ ~hspectr3~ AND
             NOT "%SOURCE_RES%" STR_EQ ~ysgp01~   AND // cute bhaalspawns with unusual alignment, let's leave them be
             NOT "%SOURCE_RES%" STR_EQ ~ysgp02~   AND
             NOT "%SOURCE_RES%" STR_EQ ~ysgp03~   AND
             NOT "%SOURCE_RES%" STR_EQ ~ysgp05~   AND
             NOT "%SOURCE_RES%" STR_EQ ~gorsal~   AND  // saladrex is just special, let's leave him alone
             NOT "%SOURCE_RES%" STR_EQ ~famfai25~ AND // familiars
             NOT "%SOURCE_RES%" STR_EQ ~famfair~  AND
             NOT "%SOURCE_RES%" STR_EQ ~fampsd~   AND
             NOT "%SOURCE_RES%" STR_EQ ~fampsd25~ AND
             NOT "%SOURCE_RES%" STR_EQ ~uhostile~ AND // probably some helper creature...
             NOT "%SOURCE_RES%" STR_EQ ~revent~   AND // revenants are a rare non-evil type of undead
             NOT "%SOURCE_RES%" STR_EQ ~revnant~  AND //
             NOT "%SOURCE_RES%" STR_EQ ~bpreve01~ AND //
             NOT "%SOURCE_RES%" STR_EQ ~malkal~   AND //
             NOT "%SOURCE_RES%" STR_EQ ~bdnuber1~ AND // undead nüber
             NOT "%SOURCE_RES%" STR_EQ ~bdnuber2~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdendles~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdcchob2~ AND  // beastial humanoids in Argent's crusade (often CN)
             NOT "%SOURCE_RES%" STR_EQ ~bdcckob1~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdccogr1~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdcru118~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdcru46~  AND
             NOT "%SOURCE_RES%" STR_EQ ~bdcruml7~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdcrur29~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdcrus86~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdcrus8d~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdwave12~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bddead01~ AND // drowned in blood, based on drowned dead, neutral undead (for some reason)
             NOT "%SOURCE_RES%" STR_EQ ~bddispbe~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bddispbp~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdcutid2~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdmkhi7~  AND // mkhiin
             NOT "%SOURCE_RES%" STR_EQ ~bdtreant~ AND // dark treant, they're evil
             NOT "%SOURCE_RES%" STR_EQ ~c0aualch~ AND // helper cre
             NOT "%SOURCE_RES%" STR_EQ ~c0auin4~  AND
             NOT "%SOURCE_RES%" STR_EQ ~c0ausumm~ AND
             NOT "%SOURCE_RES%" STR_EQ ~rbidrow~  AND // drowned dead is neutral
             NOT "%SOURCE_RES%" STR_EQ ~kaylessa~ AND //benevolvent spected
             NOT "%SOURCE_RES%" STR_EQ ~lizking~  AND // lizardfolk, malevolent
             NOT "%SOURCE_RES%" STR_EQ ~dlyeti~   AND // unusually evil yeti
             NOT "%SOURCE_RES%" STR_EQ ~larze~    AND // true neutral ogre looking for your bounty
             NOT "%SOURCE_RES%" STR_EQ ~fear~     AND
             NOT "%SOURCE_RES%" STR_EQ ~fearm~    AND
             NOT "%SOURCE_RES%" STR_EQ ~nesqrl~   AND
             NOT "%SOURCE_RES%" STR_EQ ~mistpo01~ AND
             NOT "%SOURCE_RES%" STR_EQ ~mistposu~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdtarget~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdforcw1~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdforcw3~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bddsarc4~ AND
             NOT "%SOURCE_RES%" STR_EQ ~bdstonec~
    BEGIN

      SET str_length = STRING_LENGTH "%SOURCE_RES%"
      PATCH_IF str_length >= 2 BEGIN
        LPF SUBSTRING INT_VAR length = 2 STR_VAR string = "%SOURCE_RES%" RET substring END
      END

      PATCH_IF VARIABLE_IS_SET substring AND NOT "%substring%" STR_EQ "ZS" BEGIN

        READ_BYTE 0x271 general
        READ_BYTE 0x272 race
        READ_BYTE 0x273 class

        PATCH_IF class = class_doppelganger_greater OR LONG_AT(0x28) = 0x7501 BEGIN // greater dopples are evil
            READ_BYTE 0x27b alignment
            PATCH_IF alignment != alignmen_chaotic_evil AND
                     alignment != alignmen_lawful_evil  AND
                     alignment != alignmen_neutral_evil
            BEGIN
              ++matches
              READ_STRREF 0x08 name ELSE "Unknown name"
              LOOKUP_IDS_SYMBOL_OF_INT found_race RACE race
              LOOKUP_IDS_SYMBOL_OF_INT found_general GENERAL general
              LOOKUP_IDS_SYMBOL_OF_INT found_class CLASS class
              LOOKUP_IDS_SYMBOL_OF_INT found_alignment ALIGNMEN alignment

              LPF LOG_TEXT STR_VAR filename="debug" log_level="debug" message = "Found a greater doppelganger %found_alignment% creature of race %found_race%, general %found_general%, and class %found_class%, that should be evil: %SOURCE_RES% -- %name%" END
            END
        END

        PATCH_IF race = race_fairy BEGIN
          PATCH_IF class     = class_fairy_nereid       AND
                   alignment != alignmen_chaotic_good    AND
                   alignment != alignmen_chaotic_evil    AND
                   alignment != alignmen_chaotic_neutral
          BEGIN
              READ_BYTE 0x27b alignment
              PATCH_IF alignment != alignmen_chaotic_good    AND
                       alignment != alignmen_chaotic_evil    AND
                       alignment != alignmen_chaotic_neutral
              BEGIN
                ++matches
                READ_STRREF 0x08 name ELSE "Unknown name"
                LOOKUP_IDS_SYMBOL_OF_INT found_race RACE race
                LOOKUP_IDS_SYMBOL_OF_INT found_general GENERAL general
                LOOKUP_IDS_SYMBOL_OF_INT found_class CLASS class
                LOOKUP_IDS_SYMBOL_OF_INT found_alignment ALIGNMEN alignment

                LPF LOG_TEXT STR_VAR filename="debug" log_level="debug" message = "Found a %found_alignment% creature of race %found_race%, general %found_general%, and class %found_class%, that should be in the chaotic axis: %SOURCE_RES% -- %name%" END
              END
          END

          PATCH_IF class = class_fairy_sirine BEGIN
            READ_BYTE 0x27b alignment
            PATCH_IF alignment != alignmen_chaotic_neutral BEGIN
              ++matches
              READ_STRREF 0x08 name ELSE "Unknown name"
              LOOKUP_IDS_SYMBOL_OF_INT found_race RACE race
              LOOKUP_IDS_SYMBOL_OF_INT found_general GENERAL general
              LOOKUP_IDS_SYMBOL_OF_INT found_class CLASS class
              LOOKUP_IDS_SYMBOL_OF_INT found_alignment ALIGNMEN alignment

              LPF LOG_TEXT STR_VAR filename="debug" log_level="debug" message = "Found a %found_alignment% creature of race %found_race%, general %found_general%, and class %found_class%, that should be Chaotic Neutral: %SOURCE_RES% -- %name%" END
            END
          END

          PATCH_IF class = class_fairy_nymph BEGIN
            READ_BYTE 0x27b alignment
            PATCH_IF alignment != alignmen_neutral_good AND
                     alignment != alignmen_chaotic_good
            BEGIN
              ++matches
              READ_STRREF 0x08 name ELSE "Unknown name"
              LOOKUP_IDS_SYMBOL_OF_INT found_race RACE race
              LOOKUP_IDS_SYMBOL_OF_INT found_general GENERAL general
              LOOKUP_IDS_SYMBOL_OF_INT found_class CLASS class
              LOOKUP_IDS_SYMBOL_OF_INT found_alignment ALIGNMEN alignment

              LPF LOG_TEXT STR_VAR filename="debug" log_level="debug" message = "Found a %found_alignment% creature of race %found_race%, general %found_general%, and class %found_class%, that should be Neutral Good or Chaotic Good: %SOURCE_RES% -- %name%" END
            END
          END

        END

        PATCH_IF race = race_mephit OR
                 race = race_salamander
        BEGIN
            READ_BYTE 0x27b alignment
            PATCH_IF alignment = alignmen_chaotic_good OR
                     alignment = alignmen_lawful_good  OR
                     alignment = alignmen_neutral_good

            BEGIN
                ++matches
                READ_STRREF 0x08 name ELSE "Unknown name"
                LOOKUP_IDS_SYMBOL_OF_INT found_race RACE race
                LOOKUP_IDS_SYMBOL_OF_INT found_general GENERAL general
                LOOKUP_IDS_SYMBOL_OF_INT found_class CLASS class
                LOOKUP_IDS_SYMBOL_OF_INT found_alignment ALIGNMEN alignment

                LPF LOG_TEXT STR_VAR filename="debug" log_level="debug" message = "Found a %found_alignment% creature of race %found_race%, general %found_general%, and class %found_class%, that should be not good: %SOURCE_RES% -- %name%" END
            END

        END

        PATCH_IF class  != class_innocent            AND
                 class  != class_druid               AND
                (general = general_undead            OR
                 race    = race_demonic              OR
                 race    = race_antisolar            OR
                 race    = race_beholder             OR
                 race    = race_mind_flayer          OR
                 race    = race_darkplanetar         OR
                 race    = race_drider               OR
                 race    = race_ettercap             OR
                 race    = race_kuo_toa              OR
                 race    = race_lich                 OR
                 race    = race_demilich             OR
                 race    = race_rakshasa             OR
                 race    = race_sahuagin             OR
                 race    = race_shadow               OR
                (race    = race_specter AND general = general_undead) OR
                (race    = race_spectral_undead AND general = general_undead) OR
                 race    = race_troll                OR
                 race    = race_will_o_wisp          OR
                 race    = race_vampire              OR
                 race    = race_vampyre              OR
                 race    = race_wraith               OR
                 race    = race_ogre                 OR
                 race    = race_chimera              OR
                 race    = race_goblin               OR
                 race    = race_hobgoblin            OR
                 race    = race_kobold               OR
                 race    = race_yuanti               OR
                 race    = race_skeleton             OR
                 race    = race_gnoll                OR
                 race    = race_ghoul                OR
                 race    = race_orc                  OR
                 race    = race_umberhulk            OR
                 race    = race_zombie               OR
                 race    = race_bugbear              OR
                 race    = race_minotaur             OR
                 race    = race_harpy                OR
              //   race    = race_yeti                 OR // only in future editions
                 race    = race_ettin                OR
                 class   = class_worg                OR
                 class   = class_wolf_winter         OR
                 (race = race_spider AND class = class_spider_wraith) AND // wraith undead spiders are evil
                 class   = class_genie_efreeti       OR // all these genies are evil
                 class   = class_genie_noble_efreeti OR
                 class   = class_genie_dao           OR
                (race    = race_lycanthrope AND class = class_wolfwere) OR // wolfweres are evil
                (race    = race_dragon AND class != class_silver_dragon) // silver dragons are LG
                )
        BEGIN

            READ_BYTE 0x27b alignment
            PATCH_IF alignment != alignmen_chaotic_evil AND
                     alignment != alignmen_lawful_evil  AND
                     alignment != alignmen_neutral_evil
            BEGIN
                ++matches
                READ_STRREF 0x08 name ELSE "Unknown name"
                LOOKUP_IDS_SYMBOL_OF_INT found_race RACE race
                LOOKUP_IDS_SYMBOL_OF_INT found_general GENERAL general
                LOOKUP_IDS_SYMBOL_OF_INT found_class CLASS class
                LOOKUP_IDS_SYMBOL_OF_INT found_alignment ALIGNMEN alignment

                LPF LOG_TEXT STR_VAR filename="debug" log_level="debug" message = "Found a %found_alignment% creature of race %found_race%, general %found_general%, and class %found_class%, that should be evil: %SOURCE_RES% -- %name%" END
            END

        END

        ELSE

        PATCH_IF race  = race_planetar      OR
                 race  = race_solar         OR
                (race  = race_genie         AND
                (class = class_genie_djinni OR
                 class = class_genie_noble_djinni))
        BEGIN
            READ_BYTE 0x27b alignment
            PATCH_IF alignment != alignmen_chaotic_good AND
                     alignment != alignmen_lawful_good  AND
                     alignment != alignmen_neutral_good
            BEGIN
                ++matches
                READ_STRREF 0x08 name ELSE "Unknown name"
                LOOKUP_IDS_SYMBOL_OF_INT found_race RACE race
                LOOKUP_IDS_SYMBOL_OF_INT found_general GENERAL general
                LOOKUP_IDS_SYMBOL_OF_INT found_class CLASS class
                LOOKUP_IDS_SYMBOL_OF_INT found_alignment ALIGNMEN alignment

                LPF LOG_TEXT STR_VAR filename="debug" log_level="debug" message = "Found a %found_alignment% creature of race %found_race%, general %found_general%, and class %found_class%, that should be good: %SOURCE_RES% -- %name%" END
            END
        END

        ELSE

        PATCH_IF (general = general_animal AND class != class_worg AND class != class_wolf_winter) OR
                  general = general_plant        OR
                  race    = race_elemental       OR
                  race    = race_ankheg          OR
                 (race    = race_genie AND (class < class_genie_djinni AND class > class_genie_noble_efreeti)) OR
                  race    = race_basilisk        OR
                  race    = race_carrion_crawler OR
                  race    = race_beetle          OR
                 (race    = race_spider AND class != class_spider_wraith AND general != general_humanoid) OR
                  race    = race_hook_horror     OR
                  race    = race_myconid         OR
                  race    = race_golem           OR
                  race    = race_mimic           OR
                  race    = race_otyugh          OR
                  race    = race_shambling_mound OR
               //   race    = race_statue          OR // probably should just be unaligned
                  race    = race_shrieker        OR
                  race    = race_slime           OR
                  race    = race_treant          OR
                  race    = race_yeti            OR // in early editions
                  race    = race_wyvern          OR
                  race    = race_lizardman       OR
     //           ((race    = race_mist OR class = class_mist) AND general != general_undead) OR
                 (race    = race_salamander AND class != class_salamander_frost)
        BEGIN

          READ_BYTE 0x27b alignment
          PATCH_IF alignment != alignmen_chaotic_neutral AND
                   alignment != alignmen_lawful_neutral  AND
                   alignment != alignmen_neutral

          BEGIN
              ++matches
              READ_STRREF 0x08 name ELSE "Unknown name"
              LOOKUP_IDS_SYMBOL_OF_INT found_race RACE race
              LOOKUP_IDS_SYMBOL_OF_INT found_general GENERAL general
              LOOKUP_IDS_SYMBOL_OF_INT found_class CLASS class
              LOOKUP_IDS_SYMBOL_OF_INT found_alignment ALIGNMEN alignment

              LPF LOG_TEXT STR_VAR filename="debug" log_level="debug" message = "Found a %found_alignment% creature of race %found_race%, general %found_general%, and class %found_class%, that should be neutral: %SOURCE_RES% -- %name%" END
            END
        END

      END

    END

  BUT_ONLY

  PRINT "[DEBUG][INFO]: Checking finished, found %matches% matches"
  LAF LOG_TEXT INT_VAR predicate_stdout=FALSE STR_VAR flog_preamble="" filename="debug" message="-- END OF OVERSIGHT++ ALIGNMENT CHECKING --" END

END