ACTION_IF is_bg2ee_or_eet BEGIN

  COPY_EXISTING ~figure01.itm~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@60010) END
    LPF ALTER_EFFECT INT_VAR match_duration = 24 duration = 60 END

  COPY_EXISTING ~shakti1.itm~ ~override~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter1 = 3 END
    LPF ADD_EQUIPPED_EFF INT_VAR p2=1 STR_VAR effects = ~op=1,p1=2;op=301,p1=1~ END

END
