COPY_EXISTING ~SW1H67.ITM~ ~override~
    LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6120) END
    LPF ALTER_EFFECT INT_VAR check_globals=0 match_opcode=12 dicesize=4 dicenumber=5 parameter1=1 savebonus="-2" probability1=14 END
    LPF ADD_EQUIPPED_EFF INT_VAR p1 = 40 STR_VAR effects = ~op=29~ END
    LPF GET_DMG_TYPE STR_VAR type = ~electricity~ RET electricity = result END
    LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=12,tmg=9,p2=%electricity%,dsize=3,dnum=1~ END
BUT_ONLY
