ACTION_IF (VARIABLE_IS_SET ~zs_comp_1312~) BEGIN
  FAIL ~Script already included: zs_comp_1312~
END ELSE BEGIN
  OUTER_SET ~zs_comp_1312~ = 1
END

ACTION_IF is_bg2ee_or_eet BEGIN

  COPY ~%MOD_FOLDER%/items/skullcrusher~ ~override~
  COPY_EXISTING ~blun18.itm~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6160) END
    LPF ALTER_EFFECT INT_VAR check_globals = 0 match_opcode = 177 STR_VAR resource = ~zstwbl02~ END

END
