ADD_PROJECTILE ~%MOD_FOLDER%/pro/ZSTWRDPJ.pro~
COPY ~%MOD_FOLDER%/spells/divine/divine_words~ ~override~ // will turn to code eventually

// CREATE EFFs to target to use in opcode 177 that target alignment correctly and show the expected visual effect
DEFINE_PATCH_MACRO patch_file BEGIN
  LPF ALTER_EFF_FILE INT_VAR opcode = 146 parameter2 = 1 STR_VAR resource = "zstwrd08" END
END
LAF CREATE_TG_EFF STR_VAR filename = "zstwrd10" END

DEFINE_PATCH_MACRO patch_file BEGIN
  LPF ALTER_EFF_FILE INT_VAR opcode = 146 parameter2 = 1 STR_VAR resource = "zstwrd09" END
END
LAF CREATE_TG_EFF STR_VAR filename = "zstwrd11" END

COPY_EXISTING ~sppr710.spl~ ~override~
  LPF ALTER_SPELL INT_VAR desc=RESOLVE_STR_REF(@8650) END
  LPF ALTER_HEADER INT_VAR projectile = %ZSTWRDPJ% END
  LPF DELETE_EFFECT_EX STR_VAR match_opcode_ex = "(o_opcode != 215)" END
  LPF RGB INT_VAR red = 128 green = 128 blue = 128 RET color = result END
  LPF ADD_SPL_TGTEFF INT_VAR rd=2 tmg=0 pwr=7 STR_VAR effects = ~op=326,p2=104,p1=%race_demilich%,res=zstwrd07;op=318,p2=104,p1=%race_demilich%,res=%SOURCE_RES%;op=177,p2=3,p1=%general_undead%,res=zstwrd05;op=318,p2=1,res=%SOURCE_RES%;op=177,p2=8,p1=%alignmen_mask_evil%,res=zstwrd05;op=177,p2=8,p1=%alignmen_mask_neutral%,res=zstwrd05;op=177,p2=8,p1=%alignmen_mask_evil%,res=zstwrd10;op=177,p2=8,p1=%alignmen_mask_neutral%,res=zstwrd10~ END

ACTION_IF has_eefixpack BEGIN
  COPY_EXISTING ~zstwrd00.spl~ ~override~
    LPF CLONE_EFFECT
      INT_VAR
        match_opcode = 13
        opcode = 318
        parameter1 = splstate_fp_death_immunity
        timing = 0
        parameter2 = 115
      STR_VAR
        insert = "above"
    END
END

COPY_EXISTING ~zstwrd03.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF(@8654) END

COPY_EXISTING ~zstwrd02.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF(@8653) END

COPY_EXISTING ~zstwrd01.spl~ ~override~
  FOR (turns = 1; turns <= 4; ++turns) BEGIN
    LPF ALTER_EFFECT INT_VAR match_opcode=139 match_parameter1=turns parameter1=RESOLVE_STR_REF(@8652) END
  END


COPY_EXISTING ~sppr715.spl~ ~override~
  LPF ALTER_SPELL INT_VAR desc=RESOLVE_STR_REF(@8651) END
  LPF ALTER_HEADER INT_VAR projectile = %ZSTWRDPJ% END
  LPF DELETE_EFFECT_EX STR_VAR match_opcode_ex = "(o_opcode != 215)" END
  LPF ADD_SPL_TGTEFF INT_VAR rd=2 tmg=0 pwr=7 STR_VAR effects = ~op=177,p2=8,p1=%alignmen_mask_good%,res=zstwrd05;op=177,p2=8,p1=%alignmen_mask_neutral%,res=zstwrd05;op=177,p2=8,p1=%alignmen_mask_good%,res=zstwrd11;op=177,p2=8,p1=%alignmen_mask_neutral%,res=zstwrd11~ END
