COPY_EXISTING ~sppr111.spl~ ~override~
  LPF ALTER_SPELL INT_VAR desc=RESOLVE_STR_REF(@6200) END
  LPF ~CD_TRIM-O-MATIC~ INT_VAR level_cap = 1 END
  PATCH_FOR_EACH op IN 27 28 29 30 31 86 87 88 89 BEGIN
    LPF ALTER_EFFECT INT_VAR match_opcode = op parameter1 = 20 END
  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 89 opcode = 0 parameter1 = 2 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 89 opcode = 173 END

  LPF ALTER_EFFECT_EX INT_VAR duration=12 STR_VAR match_duration_ex = "(o_duration > 6)" END

  // extend duration afterwards
  LPF ~CD_EXTEND-O-MATIC~ INT_VAR dur_special=1 step_dur=6 level_cap=(is_iwdee ? 30 : 20) END