ACTION_IF NOT is_iwdee BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~bdring03.itm~ BEGIN

    COPY_EXISTING ~bdring03.itm~ ~override~
      LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@7830) END
      LPF CLONE_EFFECT INT_VAR match_opcode=219 opcode = 178 special=2 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 178 opcode = 179 END

  END ELSE BEGIN
    LAF LOG_TEXT INT_VAR predicate_stdout = (NOT group_component) STR_VAR log_level="abort" message = "Ring of the Crusade not found. -- Harmless unless it's BGEE with SoD or EET." END
  END

END
