ACTION_IF (VARIABLE_IS_SET ~zs_comp_466~) BEGIN
  FAIL ~Script already included: zs_comp_466~
END ELSE BEGIN
  OUTER_SET ~zs_comp_466~ = 1
END

COPY_EXISTING ~SPPR701.SPL~ ~override~
  LPF ALTER_SPELL INT_VAR name = RESOLVE_STR_REF(@7551) desc=RESOLVE_STR_REF(@7550) END
  LPF ALTER_EFFECT_EX INT_VAR match_opcode = 201 STR_VAR parameter1_ex = "(THIS * 2)" END
  LPF CLONE_EFFECT INT_VAR match_opcode=201 match_parameter2=2 parameter2=0 parameter1=4 opcode=325 END
