ACTION_IF is_bg2ee_or_eet BEGIN

  DEFINE_PATCH_MACRO patch_file BEGIN LPF ALTER_EFF_FILE INT_VAR opcode = 1 parameter1 = 1 END END
  LAF CREATE_EQ_EFF STR_VAR filename="zstwras1" END // extra apr

  DEFINE_PATCH_MACRO patch_file BEGIN LPF ALTER_EFF_FILE INT_VAR opcode = 9 parameter1 = 6 parameter2 = 2359317 END END
  LAF CREATE_EQ_EFF STR_VAR filename="zstwras2" END // color pulse

  COPY_EXISTING ~sw1h33.itm~  ~override~
                ~sw1h33a.itm~ ~override~
                ~sw1h33c.itm~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6700) END

  COPY_EXISTING ~sw1h33.itm~  ~override~
                ~sw1h33c.itm~ ~override~
    LPF ALTER_HEADER INT_VAR speed = 1 to_hit=4 END
    LPF ALTER_EFFECT INT_VAR check_globals = 0 header_type = 3 match_opcode = 67 duration = 60 END
    LPF ALTER_EFFECT INT_VAR check_globals = 0 header_type = 3 match_opcode = 122 duration = 60 END
    LPF ADD_EQUIPPED_EFF INT_VAR p1=1 STR_VAR effects = ~op=0;op=0,p2=4;op=0,p2=8~ END
    LPF ADD_EQUIPPED_EFF INT_VAR p2=9 STR_VAR effects = ~op=177,p1=%kit_blade%,res=zstwras1;op=177,p1=%kit_blade%,res=zstwras2;op=177,p1=%kit_shadowdancer%,res=zstwras1;op=177,p1=%kit_shadowdancer%,res=zstwras2;op=177,p1=%kit_swashbuckler%,res=zstwras1;op=177,p1=%kit_swashbuckler%,res=zstwras2~ END

    PATCH_IF has_zs_shadowdancer_overhaul BEGIN
      LPF ADD_EQUIPPED_EFF INT_VAR p2=9 STR_VAR effects = ~op=177,p1=%kit_zs_shadowdancer%,res=zstwras1;op=177,p1=%kit_zs_shadowdancer%,res=zstwras2~ END
    END

END
