ACTION_IF (VARIABLE_IS_SET ~zs_comp_1311~) BEGIN
  FAIL ~Script already included: zs_comp_1311~
END ELSE BEGIN
  OUTER_SET ~zs_comp_1311~ = 1
END

ACTION_IF NOT is_iwdee BEGIN

  COPY ~%MOD_FOLDER%/items/krotan~ ~override~
  COPY_EXISTING ~BLUN11.ITM~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6150) END
    LPF ADD_ON_HIT_EFF STR_VAR effects = ~op=177,p1=1,p2=3,tmg=1,rd=2,res=ZSTWBL01~ END
    
END
