ACTION_IF zst_443_death BEGIN

    COPY ~%MOD_FOLDER%/spells/common/symbol_death~ ~override~

    ACTION_IF NOT has_eefixpack BEGIN
        OUTER_SPRINT effects_sdeath ~op=326,p2=144,res=zstwsdh0;op=326,p2=145,res=zstwsdh1~
    END ELSE BEGIN
        OUTER_SPRINT effects_sdeath ~op=318,p2=110,p1=%splstate_fp_death_immunity%,res=%SOURCE_RES%;op=318,p2=55,p1=0,res=%SOURCE_RES%;op=326,p2=144,res=zstwsdh0;op=326,p2=145,res=zstwsdh1~
    END

    DEFINE_PATCH_MACRO symbol_death_patch BEGIN
        LPF DELETE_EFFECT INT_VAR check_globals = 0 END
        LPF ADD_SPL_TGTEFF INT_VAR pwr=power p1=60 STR_VAR effects=~%effects_sdeath%~ END
    END

    COPY_EXISTING ~sppr719.spl~ ~override~
        LPF ALTER_SPELL INT_VAR desc=RESOLVE_STR_REF(@5190) END
        SET power = 7
        LPM symbol_death_patch
    IF_EXISTS

    OUTER_SET new_description = RESOLVE_STR_REF(@5200)
    COPY_EXISTING ~spwi817.spl~ ~override~
                  ~spwi897.spl~ ~override~
        LPF ALTER_SPELL INT_VAR desc=new_description END
        SET power = 8
        LPM symbol_death_patch
    IF_EXISTS

    COPY_EXISTING ~scrlao.itm~ ~override~
        LPF ALTER_ITEM INT_VAR id_desc=new_description END
    IF_EXISTS

    COPY_EXISTING ~scrlam.itm~ ~override~
        LPF ALTER_ITEM INT_VAR id_desc=new_description END
    IF_EXISTS

END

ACTION_IF zst_443_pain AND spell_symbol_pain > 0 BEGIN

    LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = "CLERIC_SYMBOL_PAIN" RET spell_res END
    COPY_EXISTING ~%spell_res%.spl~ ~override~
        LPF ALTER_SPELL INT_VAR desc=RESOLVE_STR_REF(@8280) END
        LPF ADD_SPL_TGTEFF STR_VAR effects=~t=99,op=332,pwr=7,p1=-10,dur=66~ END
        LPF ALTER_EFFECT INT_VAR match_duration = 660 duration = 66 END
        LPF ALTER_EFFECT INT_VAR check_globals = 0 match_savingthrow = 1 savebonus = 0 savingthrow = 0 END

END

ACTION_IF zst_443_nerf_npc_symbols BEGIN

    COPY_EXISTING ~spwi898.spl~ ~override~
                  ~spwi899.spl~ ~override~
        LPF ALTER_EFFECT INT_VAR silent=1 match_duration = 96  duration = 42 END
        LPF ALTER_EFFECT INT_VAR silent=1 match_duration = 102 duration = 42 END
        LPF ALTER_EFFECT INT_VAR silent=1 match_duration = 108 duration = 48 END
        LPF ALTER_EFFECT INT_VAR silent=1 match_duration = 112 duration = 48 END
        LPF ALTER_EFFECT INT_VAR silent=1 match_duration = 120 duration = 54 END
    BUT_ONLY IF_EXISTS

END

