ACTION_IF NOT is_iwdee BEGIN

    ACTION_IF FILE_EXISTS_IN_GAME ~bdsw2h03.itm~ BEGIN

        COPY_EXISTING ~bdsw2h03.itm~ ~override~
            PATCH_IF zst_1150_dice_twohanded_swords AND
                    (MOD_IS_INSTALLED ~ZSTweaks.tp2~ ~1150~ OR 
                    (MOD_IS_INSTALLED "ZSTweaks.tp2" "103" AND zst_group_1150_weapon_dice))
            BEGIN

                SPRINT strref @6900
                SPRINT str @99999
                LPF WPN_DMG RET dmg = result END

                INNER_PATCH_SAVE strref ~%strref%~ BEGIN
                    REPLACE_TEXTUALLY ~\([%LNL%%MNL%%WNL%]+[ %TAB%]*%str%[ %TAB%]*:?[ %TAB%]*\)1[Dd]10[ %TAB%]?\+[ %TAB%]?[0-9][0-9]?~ ~\11d9+%dmg%~
                END

                SAY_EVALUATED 0x54 ~%strref%~

            END ELSE BEGIN
                LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6900) END
            END

        COPY_EXISTING ~bdsw2h03.spl~ ~override~
            LPF ALTER_EFFECT INT_VAR match_opcode=12 match_dicesize=4 match_parameter1=0 dicesize=5 parameter1=2 special=1024 END

    END ELSE BEGIN
        LAF LOG_WARNING_FAIL INT_VAR force_warn=1 predicate_stdout = (NOT group_component) STR_VAR message = "[WARN]: Sword of Ruin not found. Skipping. -- Harmless unless it's EET or SoD." END
    END

END
