ACTION_IF NOT is_bgee BEGIN

  COPY_EXISTING "spcl904.spl" ~override~
                "spcl907.spl" ~override~
    LPF ALTER_SPELL INT_VAR secondary_type=0 END
  IF_EXISTS

  COPY_EXISTING "spcl913.spl" ~override~
                "spcl914.spl" ~override~
                "spcl916.spl" ~override~
                "spcl917.spl" ~override~
    LPF ALTER_SPELL INT_VAR secondary_type=0 END
  IF_EXISTS

  COPY_EXISTING ~spwish12.spl~ ~override~
    LPF ALTER_SPELL INT_VAR secondary_type=0 END
  IF_EXISTS

END

