ACTION_IF NOT is_iwdee BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~bdbrac05.itm~ BEGIN

    COPY_EXISTING ~bdbrac05.itm~ ~override~
      LPF ALTER_ITEM INT_VAR id_name = RESOLVE_STR_REF(@7321) id_desc=RESOLVE_STR_REF(@7320) END
      LPF CLONE_EFFECT INT_VAR check_headers=0 match_opcode=177 match_parameter2=9 match_parameter1=kit_stalker parameter1=kit_bounty_hunter END
      LPF CLONE_EFFECT INT_VAR check_headers=0 match_opcode=177 match_parameter2=9 match_parameter1=kit_stalker parameter1=kit_shadowdancer END

      PATCH_IF has_zs_shadowdancer_overhaul BEGIN
        LPF CLONE_EFFECT INT_VAR check_headers=0 match_opcode=177 match_parameter2=9 match_parameter1=kit_stalker parameter1=kit_zs_shadowdancer END
      END

  END ELSE BEGIN
    LAF LOG_TEXT INT_VAR predicate_stdout = (NOT group_component) STR_VAR log_level="abort" message = "Stalker Gauntlets not found, skipping. -- Harmless unless it's EET or BGEE with SoD." END
  END

END
