ACTION_IF NOT is_iwdee BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME "bdboot03.itm" BEGIN

    COPY_EXISTING "bdboot03.itm" ~override~
      LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6920) END
      LPF ALTER_EFFECT INT_VAR match_opcode = 166 parameter1 = 10 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 177 match_parameter2 = 9 parameter1 = kit_inquisitor END

  END ELSE BEGIN
      LAF LOG_WARNING_FAIL INT_VAR force_warn=1 predicate_stdout = (NOT group_component) STR_VAR message = "[WARN]: Star-strewn boots are found. -- Harmless unless it's EET or SoD." END
  END

END
