ACTION_IF is_bg2ee_or_eet BEGIN

  COPY_EXISTING ~leat13.itm~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc = RESOLVE_STR_REF(@8425) END
    SPRINT fp_splstates ""
    PATCH_IF has_eefixpack BEGIN
      SPRINT fp_splstates "op=328,spec=1,p2=%splstate_fp_stun_immunity%;op=328,spec=1,p2=%splstate_fp_hold_immunity%;"
    END
    LPF ADD_EQUIPPED_EFF STR_VAR effects = ~%fp_splstates%op=101,p2=210;op=101,p2=109;op=101,p2=175;op=101,p2=45;op=267,p1=14043;op=267,p1=1280;op=267,p1=14102;op=169,p2=13;op=296,res=spmindat;op=296,res=spflayer;op=169,p2=55~ END

END
