ACTION_IF (VARIABLE_IS_SET ~zs_comp_501~) BEGIN
  FAIL ~Script already included: zs_comp_501~
END ELSE BEGIN
  OUTER_SET ~zs_comp_501~ = 1
END

ACTION_IF NOT is_iwdee BEGIN

  ACTION_IF NOT has_eefixpack BEGIN

    COPY_EXISTING ~SPPR508.SPL~ ~override~
      LPF LAST_VALID_HEADER RET new_header = result END
      LPF ~CD_EXTEND-O-MATIC~ INT_VAR step_dur=60 level_cap=20 END

  END ELSE BEGIN PRINT ~EET Fixpack detected, skipping Chaotic Commands component~ END

END
