ACTION_IF is_bg2ee_or_eet BEGIN

  DEFINE_PATCH_MACRO patch_file BEGIN LPF ALTER_EFF_FILE INT_VAR opcode = 12 parameter1 = 4 END END
  LAF CREATE_TG_EFF STR_VAR filename = "zstwbl01" END // humanoid attack

  COPY_EXISTING ~blun18.itm~ ~override~
    LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6160) END
    LPF ALTER_EFFECT INT_VAR check_globals = 0 match_opcode = 177 STR_VAR resource = ~zstwbl02~ END

END
