ACTION_IF (VARIABLE_IS_SET ~zs_comp_1561~) BEGIN
  FAIL ~Script already included: zs_comp_1561~
END ELSE BEGIN
  OUTER_SET ~zs_comp_1561~ = 1
END

ACTION_IF is_bg2ee_or_eet BEGIN

  COPY_EXISTING "clck25.itm" ~override~
    LPF ALTER_ITEM INT_VAR id_desc=RESOLVE_STR_REF(@6820) END
    LPF ALTER_EFFECT INT_VAR check_globals = 0 match_opcode = 255 parameter1 = 30 END
    SET proficiency = (106 << 16)
    LPF ADD_EQUIPPED_EFF STR_VAR effects =~op=233,p1=1,p2=%proficiency%;op=37,p1=2~ END

END
