ACTION_IF !VARIABLE_IS_SET ZS_MARKER_FILE_EXISTS BEGIN
    OUTER_SET ZS_MARKER_FILE_EXISTS = FILE_EXISTS_IN_GAME "zssetup.rp"
END

ACTION_IF zs_debug AND !VARIABLE_IS_SET ~zs_debug_warning~ BEGIN
    PRINT "[WARN]: W A R N I N G!!! zs_debug flag is ON. This should be off in normal installations, as it will make things slower and force more code than normal to run. Disregard if truly intended."
    OUTER_SET zs_debug_warning = 1
END

ACTION_IF zs_allow_prefixes BEGIN

    ACTION_IF !VARIABLE_IS_SET ~zs_prefixes~ AND NOT ZS_MARKER_FILE_EXISTS BEGIN

        PRINT "[INFO]: ---- STARTING PREFIXES ----"
        ACTION_IF zst_shield_std_fix BEGIN

            INCLUDE ~%MOD_FOLDER%/libs/preambles/fragments/zs_standardize_shields.tph~

        END

        ACTION_IF zst_simulacra_fix BEGIN

            PRINT "[INFO]: Fixing 2.6.6 bug that prevents finding traps and stealth for simulacra"
            COPY_EXISTING ~simulacr.spl~ ~override~
                LPF DELETE_EFFECT_EX INT_VAR match_opcode=144 STR_VAR match_parameter2_ex = ~(o_parameter2 = 14 OR o_parameter2 = 0)~ END

        END

        ACTION_IF zst_phantom_blade_dmg BEGIN

            PRINT "[INFO]: Marking Phantom's Blade extra damage as not waking up sleepers"
            COPY_EXISTING ~phanblad.eff~ ~override~
                LPF ALTER_EFF_FILE INT_VAR special = 1024 END

        END

        ACTION_IF zst_wraith_spid_undead BEGIN

            PRINT "[INFO]: Wraith Spiders should be classified as Undead"
            COPY_EXISTING ~spidwr01.cre~ ~override~
                          ~spidwr.cre~   ~override~
                          ~spidkid.cre~  ~override~
                          ~rdespiw.cre~  ~override~
                          ~ttspid.cre~   ~override~
                WRITE_BYTE 0x271 general_undead
            IF_EXISTS

            PRINT "[INFO]: Parsing game data to find mod-added wraith spiders that aren't undead..."
            OUTER_SET wraith_spiders_found = 0
            COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
                SET general = BYTE_AT(0x271)
                SET race    = BYTE_AT(0x272)
                SET class   = BYTE_AT(0x273)
                PATCH_IF race = race_spider AND class = class_spider_wraith AND general != general_undead BEGIN
                    WRITE_BYTE 0x271 general_undead
                    ++wraith_spiders_found
                END
            BUT_ONLY

            ACTION_IF wraith_spiders_found > 0 BEGIN PRINT "[INFO]: Patched %wraith_spiders_found% mod-added wraith spiders!" END
            ELSE BEGIN PRINT "[INFO]: No mod-added wraith spiders found, cool!" END

        END

        ACTION_IF zst_eefp_unfix_blackrazor_bbod BEGIN

            ACTION_IF has_eefixpack AND (FILE_EXISTS_IN_GAME ~cdmiscbc.spl~ OR FILE_EXISTS_IN_GAME ~cdblkbld.spl~) BEGIN
                PRINT "[INFO]: Fixing faulty Blackrazor/BBoD Unfix in Fixpack strengthening target instead of self"
                COPY_EXISTING ~cdmiscbc.spl~ ~override~
                              ~cdblkbld.spl~ ~override~
                    LPF ALTER_EFFECT INT_VAR silent=1 match_target=1 target=9 END
                BUT_ONLY IF_EXISTS
            END

        END

        ACTION_IF zst_eefp_exaltation_bug BEGIN

            ACTION_IF has_eefixpack BEGIN
                COPY_EXISTING ~ohtyr1.spl~ ~override~
                    LPF CLONE_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 43 opcode = 318 STR_VAR insert = "first" END
                    LPF DELETE_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 43 END
                    LPF ALTER_EFFECT INT_VAR match_opcode = 318 match_parameter2 = 43 opcode = 324 END

            END

        END

        ACTION_IF NOT has_eefixpack BEGIN

            ACTION_IF zst_shadow_twin_duration BEGIN

                ACTION_IF FILE_EXISTS_IN_GAME ~spcl936.spl~ AND NOT has_zs_shadowdancer_overhaul BEGIN

                    PRINT "[INFO]: Extending duration of Shadow Twin to the intended 2 turns"
                    COPY_EXISTING ~spcl936.spl~ ~override~ // Shadow Twin, fixed wrong duration
                        LPF ALTER_EFFECT INT_VAR silent=1 match_duration = 60 duration = 120 END

                END

            END

            ACTION_IF zst_sd_thac0_bug BEGIN

                PRINT "[INFO]: Setting the right THAC0 penalty to the Shadowdancer kit for using weapons without proficiency"
                COPY_EXISTING ~clswpbon.2da~ ~override~
                    READ_2DA_ENTRIES_NOW clswpbon 1
                    FOR (row = 3; row < clswpbon; ++row) BEGIN
                        READ_2DA_ENTRY_FORMER clswpbon row 0 label
                        PATCH_IF (~%label%~ STR_EQ ~shadowdancer~) BEGIN
                            SET_2DA_ENTRY_LATER clswpbon_out row 3 3
                            SET row = clswpbon
                        END
                    END
                    SET_2DA_ENTRIES_NOW clswpbon_out 1

            END

        END

        ACTION_IF is_iwdee BEGIN

            ACTION_IF zst_bonecir BEGIN

                ACTION_IF NOT has_eefixpack BEGIN

                    PRINT ~[INFO]: Fixing broken #bonecir.spl~
                    COPY_EXISTING ~#bonecir.spl~ ~override~
                        WRITE_ASCII 0x0 "SPL " (4)

                END

            END

            ACTION_IF zst_drider BEGIN

                ACTION_IF has_willowisp_driders BEGIN
                    PRINT "[INFO]: Setting Lava's drider in Will O' Wisp to Drider race-wise"
                    COPY_EXISTING ~l0drider.cre~ ~override~
                        LPF ALTER_CRE INT_VAR race = race_drider END
                END

            END

            ACTION_IF zst_chimeras BEGIN

                PRINT "[INFO]: Setting Lava's chimeras to the race of chimera"
                    COPY_EXISTING ~l#kuchim.cre~ ~override~
                        LPF ALTER_CRE INT_VAR race = race_chimera END

            END

        END

        ACTION_IF NOT is_iwdee BEGIN

            PRINT "[INFO]: Fixing Seeking Sword's incorrect casting speed at level 20"
            COPY_EXISTING ~spcl731.spl~ ~override~
                LPF ALTER_HEADER INT_VAR speed = 5 END

            ACTION_IF NOT has_eefixpack BEGIN

                ACTION_IF zst_phantom_chaotic_dur BEGIN

                    PRINT ~[INFO]: Fixing scaling of Phantom's Blade and Chaotic Command's duration~
                    COPY_EXISTING ~spwi518.spl~ ~override~
                        LPF ~CD_EXTEND-O-MATIC~ INT_VAR dur_special = 1 step_dur=6 level_cap=20 END
                    COPY_EXISTING ~sppr508.spl~ ~override~
                        LPF ~CD_EXTEND-O-MATIC~ INT_VAR dur_special = 1 step_dur=60 level_cap=20 END

                END

                ACTION_IF zst_nish_hake_race BEGIN

                    PRINT ~[INFO]: Fixing Hakeashar and Nishruu being identified as ogre mages class-wise~
                    COPY_EXISTING "nishrusu.cre" "override"
                                  "haksu.cre"    "override"
                        WRITE_BYTE 0x271 general_monster
                        WRITE_BYTE 0x272 race_mist
                        WRITE_BYTE 0x273 class_mist

                END

            END

        END

        ACTION_IF is_bg2ee_or_eet BEGIN

            ACTION_IF zst_dancing_swords BEGIN

                COPY_EXISTING ~sword01.cre~ ~override~
                              ~sword02.cre~ ~override~
                    WRITE_BYTE 0x273 class_long_sword
                IF_EXISTS

            END

            ACTION_IF zst_genie_races BEGIN

                PRINT "[INFO]: Making the dao genies in Trademeet Dao instead of Djinni race-wise, as all evidence suggests it's what they are"
                COPY_EXISTING ~trgeni01.cre~ ~override~
                              ~trgeni02.cre~ ~override~
                              ~trgeni03.cre~ ~override~
                    WRITE_BYTE 0x273 class_genie_dao

                PRINT "[INFO]: Making the enslaved djinni in hell tagged as noble djinni instead of noble efreeti"
                COPY_EXISTING ~hellgen.cre~ ~override~
                    WRITE_BYTE 0x273 class_genie_noble_djinni

            END

            ACTION_IF zst_firkraag_animal BEGIN

                PRINT "[INFO]: Lord Jierdan no longer classified as an animal but a monster."
                COPY_EXISTING ~firkra01.cre~ ~override~
                    WRITE_BYTE 0x271 general_monster

            END

            ACTION_IF zst_wa2plat_fix BEGIN

                PRINT "[INFO]: Balduran's Plate no longer preventing characters of level 5 or less from getting a Charisma increase"
                COPY_EXISTING ~wa2plat.itm~ ~override~
                    LPF ALTER_EFFECT INT_VAR silent = 1 check_headers=0 match_dicesize = 6 dicesize = 0 END
                BUT_ONLY

            END

            ACTION_IF zst_dryad_race BEGIN

                PRINT "[INFO]: Fixing traits in vanilla unused creature resources... in case they're used!"
                COPY_EXISTING ~dry01.cre~   ~override~
                              ~dryad01.cre~ ~override~
                              ~dryad02.cre~ ~override~
                              ~dryad03.cre~ ~override~
                    WRITE_BYTE 0x272 race_fairy

            END

            ACTION_IF zst_gas_pocket BEGIN

                COPY_EXISTING ~behgas01.cre~ ~override~
                    WRITE_BYTE 0x271 general_plant
                    WRITE_BYTE 0x272 race_none

            END

            ACTION_IF zst_solar_tags BEGIN
    
                COPY_EXISTING ~solar.cre~   ~override~
                              ~solar01.cre~ ~override~
                    WRITE_BYTE 0x272 race_solar
                    WRITE_BYTE 0x272 class_cleric_mage
            END

            ACTION_IF zst_pit_fiends BEGIN
                
                COPY_EXISTING ~dempit.cre~   ~override~
                              ~dempit01.cre~ ~override~
                              ~dempitsu.cre~ ~override~
                    WRITE_BYTE 0x273 class_imp

            END

            ACTION_IF NOT has_eefixpack BEGIN

                ACTION_IF zst_lilarcor_speed_factor BEGIN

                    PRINT "[INFO]: Fixing incorrect speed factor in Lilarcor from 8 to 7"
                    COPY_EXISTING ~sw2h14.itm~ ~override~
                        LPF ALTER_HEADER INT_VAR silent = 1 match_type = 1 speed = 7 END
                        READ_STRREF 0x54 desc
                        SPRINT str_sf @99998
                        INNER_PATCH_SAVE new_description ~%new_description%~ BEGIN
                            REPLACE_TEXTUALLY ~\([%LNL%%MNL%%WNL%]+[ %TAB%]*%str_sf%[ %TAB%]*:?[ %TAB%]*\)8~ ~\17~
                        END
                        SAY_EVALUATED 0x54 ~%desc%~

                END

                ACTION_IF zst_wakininja_animations BEGIN

                    PRINT ~[INFO]: Fixing non-standard scimitar/wakizashi/ninjato animations in vanilla weapons to allow consistent identification in the mod~
                    COPY_EXISTING ~misc9q.itm~ ~override~
                        WRITE_ASCII 0x22 "SC" #2
                    COPY_EXISTING ~sw1h66.itm~ ~override~
                        WRITE_ASCII 0x22 "SS" #2
                    COPY_EXISTING ~sw1h67.itm~ ~override~
                        WRITE_ASCII 0x22 "S1" #2
                    COPY_EXISTING ~sw1h68a.itm~ ~override~
                        WRITE_ASCII 0x22 "SC" #2

                END

                ACTION_IF zst_misaligned BEGIN

                    PRINT "[INFO]: Fixes for misaligned indexes in Quarterstaff and Dwarven Thrower"
                    COPY_EXISTING ~hamm06.itm~ ~override~
                                  ~staf01.itm~ ~override~
                        LPF FJ_SPL_ITM_REINDEX END

                END

                ACTION_IF zst_dagg24 BEGIN

                    COPY_EXISTING ~dagg24.itm~ ~override~
                        READ_LONG 0x4c itm_weight
                        PATCH_IF itm_weight = 0 BEGIN
                            PATCH_PRINT "[INFO]: Fixing dagg24.itm (Dagger +3) weight from 0 to 1"
                            LPF ALTER_ITEM INT_VAR weight = 1 END
                            SPRINT str @99990
                            READ_STRREF 0x54 desc
                            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                                REPLACE_TEXTUALLY ~\([%LNL%%MNL%%WNL%]+[ %TAB%]*%str%[ %TAB%]*:?[ %TAB%]*\)[0-9]~ ~\11~
                            END
                            SAY_EVALUATED 0x54 ~%desc%~
                        END
                    BUT_ONLY

                END

                ACTION_IF zst_shakti BEGIN

                    PRINT "[INFO]: Fixing shakti1.itm speed factor from 1 to 0 as it's a +4 sword"
                    COPY_EXISTING ~shakti1.itm~ ~override~
                        LPF ALTER_HEADER INT_VAR speed = 0 END

                END

                ACTION_IF zst_ogre_sword BEGIN

                    COPY_EXISTING ~misc4q.itm~ ~override~
                        LPF WPN_DICENUM RET dicenum = result END
                        LPF WPN_DICESIZE RET dicesize = result END
                        PATCH_IF dicesize = 4 AND dicenum = 2 BEGIN
                            PATCH_PRINT "[INFO]: Fixing misc4q.itm (The Ogre's Sword) so it uses bastard sword proficiency"
                            LPF ALTER_ITEM INT_VAR lore = 0 wpn_prof = 89 END
                            LPF ALTER_HEADER INT_VAR silent = 1 dicesize = 8 dicenumber = 1 END
                            SPRINT str @99980
                            SPRINT ls_str @99981
                            SPRINT bs_str @99982
                            READ_STRREF 0x50 desc
                            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                                REPLACE_TEXTUALLY ~\([%LNL%%MNL%%WNL%]+[ %TAB%]*%str%[ %TAB%]*:?[ %TAB%]*\)%ls_str%~ ~\1%bs_str%~
                            END
                            SAY_EVALUATED 0x50 ~%desc%~
                        END
                    BUT_ONLY

                END

                ACTION_IF zst_cutthroat_sf BEGIN

                    PRINT "[INFO]: Fixing Cutthroat +4 so it has a speed factor of 0 as expected"
                    COPY_EXISTING "sw1h28.itm" ~override~
                        LPF ALTER_HEADER INT_VAR speed = 0 END
                        READ_STRREF 0x54 desc
                        SPRINT str_sf @99998
                        INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                            REPLACE_TEXTUALLY ~\([%LNL%%MNL%%WNL%]+[ %TAB%]*%str_sf%[ %TAB%]*:?[ %TAB%]*\)[0-9]~ ~\10~
                        END
                        SAY_EVALUATED 0x54 ~%desc%~

                END

            END

            ACTION_IF zst_golem_jugg BEGIN

                PRINT "[INFO]: Standardizing Golem Juggernaut to Stone Golem class"
                COPY_EXISTING ~tomegol4.cre~ ~override~
                    WRITE_BYTE 0x273 class_golem_stone

            END

            ACTION_IF zst_greater_clay_golem BEGIN

                PRINT "[INFO]: Making Greater Clay Golem a Clay Golem class instead of Iron"
                COPY_EXISTING ~ohbgol01.cre~ ~override~
                    WRITE_BYTE 0x273 class_golem_clay

            END

            ACTION_IF zst_aesgareth_enemies BEGIN

                PRINT "[INFO]: Aesgareth enemies he fights during the card game being considered 'weapon' instead of 'humanoid', and a couple of others"
                COPY_EXISTING ~gordeck1.cre~ ~override~
                              ~gordeck2.cre~ ~override~
                              ~gordeck3.cre~ ~override~
                              ~gordeck4.cre~ ~override~
                              ~ohnavrum.cre~ ~override~
                    PATCH_IF BYTE_AT(0x271) = general_weapon BEGIN
                        WRITE_BYTE 0x271 general_humanoid
                    END
                BUT_ONLY

            END

            ACTION_IF NOT has_eefixpack BEGIN // proficiency issues

                ACTION_IF zst_thieves_wrong_profs BEGIN

                    PRINT "[INFO]: Thieves using bastard swords in BG2EE without being able to use them properly or illegally as per the rules of thieves. Replaced with short swords."
                    COPY_EXISTING ~arntra06.cre~ ~override~
                                  ~bmugg1.cre~   ~override~
                                  ~genthf01.cre~ ~override~
                                  ~pirpir05.cre~ ~override~
                        LPF IS_WEAPON_EQUIPPED INT_VAR at_slot = 1 STR_VAR weapon = ~sw1h01~ RET found END
                        PATCH_IF found BEGIN
                            REPLACE_CRE_ITEM ~sw1h07~ #0 #0 #0 ~none~ ~weapon1~ EQUIP
                        END
                    BUT_ONLY

                    PRINT "[INFO]: Cambions that are set as 'thieves' wielding bastard swords without proficiency for it. Adding large sword proficiency 1 to them"
                    COPY_EXISTING ~cambion1.cre~ ~override~
                                  ~telcam1.cre~  ~override~
                        PATCH_IF BYTE_AT(0x6e) = 0 BEGIN // if they have no proficiency in large swords
                            WRITE_BYTE 0x6f 1 // add one pip to large sword proficiency
                        END
                    BUT_ONLY

                    PRINT "[INFO]: Thieves using daggers without being proficient in them. Adding one pip to proficiency in daggers for them"
                    COPY_EXISTING ~ar18thif.cre~ ~override~
                                  ~arnman09.cre~ ~override~
                                  ~beeloo.cre~   ~override~
                                  ~bshop01.cre~  ~override~
                                  ~drim01.cre~   ~override~
                                  ~genth02.cre~  ~override~
                                  ~gentmg01.cre~ ~override~
                                  ~shth05.cre~   ~override~
                        LPF DELETE_EFFECT INT_VAR match_opcode = 233 match_parameter1 = 1 match_parameter2 = 96 END
                        LPF ADD_CRE_EFFECT INT_VAR opcode = 233 parameter1 = 1 parameter2 = 96 timing=9 target=1 END

                    PRINT "[INFO]: Thieves using short swords without being proficient in them. Adding one pip to proficiency in short swords for them"
                    COPY_EXISTING ~dshop01.cre~  ~override~
                                  ~genth01.cre~  ~override~
                                  ~gpthief1.cre~ ~override~
                                  ~irethf03.cre~ ~override~
                                  ~ishclo01.cre~ ~override~
                                  ~ishthf01.cre~ ~override~
                                  ~parthf.cre~   ~override~
                                  ~uddoor08.cre~ ~override~
                                  ~uddoor09.cre~ ~override~
                                  ~waylane.cre~  ~override~
                                  ~sarthf01.cre~ ~override~
                                  ~irethf04.cre~ ~override~
                                  ~ishthf03.cre~ ~override~
                        LPF DELETE_EFFECT INT_VAR match_opcode = 233 match_parameter1 = 1 match_parameter2 = 91 END
                        LPF ADD_CRE_EFFECT INT_VAR opcode = 233 parameter1 = 1 parameter2 = 91 timing=9 target=1 END

                    PRINT "[INFO]: Thieves using a long swords without being proficient in them. Adding one pip to proficiency in long swords"
                    COPY_EXISTING ~arntra01.cre~  ~override~
                                  ~dassin.cre~    ~override~
                                  ~arnfgt03.cre~  ~override~
                                  ~arnman10.cre~  ~override~
                                  ~arnman11.cre~  ~override~
                                  ~arntra01.cre~  ~override~
                                  ~arntra03.cre~  ~override~
                                  ~arntra05.cre~  ~override~
                                  ~arnwar01.cre~  ~override~
                                  ~flyfgt02.cre~  ~override~
                                  ~flyfgt03.cre~  ~override~
                                  ~shadth01.cre~  ~override~
                                  ~shadth02.cre~  ~override~
                                  ~stguard1.cre~  ~override~
                                  ~stguard2.cre~  ~override~
                                  ~stguard3.cre~  ~override~
                                  ~thief4.cre~    ~override~
                        LPF DELETE_EFFECT INT_VAR match_opcode = 233 match_parameter1 = 1 match_parameter2 = 90 END
                        LPF ADD_CRE_EFFECT INT_VAR opcode = 233 parameter1 = 1 parameter2 = 90 timing=9 target=1 END

                    PRINT "[INFO]: Yuan-ti using long swords without being proficient in them. Setting proficiencies to large swords to 3, as seemingly intended"
                    COPY_EXISTING ~icyuan01.cre~ ~override~
                        WRITE_BYTE 0x6e 3

                END

            END

            ACTION_IF zst_minotaur_race_fix BEGIN

                PRINT "[INFO]: Minotaurs being set to the Ogre/gnoll race instead of Minotaurs"
                COPY_EXISTING ~icmin01.cre~  ~override~
                              ~amminot.cre~  ~override~
                              ~ohbmin01.cre~ ~override~
                              ~ohbminsu.cre~ ~override~
                              ~garock.cre~   ~override~
                              ~hlmafer.cre~  ~override~
                              ~ohnghall.cre~ ~override~
                              ~rock.cre~     ~override~
                              ~slandor.cre~  ~override~
                    WRITE_BYTE 0x272 race_minotaur

            END

            ACTION_IF zst_green_dragons BEGIN

                PRINT "[INFO]: Setting green dragons to have actually the race of green dragon"
                COPY_EXISTING ~bazdra03.cre~ ~override~
                              ~fsdragon.cre~ ~override~
                    WRITE_BYTE 0x273 class_green_dragon

            END

        END

        ACTION_IF NOT has_eefixpack BEGIN

            ACTION_IF zst_water_elementals BEGIN

                PRINT "[INFO]: Setting water elementals to their proper class of elemental of water instead of nothing"
                COPY_EXISTING ~ohbwat01.cre~ ~override~
                              ~bdwe1str.cre~ ~override~
                              ~bdwe2str.cre~ ~override~
                              ~elwatg01.cre~ ~override~
                    LPF ALTER_CRE INT_VAR class=class_elemental_water END
                IF_EXISTS

            END

        END

        ACTION_IF is_bgee_or_eet BEGIN

            ACTION_IF zst_not_the_rabbits BEGIN

                PRINT "[INFO]: Fixing rabbit's lack of race. Oh noes."
                COPY_EXISTING ~rabbit.cre~   ~override~
                    LPF ALTER_CRE INT_VAR race = race_rabbit END

            END

            ACTION_IF includes_sod BEGIN

                ACTION_IF zst_drider BEGIN

                    PRINT "[INFO]: Patching SoD driders so they actually have the Drider race instead of Spider"
                    COPY_EXISTING ~bddridr1.cre~ ~override~
                                  ~bddridrf.cre~ ~override~
                                  ~bddridrm.cre~ ~override~
                        LPF ALTER_CRE INT_VAR race=race_drider END

                END

                ACTION_IF zst_albino_wyrms BEGIN

                    PRINT "[INFO]: Patching Blind Albino Wyrmlings so they actually have the Dragon race and Silver Dragon class instead of Wyvern for both (I smell copy paste, BeamDog!)"
                    COPY_EXISTING ~bdwyrml1.cre~ ~override~
                                  ~bdwyrmli.cre~ ~override~
                        LPF ALTER_CRE INT_VAR race=race_dragon class=class_silver_dragon END

                END

            END

            ACTION_IF zst_korax_race BEGIN

                PRINT "[INFO]: Patching Korax the Ghoul so it has the race of Ghoul instead of Revenant/Mummy"
                COPY_EXISTING ~korax.cre~ ~override~
                    LPF ALTER_CRE INT_VAR race = race_ghoul END

            END

            ACTION_IF NOT has_eefixpack BEGIN

                ACTION_IF zst_riggilo BEGIN

                    PRINT "[INFO]: Fixing Riggilo having 4 pips in big swords but none in small swords while being forced to use small swords. Setting him to have 1 pip in small swords too."
                    COPY_EXISTING ~riggilo.cre~ ~override~
                        PATCH_IF BYTE_AT(0x6e) = 0 BEGIN
                            WRITE_BYTE 0x6f 1
                        END
                    BUT_ONLY

                END

            END

        END

        ACTION_IF NOT has_eefixpack BEGIN

            ACTION_IF zst_shadows_spells_bug BEGIN

                ACTION_IF is_bgee_bg2ee_or_eet BEGIN
                    PRINT "[INFO]: Removing unused spell selection from shadow creatures that can be exploited by the player with summons"
                END

                ACTION_IF is_bgee_or_eet BEGIN

                    COPY_EXISTING ~bdwrai01.cre~ ~override~ // wraith
                                  ~bdwrait1.cre~ ~override~ // wraith
                                  ~bpshadow.cre~ ~override~ // shadow
                                  ~bpwrai01.cre~ ~override~ // wraith
                                  ~daitel.cre~   ~override~ // ghost
                                  ~mistpo01.cre~ ~override~ // poison mist
                                  ~mistposu.cre~ ~override~ // poison mist
                                  ~shadfi02.cre~ ~override~ // devil shade
                                  ~shadowsu.cre~ ~override~ // shadow
                                  ~slaysh01.cre~ ~override~ // slayer shadow
                        REMOVE_MEMORIZED_SPELL ~spwi112~ ~spwi212~ ~spwi304~ ~spwi306~ ~spwi308~ ~spwi402~ ~spwi415~ ~spwi501~ ~spwi502~ ~spwi504~ ~spwi505~ ~spwi508~ ~spwi601~ ~spwi602~ ~spwi604~
                        REMOVE_KNOWN_SPELL ~spwi112~ ~spwi212~ ~spwi304~ ~spwi306~ ~spwi308~ ~spwi402~ ~spwi415~ ~spwi501~ ~spwi502~ ~spwi504~ ~spwi505~ ~spwi508~ ~spwi601~ ~spwi602~ ~spwi604~
                    BUT_ONLY IF_EXISTS

                END ELSE ACTION_IF is_bg2ee_or_eet BEGIN // bg2ee

                    COPY_EXISTING ~chwraith.cre~ ~override~ // child spirit
                                  ~firwra01.cre~ ~override~ // greater wraith
                                  ~fsghos.cre~   ~override~ // ghost
                                  ~fsghos2.cre~  ~override~ // ghost
                                  ~gormisti.cre~ ~override~ // ice mist
                                  ~gormistp.cre~ ~override~ // poison mist
                                  ~hgmis01.cre~  ~override~ // vampiric wraith
                                  ~hgmis02.cre~  ~override~ // swamp horror
                                  ~hgwra01.cre~  ~override~ // gorion (casts all spells via forcespell)
                                  ~hgwra02.cre~  ~override~ // devil shade
                                  ~hgwra03.cre~  ~override~ // devil shade
                                  ~kshadow.cre~  ~override~ // shadow
                                  ~mistcd01.cre~ ~override~ // crimson death
                                  ~mistho01.cre~ ~override~ // mist horror
                                  ~mistpo01.cre~ ~override~ // poison mist
                                  ~mistposu.cre~ ~override~ // poison mist
                                  ~mistva01.cre~ ~override~ // vampiric mist
                                  ~mistwa01.cre~ ~override~ // wandering horror
                                  ~ohhburic.cre~ ~override~ // burich
                                  ~ohhshad.cre~  ~override~ // shadow
                                  ~ohhshfi1.cre~ ~override~ // shadow fiend
                                  ~ohhshfi2.cre~ ~override~ // devil shade
                                  ~rngsha.cre~   ~override~ // shadow
                                  ~rngsha01.cre~ ~override~ // shadow
                                  ~rngsha02.cre~ ~override~ // shadow patrick - knows cure medium wounds and has generic priest script to use it, but doesn't have it memorized
                                  ~rngsha03.cre~ ~override~ // shadow
                                  ~rngsha04.cre~ ~override~ // shadow jailor
                                  ~rngsha2d.cre~ ~override~ // shadow patrick
                                  ~sarspir.cre~  ~override~ // prison spirit
                                  ~sdshadfi.cre~ ~override~ // shadow fiend
                                  ~sdshadow.cre~ ~override~ // shadow
                                  ~sewsha01.cre~ ~override~ // shadow fiend
                                  ~sewsha02.cre~ ~override~ // shadow fiend
                                  ~sewsha03.cre~ ~override~ // shadow
                                  ~shadfi01.cre~ ~override~ // shadow fiend
                                  ~shadfi02.cre~ ~override~ // devil shade
                                  ~shadow01.cre~ ~override~ // shadow
                                  ~shadowsu.cre~ ~override~ // shadow
                                  ~slaysh01.cre~ ~override~ // slayer shadow
                                  ~spectr01.cre~ ~override~ // specter
                                  ~spellh01.cre~ ~override~ // spellhaunt
                                  //~tanwiz1.cre~  ~override~ // vellin dahn
                                  ~telslav.cre~  ~override~ // slave wraith
                                  ~telwrai.cre~  ~override~ // demon wraith
                                  ~uhcreat.cre~  ~override~ // shadow
                                  ~wraith01.cre~ ~override~ // wraith
                                  ~wrashi01.cre~ ~override~ // shimmering wraith
                        REMOVE_MEMORIZED_SPELL ~spwi112~ ~spwi212~ ~spwi304~ ~spwi306~ ~spwi308~ ~spwi402~ ~spwi415~ ~spwi501~ ~spwi502~ ~spwi504~ ~spwi505~ ~spwi508~ ~spwi601~ ~spwi602~ ~spwi604~
                        REMOVE_KNOWN_SPELL ~spwi112~ ~spwi212~ ~spwi304~ ~spwi306~ ~spwi308~ ~spwi402~ ~spwi415~ ~spwi501~ ~spwi502~ ~spwi504~ ~spwi505~ ~spwi508~ ~spwi601~ ~spwi602~ ~spwi604~
                    BUT_ONLY IF_EXISTS

                END

            END

        END

        ACTION_IF zst_invistalkers_race BEGIN

            PRINT "[INFO]: Setting invisible stalker enemies as elementals of the Elemental Plane of Air instead of spectres/human"
            COPY_EXISTING ~stalke.cre~   ~override~
                          ~senstalk.cre~ ~override~
                          ~gorstalk.cre~ ~override~
                WRITE_BYTE 0x272 race_elemental
                WRITE_BYTE 0x273 class_elemental_air
            IF_EXISTS

        END

        ACTION_IF zst_gender_fix BEGIN

            DEFINE_PATCH_MACRO fix_gender BEGIN
                SET gender = BYTE_AT(0x275)
                PATCH_IF gender = gender_male OR gender = gender_female BEGIN
                    ++matches
                    WRITE_BYTE 0x275 gender_niether

                    PATCH_IF zs_debug BEGIN
                        READ_STRREF 0x8 name ELSE "unknown"
                        PATCH_IF gender=gender_male BEGIN SPRINT gender "male" END ELSE BEGIN SPRINT gender "female" END
                        LOOKUP_IDS_SYMBOL_OF_INT race_str race race
                        LOOKUP_IDS_SYMBOL_OF_INT general_str general general
                        LPF LOG_TEXT STR_VAR log_level="debug" filename="debug" message="Patched likely genderless/sexless creature (%SOURCE_RES% - %name%) of race %race_str% and general %general_str% actually marked as %gender%" END
                    END

                END
            END

            PRINT "[INFO]: Setting many types of sexless creatures as 'niether'-gendered if they're set to male or female so it doesn't intrude with opcodes that target male/female"
            ACTION_IF zs_debug BEGIN
                LAF LOG_TEXT STR_VAR filename="debug" log_level="debug" message = "-- START OF GENDER CREATURE PATCHING --" END
            END

            OUTER_SET matches = 0
            COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
                SET general = BYTE_AT(0x271)
                SET race    = BYTE_AT(0x272)
                SET class   = BYTE_AT(0x273)
                PATCH_IF race    = race_golem           OR
                         race    = race_treant          OR
                         race    = race_demonic         OR
                         race    = race_mind_flayer     OR
                         race    = race_mist            OR
                         race    = race_planetar        OR
                         race    = race_darkplanetar    OR
                         race    = race_solar           OR
                         race    = race_antisolar       OR
                         race    = race_beholder        OR
                         race    = race_genie           OR
                         race    = race_slime           OR
                         race    = race_mimic           OR
                         race    = race_doppleganger    OR
                         race    = race_myconid         OR
                         race    = race_shadow          OR
                         race    = race_wraith          OR
                         race    = race_specter         OR
                         race    = race_spectral_undead OR
                         race    = race_elemental       OR
                         race    = race_shambling_mound OR
                         race    = race_shrieker        OR
                         race    = race_will_o_wisp     OR
                         race    = race_otyugh          OR
                         general = general_weapon       OR
                         general = general_plant
                BEGIN

                    LPM fix_gender

                END ELSE PATCH_IF race = race_statue BEGIN

                    LPF IS_BIT_SET INT_VAR bit_field = LONG_AT(0x20) bit = 7 RET petrified = result END
                    PATCH_IF NOT petrified BEGIN
                        LPM fix_gender
                    END

                END

            BUT_ONLY

            PRINT "[INFO]: Found %matches% matches that were set to 'niether' gender"
             ACTION_IF zs_debug BEGIN
                LAF LOG_TEXT STR_VAR filename="debug" log_level="debug" message = "-- END OF GENDER CREATURE PATCHING --" END
            END

        END

        ACTION_IF NOT has_eefixpack AND FILE_EXISTS_IN_GAME ~dobone.itm~ BEGIN

            ACTION_IF zst_darts_bone BEGIN

                PRINT "[INFO]: Fixing dobone.itm (Darts of Bone) to have a speed factor of 0 (+3 Darts)"
                COPY_EXISTING ~dobone.itm~ ~override~
                    LPF ALTER_HEADER INT_VAR speed = 0 END

            END

        END

        ACTION_IF zst_shambling_mounds BEGIN

            PRINT "[INFO]: Setting Shambling Mounds to the race of Shambling Mound and Plant type"
            COPY_EXISTING ~globsham.cre~ ~override~
                          ~hgmnd2.cre~   ~override~
                          ~hgmound.cre~  ~override~
                          ~smound01.cre~ ~override~
                          ~bpshamb.cre~  ~override~
                          ~smoundsu.cre~ ~override~
                          ~sshamb.cre~   ~override~
                          ~cyshamb.cre~  ~override~
                          ~shmblr.cre~   ~override~
                WRITE_BYTE 0x271 general_plant
                WRITE_BYTE 0x272 race_shambling_mound
            IF_EXISTS

        END

        PRINT "[INFO]: ---- FINISHED PREFIXES ----"
        
    END 
    
END ELSE ACTION_IF !VARIABLE_IS_SET ~zs_prefixes~ BEGIN

    LAF LOG_TEXT INT_VAR add_level_preamble=0 STR_VAR log_level="info" message="[WARN]: You disabled prefixes. You better know what you're doing." END

END

OUTER_SET zs_prefixes = 1