OUTER_SET base_dagg_dart = 42
OUTER_SET base_sling_wk_nj = 15
OUTER_SET base_arrow_bolt = 30
OUTER_SET base_ls_staff = 5
OUTER_SET base_sci_ka = 9
OUTER_SET base_ss_club = 25

DEFINE_PATCH_MACRO PROBABILITY_BONUS
BEGIN
    PATCH_MATCH ench WITH
        0   BEGIN SET bonus=0 END
        1 2 BEGIN SET bonus=ench+1 END
        3 4 BEGIN SET bonus=ench+2 END
        5 6 BEGIN SET bonus=ench+3 END
        DEFAULT
    END
END
