ACTION_IF GAME_IS "bg2ee eet" BEGIN
    COPY_EXISTING "SPCL911.SPL" ~override~
        LPF ALTER_SPELL INT_VAR ref_desc=RESOLVE_STR_REF(@6300) END
    COPY_EXISTING "SPCL911B.SPL" ~override~
        LPF ALTER_EFFECT INT_VAR header_type=1 check_globals=0 match_opcode=12 dicenumber=15 END
        LPF ALTER_EFFECT INT_VAR header_type=1 check_globals=0 match_opcode=39 duration=6 savingthrow=0 savebonus=0 END
END
