ACTION_IF GAME_IS "bg2ee eet" BEGIN
    COPY ~%MOD_FOLDER%/class_kits/warcry~ ~override~
    COPY_EXISTING "SPCL908.SPL" ~override~
        LPF ALTER_SPELL INT_VAR ref_desc=RESOLVE_STR_REF(@6320) END
        LPF ALTER_HEADER INT_VAR projectile = 94 END
        LPF DELETE_EFFECT INT_VAR check_globals = 0 END
        LPF ADD_SPL_TGTEFF STR_VAR effects = ~op=326,p2=51,res=ZSTWWRC0;op=326,p2=49,res=ZSTWWRC1;op=326,tgt=1,res=ZSTWWRC1;op=301,p1=1,tmg=0,dur=18,rd=0,tgt=1~ END
    BUT_ONLY
END
