OUTER_SET group_component = 1

INCLUDE "ZSTweaks/libs/components/03_dagger_tweaks/zs_comp_1000.tph"
INCLUDE "ZSTweaks/libs/components/03_dagger_tweaks/zs_comp_1130.tph"
INCLUDE "ZSTweaks/libs/components/03_dagger_tweaks/zs_comp_1140.tph"
INCLUDE "ZSTweaks/libs/components/03_dagger_tweaks/zs_comp_1490.tph"
INCLUDE "ZSTweaks/libs/components/03_dagger_tweaks/zs_comp_1630.tph"
INCLUDE "ZSTweaks/libs/components/03_dagger_tweaks/zs_comp_1660.tph"
INCLUDE "ZSTweaks/libs/components/03_dagger_tweaks/zs_comp_1670.tph"
INCLUDE "ZSTweaks/libs/components/03_dagger_tweaks/zs_comp_1680.tph"
INCLUDE "ZSTweaks/libs/components/03_dagger_tweaks/zs_comp_1681.tph"
INCLUDE "ZSTweaks/libs/components/03_dagger_tweaks/zs_comp_1682.tph"
INCLUDE "ZSTweaks/libs/components/03_dagger_tweaks/zs_comp_1683.tph"
INCLUDE "ZSTweaks/libs/components/03_dagger_tweaks/zs_comp_1684.tph"

