ACTION_IF !(GAME_IS "iwdee") BEGIN
    COPY ~ZSTweaks/items/werebane~ ~override~
    COPY_EXISTING "dagg09.ITM" ~override~
        LPF ALTER_ITEM INT_VAR id_ref_desc=RESOLVE_STR_REF(@6570) END
        LPF ALTER_HEADER INT_VAR match_type = 1 speed = 0 silent = 1 END
        LPF ALTER_EFFECT INT_VAR match_opcode = 177 check_globals = 0 STR_VAR resource = ~ZSTWWED6~ END
    BUT_ONLY
END

COPY_EXISTING "LYCNHIT3.EFF" ~override~
    LPF ALTER_EFF_FILE INT_VAR parameter3 = 5 END
BUT_ONLY
