ACTION_IF !(GAME_IS "iwdee") BEGIN
    COPY_EXISTING ~SPPR611.SPL~ ~override~
        LPF ALTER_SPELL INT_VAR ref_desc=RESOLVE_STR_REF(@7420) END
        LPF ALTER_HEADER INT_VAR speed=20 END
        LPF ALTER_EFFECT INT_VAR match_opcode=261 parameter1=1 END
        LPF CLONE_EFFECT INT_VAR match_opcode=261 parameter1=0 END
        LPF CLONE_EFFECT INT_VAR match_opcode=261 parameter1=5 END
    
END
