COPY_EXISTING ~SPPR707.SPL~ ~override~
    LPF ALTER_EFFECT INT_VAR resist_dispel=3 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 177 resist_dispel = 0 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 12 resist_dispel = 0 END
BUT_ONLY

COPY_EXISTING ~UNDDEATH.EFF~ ~override~
    LPF GET_DMG_TYPE STR_VAR type = "magic" RET magic = result END
    LPF ALTER_EFF_FILE INT_VAR parameter1=100 parameter2=3 + magic END
BUT_ONLY
