ACTION_IF !(GAME_IS "iwdee") BEGIN
    COPY_EXISTING ~SPPR720.SPL~ ~override~
        LPF DELETE_EFFECT INT_VAR match_opcode = 269 END
        LPF DELETE_EFFECT STR_VAR match_resource = ~SHAKE1~ END
    BUT_ONLY

    ACTION_IF !GAME_IS "bgee" BEGIN
        COPY_EXISTING ~SPOGRE01.SPL~ ~override~
            LPF DELETE_EFFECT INT_VAR match_opcode = 269 END
            LPF DELETE_EFFECT STR_VAR match_resource = ~SHAKE1~ END
        BUT_ONLY
    END
END
